sub soh_format {
  my $outfile = shift @_;
  my %h = @_;
  print_head("$outfile","Load Review", %h);

open (SF, ">>$outfile");

printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD><TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>PCAD LOAD REVIEW PARAMETERS</FONT></TR>";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>TARGET QUATERNION</FONT></TR>";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOTARQT1     </FONT></TD>\n", ${$h{AOTARQT1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOTARQT1}}[3], ${$h{AOTARQT1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOTARQT2     </FONT></TD>\n", ${$h{AOTARQT2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOTARQT2}}[3], ${$h{AOTARQT2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOTARQT3     </FONT></TD>\n", ${$h{AOTARQT3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOTARQT3}}[3], ${$h{AOTARQT3}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOTARQT4     </FONT></TD>\n", ${$h{AOTARQT4}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOTARQT4}}[3], ${$h{AOTARQT4}}[1];

printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>MOMENTUM</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSYMOM1 </FONT></TD>\n", ${$h{AOSYMOM1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOSYMOM1}}[3], ${$h{AOSYMOM1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSYMOM2 </FONT></TD>\n", ${$h{AOSYMOM2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOSYMOM2}}[3], ${$h{AOSYMOM2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSYMOM3 </FONT></TD>\n", ${$h{AOSYMOM3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOSYMOM3}}[3], ${$h{AOSYMOM3}}[1];

printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>TEMPERATURES</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TEPHIN </FONT></TD>\n", ${$h{TEPHIN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{TEPHIN}}[3], ${$h{TEPHIN}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3TRMTRAT </FONT></TD>\n", ${$h{3TRMTRAT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{3TRMTRAT}}[3], ${$h{3TRMTRAT}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>PM1THV1T </FONT></TD>\n", ${$h{PM1THV1T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{PM2THV1T}}[3], ${$h{PM2THV1T}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>PM1THV1T </FONT></TD>\n", ${$h{PM1THV1T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{PM2THV1T}}[3], ${$h{PM2THV1T}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>1PDEAAT </FONT></TD>\n", ${$h{"1PDEAAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{"1PDEAAT"}}[3], ${$h{"1PDEAAT"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>1PIN1AT </FONT></TD>\n", ${$h{"1PIN1AT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{"1PIN1AT"}}[3], ${$h{"1PIN1AT"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TCYLAFT6 </FONT></TD>\n", ${$h{TCYLAFT6}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{TCYLAFT6}}[3], ${$h{TCYLAFT6}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TMZP_MY </FONT></TD>\n", ${$h{TMZP_MY}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{TMZP_MY}}[3], ${$h{TMZP_MY}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TCYLFMZM </FONT></TD>\n", ${$h{TCYLFMZM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{TCYLFMZM}}[3], ${$h{TCYLFMZM}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TFSSBKT1 </FONT></TD>\n", ${$h{TFSSBKT1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{TFSSBKT1}}[3], ${$h{TFSSBKT1}}[1];
printf SF "</TABLE>\n";

printf SF "<TD><TABLE BORDER=0><TR><TD><FONT SIZE=2>\&nbsp</TR></TABLE>\n";

printf SF "<TD><TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>TIME</FONT></TR>\n";
#printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>OBC VCDU     </FONT></TD>\n", ${$h{CCSDSVCD}}[3];
#printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%5.2f </FONT></TD>\n", ${$h{CCSDSVCD}}[3], ${$h{CCSDSVCD}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EPHEM TIME     </FONT></TD>\n", ${$h{AOETIMEX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%5.2f </FONT></TD>\n", ${$h{AOETIMEX}}[3], ${$h{AOETIMEX}}[1];

printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>PCAD STATE</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPCADMD     </FONT></TD>\n", ${$h{"AOPCADMD"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{"AOPCADMD"}}[3], ${$h{"AOPCADMD"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOFATTMD     </FONT></TD>\n", ${$h{"AOFATTMD"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{"AOFATTMD"}}[3], ${$h{"AOFATTMD"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AODITHEN     </FONT></TD>\n", ${$h{"AODITHEN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{"AODITHEN"}}[3], ${$h{"AODITHEN"}}[1];

printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>SOLAR ARRAY ANGLE</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSARES2     </FONT></TD>\n", ${$h{"AOSARES2"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{"AOSARES2"}}[3], ${$h{"AOSARES2"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSARES1     </FONT></TD>\n", ${$h{"AOSARES1"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{"AOSARES1"}}[3], ${$h{"AOSARES1"}}[1];

printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>SIM POSITION</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3TSCPOS     </FONT></TD>\n", ${$h{"3TSCPOS"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{"3TSCPOS"}}[3], ${$h{"3TSCPOS"}}[1];
printf SF "</TABLE>\n";

printf SF "<TD><TABLE BORDER=0><TR><TD><FONT SIZE=2>\&nbsp</TR></TABLE>\n";

printf SF "<TD><TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>PCAD</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOATTER1_DEG </FONT></TD>\n", ${$h{AOATTER1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%8.6f </FONT></TD>\n", ${$h{AOATTER1}}[3], ${$h{AOATTER1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOATTER2_DEG </FONT></TD>\n", ${$h{AOATTER2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%8.6f </FONT></TD>\n", ${$h{AOATTER2}}[3], ${$h{AOATTER2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOATTER3_DEG </FONT></TD>\n", ${$h{AOATTER3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%8.6f </FONT></TD>\n", ${$h{AOATTER3}}[3], ${$h{AOATTER3}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORATE1_DEG/SEC  </FONT></TD>\n", ${$h{AORATE1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%8.6f </FONT></TD>\n", ${$h{AORATE1}}[3], ${$h{AORATE1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORATE2_DEG/SEC  </FONT></TD>\n", ${$h{AORATE2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%8.6f </FONT></TD>\n", ${$h{AORATE2}}[3], ${$h{AORATE2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORATE3_DEG/SEC  </FONT></TD>\n", ${$h{AORATE3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%8.6f </FONT></TD>\n", ${$h{AORATE3}}[3], ${$h{AORATE3}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWSPD1_RPM </FONT></TD>\n", ${$h{AORWSPD1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%9.3f </FONT></TD>\n", ${$h{AORWSPD1}}[3], ${$h{AORWSPD1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWSPD2_RPM </FONT></TD>\n", ${$h{AORWSPD2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%9.3f </FONT></TD>\n", ${$h{AORWSPD2}}[3], ${$h{AORWSPD2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWSPD3_RPM </FONT></TD>\n", ${$h{AORWSPD3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%9.3f </FONT></TD>\n", ${$h{AORWSPD3}}[3], ${$h{AORWSPD3}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWSPD4_RPM </FONT></TD>\n", ${$h{AORWSPD4}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%9.3f </FONT></TD>\n", ${$h{AORWSPD4}}[3], ${$h{AORWSPD4}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWSPD5_RPM </FONT></TD>\n", ${$h{AORWSPD5}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%9.3f </FONT></TD>\n", ${$h{AORWSPD5}}[3], ${$h{AORWSPD5}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWSPD6_RPM </FONT></TD>\n", ${$h{AORWSPD6}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%9.3f </FONT></TD>\n", ${$h{AORWSPD6}}[3], ${$h{AORWSPD6}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPCADMD </FONT></TD>\n", ${$h{AOPCADMD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOPCADMD}}[3], ${$h{AOPCADMD}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1R1Y </FONT></TD>\n", ${$h{AIRU1R1Y}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AIRU1R1Y}}[3], ${$h{AIRU1R1Y}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1R1X </FONT></TD>\n", ${$h{AIRU1R1X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AIRU1R1X}}[3], ${$h{AIRU1R1X}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>MOMENTUM </FONT></TD>\n", ${$h{MOMENTUM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%5.3f </FONT></TD>\n", ${$h{MOMENTUM}}[3], ${$h{MOMENTUM}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOMANMON </FONT></TD>\n", ${$h{AOMANMON}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOMANMON}}[3], ${$h{AOMANMON}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSUNMON </FONT></TD>\n", ${$h{AOSUNMON}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOSUNMON}}[3], ${$h{AOSUNMON}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOIRUMON </FONT></TD>\n", ${$h{AOIRUMON}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOIRUMON}}[3], ${$h{AOIRUMON}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOATTMON </FONT></TD>\n", ${$h{AOATTMON}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOATTMON}}[3], ${$h{AOATTMON}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWMON1 </FONT></TD>\n", ${$h{AORWMON1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AORWMON1}}[3], ${$h{AORWMON1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWMON2 </FONT></TD>\n", ${$h{AORWMON2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AORWMON2}}[3], ${$h{AORWMON2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWMON3 </FONT></TD>\n", ${$h{AORWMON3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AORWMON3}}[3], ${$h{AORWMON3}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWMON4 </FONT></TD>\n", ${$h{AORWMON4}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AORWMON4}}[3], ${$h{AORWMON4}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWMON5 </FONT></TD>\n", ${$h{AORWMON5}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AORWMON5}}[3], ${$h{AORWMON5}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWMON6 </FONT></TD>\n", ${$h{AORWMON6}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AORWMON6}}[3], ${$h{AORWMON6}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOMOMMON </FONT></TD>\n", ${$h{AOMOMMON}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOMOMMON}}[3], ${$h{AOMOMMON}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOULMON  </FONT></TD>\n", ${$h{AOULMON}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOULMON}}[3], ${$h{AOULMON}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSAPMON </FONT></TD>\n", ${$h{AOSAPMON}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOSAPMON}}[3], ${$h{AOSAPMON}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSATMON </FONT></TD>\n", ${$h{AOSATMON}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOSATMON}}[3], ${$h{AOSATMON}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOLAEMON </FONT></TD>\n", ${$h{AOLAEMON}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOLAEMON}}[3], ${$h{AOLAEMON}}[1];
printf SF "<TR><TD><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "</TABLE>\n";

printf SF "</TABLE>\n";
printf SF "<BR>\n";
close SF;

print_links("$outfile");
open (SF,">>$outfile");
print SF "</BODY></HTML>\n";
close SF;
}
1;
