sub soh_format {
  $outfile = shift @_;
  %h = @_;
  print_head("$outfile","Thermal", %h);

open (SF, ">>$outfile");

printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>ISIM</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('TT AT ACIS ATTACH #1 ABORT HTR TSC1 TEMP DEGC<br><font color=#FFFF00>(-20) 20 </font><br><font color=#FF0000>(-54.5) 20</font>', CAPTION, '3TTACS1T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3TTACS1T</FONT></a></TD>\n", ${$h{"3TTACS1T"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3TTACS1T"}}[3], ${$h{"3TTACS1T"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA FA FLEXURE A TEMP A DEGC<br><font color=#FFFF00>(-22.0) 20.0 </font><br><font color=#FF0000>(-25.0) 20.0</font>', CAPTION, '3FAFLAAT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3FAFLAAT</FONT></a></TD>\n", ${$h{"3FAFLAAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3FAFLAAT"}}[3], ${$h{"3FAFLAAT"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA-A BOX TEMP DEGC<br><font color=#FFFF00>(-20) 30.0 </font><br><font color=#FF0000>(-39.5) 30.0</font>', CAPTION, '3FASEAAT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3FASEAAT</FONT></a></TD>\n", ${$h{"3FASEAAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3FASEAAT"}}[3], ${$h{"3FASEAAT"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA-A FOCUS DRIVE MOTOR TEMP DEGC<br><font color=#FFFF00>(-20) 20 </font><br><font color=#FF0000>(-48.0) 20</font>', CAPTION, '3FAMTRAT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3FAMTRAT</FONT></a></TD>\n", ${$h{"3FAMTRAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3FAMTRAT"}}[3], ${$h{"3FAMTRAT"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('TT AT ACIS ATTACH #2 ABORT HTR TSC1 TEMP DEGC<br><font color=#FFFF00>(-20) 20 </font><br><font color=#FF0000>(-54.5) 20</font>', CAPTION, '3TTACS2T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3TTACS2T</FONT></a></TD>\n", ${$h{"3TTACS2T"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3TTACS2T"}}[3], ${$h{"3TTACS2T"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA FA FLEXURE B TEMP A DEGC<br><font color=#FFFF00>(-22.0) 20.0 </font><br><font color=#FF0000>(-25.0) 20.0</font>', CAPTION, '3FAFLBAT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3FAFLBAT</FONT></a></TD>\n", ${$h{"3FAFLBAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3FAFLBAT"}}[3], ${$h{"3FAFLBAT"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA FA FLEXURE C TEMP A DEGC<br><font color=#FFFF00>(-22.0) 30 </font><br><font color=#FF0000>(-25.0) 30</font>', CAPTION, '3FAFLCAT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3FAFLCAT</FONT></a></TD>\n", ${$h{"3FAFLCAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3FAFLCAT"}}[3], ${$h{"3FAFLCAT"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA A TRANSLATION DRIVE MOTOR TEMP DEGC<br><font color=#FFFF00>(-30) 45.0 </font><br><font color=#FF0000>(-48.0) 45.0</font>', CAPTION, '3TRMTRAT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3TRMTRAT</FONT></a></TD>\n", ${$h{"3TRMTRAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3TRMTRAT"}}[3], ${$h{"3TRMTRAT"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('TT AT ACIS ATTACH #3 ABORT HTR TSC1 TEMP DEGC<br><font color=#FFFF00>(-20) 20 </font><br><font color=#FF0000>(-54.5) 20</font>', CAPTION, '3TTACS3T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3TTACS3T</FONT></a></TD>\n", ${$h{"3TTACS3T"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3TTACS3T"}}[3], ${$h{"3TTACS3T"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA A POWER SUPPLY TEMP DEGC<br><font color=#FFFF00>(-20) 60 </font><br><font color=#FF0000>(-39.5) 60</font>', CAPTION, '3FAPSAT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3FAPSAT</FONT></a></TD>\n", ${$h{"3FAPSAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3FAPSAT"}}[3], ${$h{"3FAPSAT"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FLCA BASEPLATE (+X) TEMP DEGC<br><font color=#FFFF00>(-20) 20 </font><br><font color=#FF0000>(-37.5) 20</font>', CAPTION, '3FLCABPT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3FLCABPT</FONT></a></TD>\n", ${$h{"3FLCABPT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3FLCABPT"}}[3], ${$h{"3FLCABPT"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RCTU BASEPLATE (+X) ABORT HTR TSC2 TEMP DEGC<br><font color=#FFFF00>(-20) 20 </font><br><font color=#FF0000>(-42.5) 20</font>', CAPTION, '3RCTUBPT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3RCTUBPT</FONT></a></TD>\n", ${$h{"3RCTUBPT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3RCTUBPT"}}[3], ${$h{"3RCTUBPT"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('BTU BASEPLATE (+X) ABORT HTR TSC2 DEGC<br><font color=#FFFF00>(-30) 20 </font><br><font color=#FF0000>(-62.5) 20</font>', CAPTION, '3BTU_BPT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3BTU_BPT</FONT></a></TD>\n", ${$h{"3BTU_BPT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3BTU_BPT"}}[3], ${$h{"3BTU_BPT"}}[1];
printf SF "</TABLE>\n";

printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>ACIS</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('COLD RADIATOR TEMP. A DEGC<br><font color=#FFFF00>(-137.0) -100 </font><br><font color=#FF0000>(-142.0) -100</font>', CAPTION, '1CRAT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>1CRAT</FONT></a></TD>\n", ${$h{"1CRAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"1CRAT"}}[3], ${$h{"1CRAT"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('WARM RADIATOR TEMP A DEGC<br><font color=#FFFF00>(-90) -70 </font><br><font color=#FF0000>(-103.5) -70</font>', CAPTION, '1WRAT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>1WRAT</FONT></a></TD>\n", ${$h{"1WRAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"1WRAT"}}[3], ${$h{"1WRAT"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('DPA -Z PANEL TEMP (RT830) DEGC<br><font color=#FFFF00>(-20) 20 </font><br><font color=#FF0000>(-37.5) 20</font>', CAPTION, '1DPAMZT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>1DPAMZT</FONT></a></TD>\n", ${$h{"1DPAMZT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"1DPAMZT"}}[3], ${$h{"1DPAMZT"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PSMC TEMP 1A DEGC<br><font color=#FFFF00>(-20) 30 </font><br><font color=#FF0000>(-36.5) 30</font>', CAPTION, '1PIN1AT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>1PIN1AT</FONT></a></TD>\n", ${$h{"1PIN1AT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"1PIN1AT"}}[3], ${$h{"1PIN1AT"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('CAMERA BODY TEMP. B DEGC<br><font color=#FFFF00>(-70.5) -52 </font><br><font color=#FF0000>(-75.5) -52</font>', CAPTION, '1CBBT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>1CBBT</FONT></a></TD>\n", ${$h{"1CBBT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"1CBBT"}}[3], ${$h{"1CBBT"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('WARM RADIATOR TEMP B DEGC<br><font color=#FFFF00>(-90) -70 </font><br><font color=#FF0000>(-103.5) -70</font>', CAPTION, '1WRBT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>1WRBT</FONT></a></TD>\n", ${$h{"1WRBT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"1WRBT"}}[3], ${$h{"1WRBT"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('DEA -Z PANEL TEMP (RT830) DEGC<br><font color=#FFFF00>(-20) 20 </font><br><font color=#FF0000>(-37.5) 20</font>', CAPTION, '1DEAMZT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>1DEAMZT</FONT></a></TD>\n", ${$h{"1DEAMZT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"1DEAMZT"}}[3], ${$h{"1DEAMZT"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('CAMERA BODY TEMP. A DEGC<br><font color=#FFFF00>(-70.5) -52 </font><br><font color=#FF0000>(-75.5) -52</font>', CAPTION, '1CBAT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>1CBAT</FONT></a></TD>\n", ${$h{"1CBAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"1CBAT"}}[3], ${$h{"1CBAT"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('COLD RADIATOR TEMP. B DEGC<br><font color=#FFFF00>(-137.0) -100 </font><br><font color=#FF0000>(-142.0) -100</font>', CAPTION, '1CRBT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>1CRBT</FONT></a></TD>\n", ${$h{"1CRBT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"1CRBT"}}[3], ${$h{"1CRBT"}}[1];
printf SF "</TABLE>\n";

printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>HRC</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FRONT END ASSEMBLY +Y AT RADIATOR CENTER TEMP DEGC<br><font color=#FFFF00>(0) 35 </font><br><font color=#FF0000>(-40.0) 35</font>', CAPTION, '2FRADPYT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>2FRADPYT</FONT></a></TD>\n", ${$h{"2FRADPYT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"2FRADPYT"}}[3], ${$h{"2FRADPYT"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('CENTRAL ELECTRONICS BOX TEMP DEGC<br><font color=#FFFF00>(0) 35 </font><br><font color=#FF0000>(-37.5) 35</font>', CAPTION, '2CHTRPZT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>2CHTRPZT</FONT></a></TD>\n", ${$h{"2CHTRPZT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"2CHTRPZT"}}[3], ${$h{"2CHTRPZT"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('DETECTOR HOUSING TEMP 1 DEGC<br><font color=#FFFF00>(0) 35 </font><br><font color=#FF0000>(-15.0) 35</font>', CAPTION, '2DTSTATT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>2DTSTATT</FONT></a></TD>\n", ${$h{"2DTSTATT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"2DTSTATT"}}[3], ${$h{"2DTSTATT"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('DETECTOR HOUSING TEMP 2 DEGC<br><font color=#FFFF00>(0) 35 </font><br><font color=#FF0000>(-12.5) 35</font>', CAPTION, '2DCENTRT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>2DCENTRT</FONT></a></TD>\n", ${$h{"2DCENTRT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"2DCENTRT"}}[3], ${$h{"2DCENTRT"}}[1];
printf SF "</TABLE>\n";

printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>PCAD_COMP</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RWA -1 TEMP (RWA CRNR COMP) DEGF<br><font color=#FFFF00>(15) 80 </font><br><font color=#FF0000>(5.0) 80</font>', CAPTION, 'TCYZ_RW1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TCYZ_RW1</FONT></a></TD>\n", ${$h{"TCYZ_RW1"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TCYZ_RW1"}}[3], ${$h{"TCYZ_RW1"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('CEA TEMP DEGF<br><font color=#FFFF00>(10) 70 </font><br><font color=#FF0000>(-29.0) 70</font>', CAPTION, 'TPC_CEA' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TPC_CEA</FONT></a></TD>\n", ${$h{"TPC_CEA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TPC_CEA"}}[3], ${$h{"TPC_CEA"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('ESE TEMP DEGF<br><font color=#FFFF00>(5) 70 </font><br><font color=#FF0000>(-13.0) 70</font>', CAPTION, 'TPC_ESE' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TPC_ESE</FONT></a></TD>\n", ${$h{"TPC_ESE"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TPC_ESE"}}[3], ${$h{"TPC_ESE"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('-Y SADA TEMP DEGF<br><font color=#FFFF00>(5.0) 70 </font><br><font color=#FF0000>(-4.0) 70</font>', CAPTION, 'TMYSADA' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TMYSADA</FONT></a></TD>\n", ${$h{"TMYSADA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TMYSADA"}}[3], ${$h{"TMYSADA"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RWA -6 TEMP (RWA CRNR COMP) DEGF<br><font color=#FFFF00>(15) 80 </font><br><font color=#FF0000>(5.0) 80</font>', CAPTION, 'TCYZ_RW6' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TCYZ_RW6</FONT></a></TD>\n", ${$h{"TCYZ_RW6"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TCYZ_RW6"}}[3], ${$h{"TCYZ_RW6"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('DEA TEMP DEGF<br><font color=#FFFF00>(10) 70 </font><br><font color=#FF0000>(-29.0) 70</font>', CAPTION, 'TPC_DEA' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TPC_DEA</FONT></a></TD>\n", ${$h{"TPC_DEA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TPC_DEA"}}[3], ${$h{"TPC_DEA"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FSSE TEMP (BTWN UNITS) DEGF<br><font color=#FFFF00>(-4) 70 </font><br><font color=#FF0000>(-22.0) 70</font>', CAPTION, 'TPC_FSSE' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TPC_FSSE</FONT></a></TD>\n", ${$h{"TPC_FSSE"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TPC_FSSE"}}[3], ${$h{"TPC_FSSE"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RWA -2 TEMP (+Z PCAD COMP) DEGF<br><font color=#FFFF00>(15) 80 </font><br><font color=#FF0000>(5.0) 80</font>', CAPTION, 'TPCP_RW2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TPCP_RW2</FONT></a></TD>\n", ${$h{"TPCP_RW2"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TPCP_RW2"}}[3], ${$h{"TPCP_RW2"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('WDA TEMP DEGF<br><font color=#FFFF00>(-10) 70 </font><br><font color=#FF0000>(-29.0) 70</font>', CAPTION, 'TPC_WDA' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TPC_WDA</FONT></a></TD>\n", ${$h{"TPC_WDA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TPC_WDA"}}[3], ${$h{"TPC_WDA"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RCTU-PC TEMP DEGF<br><font color=#FFFF00>(-4.0) 70 </font><br><font color=#FF0000>(-49.0) 70</font>', CAPTION, 'TPC_RCTU' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TPC_RCTU</FONT></a></TD>\n", ${$h{"TPC_RCTU"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TPC_RCTU"}}[3], ${$h{"TPC_RCTU"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RWA -3 TEMP (+Z PCAD COMP) DEGF<br><font color=#FFFF00>(15) 80 </font><br><font color=#FF0000>(5.0) 80</font>', CAPTION, 'TPCP_RW3' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TPCP_RW3</FONT></a></TD>\n", ${$h{"TPCP_RW3"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TPCP_RW3"}}[3], ${$h{"TPCP_RW3"}}[1];
printf SF "</TABLE>\n";

printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>CCDM_COMP</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SS RECORDER-1 TEMP DEGF<br><font color=#FFFF00>(20) 75 </font><br><font color=#FF0000>(-4.0) 75</font>', CAPTION, 'TCM_SSR1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TCM_SSR1</FONT></a></TD>\n", ${$h{"TCM_SSR1"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TCM_SSR1"}}[3], ${$h{"TCM_SSR1"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('CTU TEMP DEGF<br><font color=#FFFF00>(0) 75 </font><br><font color=#FF0000>(-13.0) 75</font>', CAPTION, 'TCM_CTU' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TCM_CTU</FONT></a></TD>\n", ${$h{"TCM_CTU"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TCM_CTU"}}[3], ${$h{"TCM_CTU"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('USO TEMP DEGF<br><font color=#FFFF00>(0) 75 </font><br><font color=#FF0000>(-13.0) 75</font>', CAPTION, 'TCM_USO' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TCM_USO</FONT></a></TD>\n", ${$h{"TCM_USO"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TCM_USO"}}[3], ${$h{"TCM_USO"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RWA -4 TEMP (-Z PCAD COMP) DEGF<br><font color=#FFFF00>(15) 80 </font><br><font color=#FF0000>(5.0) 80</font>', CAPTION, 'TPCM_RW4' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TPCM_RW4</FONT></a></TD>\n", ${$h{"TPCM_RW4"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TPCM_RW4"}}[3], ${$h{"TPCM_RW4"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SS RECORDER-2 TEMP DEGF<br><font color=#FFFF00>(20) 75 </font><br><font color=#FF0000>(-4.0) 75</font>', CAPTION, 'TCM_SSR2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TCM_SSR2</FONT></a></TD>\n", ${$h{"TCM_SSR2"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TCM_SSR2"}}[3], ${$h{"TCM_SSR2"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('OBC TEMP DEGF<br><font color=#FFFF00>(0) 75 </font><br><font color=#FF0000>(-13.0) 75</font>', CAPTION, 'TCM_OBC' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TCM_OBC</FONT></a></TD>\n", ${$h{"TCM_OBC"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TCM_OBC"}}[3], ${$h{"TCM_OBC"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IU TEMP DEGF<br><font color=#FFFF00>(0) 75 </font><br><font color=#FF0000>(-13.0) 75</font>', CAPTION, 'TCM_IFU' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TCM_IFU</FONT></a></TD>\n", ${$h{"TCM_IFU"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TCM_IFU"}}[3], ${$h{"TCM_IFU"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RWA -5 TEMP (-Z PCAD COMP) DEGF<br><font color=#FFFF00>(15) 80 </font><br><font color=#FF0000>(5.0) 80</font>', CAPTION, 'TPCM_RW5' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TPCM_RW5</FONT></a></TD>\n", ${$h{"TPCM_RW5"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TPCM_RW5"}}[3], ${$h{"TPCM_RW5"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('TRANSPONDER-1 EXT BPL TEMP DEGF<br><font color=#FFFF00>(10) 75 </font><br><font color=#FF0000>(-4.0) 75</font>', CAPTION, 'TCM_TX1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TCM_TX1</FONT></a></TD>\n", ${$h{"TCM_TX1"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TCM_TX1"}}[3], ${$h{"TCM_TX1"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RF POWER AMP-1 EXT BPL TEMP DEGF<br><font color=#FFFF00>(-4.0) 75 </font><br><font color=#FF0000>(-13.0) 75</font>', CAPTION, 'TCM_PA1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TCM_PA1</FONT></a></TD>\n", ${$h{"TCM_PA1"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TCM_PA1"}}[3], ${$h{"TCM_PA1"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RF ASSEMBLY TEMP DEGF<br><font color=#FFFF00>(0) 75 </font><br><font color=#FF0000>(-29.0) 75</font>', CAPTION, 'TCM_RFAS' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TCM_RFAS</FONT></a></TD>\n", ${$h{"TCM_RFAS"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TCM_RFAS"}}[3], ${$h{"TCM_RFAS"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('+Y SADA TEMP DEGF<br><font color=#FFFF00>(5.0) 70 </font><br><font color=#FF0000>(-4.0) 70</font>', CAPTION, 'TPYSADA' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TPYSADA</FONT></a></TD>\n", ${$h{"TPYSADA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TPYSADA"}}[3], ${$h{"TPYSADA"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('TRANSPONDER-2 EXT BPL TEMP DEGF<br><font color=#FFFF00>(10) 75 </font><br><font color=#FF0000>(-4.0) 75</font>', CAPTION, 'TCM_TX2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TCM_TX2</FONT></a></TD>\n", ${$h{"TCM_TX2"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TCM_TX2"}}[3], ${$h{"TCM_TX2"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RF POWER AMP-2 EXT BPL TEMP DEGF<br><font color=#FFFF00>(-4.0) 75 </font><br><font color=#FF0000>(-13.0) 75</font>', CAPTION, 'TCM_PA2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TCM_PA2</FONT></a></TD>\n", ${$h{"TCM_PA2"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TCM_PA2"}}[3], ${$h{"TCM_PA2"}}[1];
printf SF "</TABLE>\n";

printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>EPS_COMP</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PCU TEMP DEGF<br><font color=#FFFF00>(10) 70 </font><br><font color=#FF0000>(-9.0) 70</font>', CAPTION, 'TEP_PCU' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TEP_PCU</FONT></a></TD>\n", ${$h{"TEP_PCU"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TEP_PCU"}}[3], ${$h{"TEP_PCU"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RCTU-EP TEMP DEGF<br><font color=#FFFF00>(-4.0) 70 </font><br><font color=#FF0000>(-49.0) 70</font>', CAPTION, 'TEP_RCTU' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TEP_RCTU</FONT></a></TD>\n", ${$h{"TEP_RCTU"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TEP_RCTU"}}[3], ${$h{"TEP_RCTU"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PSU-1 TEMP DEGF<br><font color=#FFFF00>(10) 70 </font><br><font color=#FF0000>(-9.0) 70</font>', CAPTION, 'TEP_PSU1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TEP_PSU1</FONT></a></TD>\n", ${$h{"TEP_PSU1"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TEP_PSU1"}}[3], ${$h{"TEP_PSU1"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PSU-2 TEMP DEGF<br><font color=#FFFF00>(10) 70 </font><br><font color=#FF0000>(-9.0) 70</font>', CAPTION, 'TEP_PSU2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TEP_PSU2</FONT></a></TD>\n", ${$h{"TEP_PSU2"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TEP_PSU2"}}[3], ${$h{"TEP_PSU2"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('EIA TEMP DEGF<br><font color=#FFFF00>(10) 70 </font><br><font color=#FF0000>(-9.0) 70</font>', CAPTION, 'TEP_EIA' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TEP_EIA</FONT></a></TD>\n", ${$h{"TEP_EIA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"TEP_EIA"}}[3], ${$h{"TEP_EIA"}}[1];
printf SF "</TABLE>\n";

printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>IP SIDE A</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IP A: +15 VOLT MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4IP15AV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4IP15AV</FONT></a></TD>\n", ${$h{"4IP15AV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4IP15AV"}}[3], ${$h{"4IP15AV"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IP A: -15 VOLT MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4IN15AV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4IN15AV</FONT></a></TD>\n", ${$h{"4IN15AV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4IN15AV"}}[3], ${$h{"4IN15AV"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IP A: +5 VOLT MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4IP5AV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4IP5AV</FONT></a></TD>\n", ${$h{"4IP5AV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4IP5AV"}}[3], ${$h{"4IP5AV"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IP A: HRMA MUX +10 VOLT REFERENCE MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4VRMHAV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4VRMHAV</FONT></a></TD>\n", ${$h{"4VRMHAV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4VRMHAV"}}[3], ${$h{"4VRMHAV"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IP A: PRT +5 VOLT EXCITATION MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4PRTAV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4PRTAV</FONT></a></TD>\n", ${$h{"4PRTAV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4PRTAV"}}[3], ${$h{"4PRTAV"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IP A: HRMA CURRENT SOURCE DRIVE MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4CSDHAV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4CSDHAV</FONT></a></TD>\n", ${$h{"4CSDHAV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4CSDHAV"}}[3], ${$h{"4CSDHAV"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IP A: OBA CURRENT SOURCE DRIVE MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4CSDOAV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4CSDOAV</FONT></a></TD>\n", ${$h{"4CSDOAV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4CSDOAV"}}[3], ${$h{"4CSDOAV"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IP A: OBA +10 VOLT REFERENCE MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4VRMOAV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4VRMOAV</FONT></a></TD>\n", ${$h{"4VRMOAV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4VRMOAV"}}[3], ${$h{"4VRMOAV"}}[1];
printf SF "</TABLE>\n";

printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>IP SIDE B</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IP B: +15 VOLT MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4IP15BV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4IP15BV</FONT></a></TD>\n", ${$h{"4IP15BV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4IP15BV"}}[3], ${$h{"4IP15BV"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IP B: -15 VOLT MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4IN15BV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4IN15BV</FONT></a></TD>\n", ${$h{"4IN15BV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4IN15BV"}}[3], ${$h{"4IN15BV"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IP B: +5 VOLT MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4IP5BV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4IP5BV</FONT></a></TD>\n", ${$h{"4IP5BV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4IP5BV"}}[3], ${$h{"4IP5BV"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IP B: HRMA MUX +10 VOLT REFERENCE MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4VRMHBV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4VRMHBV</FONT></a></TD>\n", ${$h{"4VRMHBV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4VRMHBV"}}[3], ${$h{"4VRMHBV"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IP B: PRT +5 VOLT EXCITATION MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4PRTBV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4PRTBV</FONT></a></TD>\n", ${$h{"4PRTBV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4PRTBV"}}[3], ${$h{"4PRTBV"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IP B: HRMA CURRENT SOURCE DRIVE MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4CSDHBV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4CSDHBV</FONT></a></TD>\n", ${$h{"4CSDHBV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4CSDHBV"}}[3], ${$h{"4CSDHBV"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IP B: OBA CURRENT SOURCE DRIVE MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4CSDOBV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4CSDOBV</FONT></a></TD>\n", ${$h{"4CSDOBV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4CSDOBV"}}[3], ${$h{"4CSDOBV"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IP B: OBA +10 VOLT REFERENCE MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4VRMOBV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4VRMOBV</FONT></a></TD>\n", ${$h{"4VRMOBV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4VRMOBV"}}[3], ${$h{"4VRMOBV"}}[1];
printf SF "</TABLE>\n";

printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD><TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>SEA 1</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 1: POWER BUS 1 STATUS MONITOR <br>  ENAB DISA', CAPTION, '4S1PWR01' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S1PWR01</FONT></a></TD>\n", ${$h{"4S1PWR01"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S1PWR01"}}[3], ${$h{"4S1PWR01"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 1: +5 VOLT MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4SP51V' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4SP51V</FONT></a></TD>\n", ${$h{"4SP51V"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4SP51V"}}[3], ${$h{"4SP51V"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 1: POWER BUS 2 STATUS MONITOR <br>  ENAB DISA', CAPTION, '4S1PWR02' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S1PWR02</FONT></a></TD>\n", ${$h{"4S1PWR02"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S1PWR02"}}[3], ${$h{"4S1PWR02"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 1: OBC MONITOR RECEIVER CIRCUIT STATUS MONITOR <br>  RECV TO', CAPTION, '4S1IMOK' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S1IMOK</FONT></a></TD>\n", ${$h{"4S1IMOK"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S1IMOK"}}[3], ${$h{"4S1IMOK"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 1: POWER BUS 3 STATUS MONITOR <br>  DISA ENAB', CAPTION, '4S1PWR03' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S1PWR03</FONT></a></TD>\n", ${$h{"4S1PWR03"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S1PWR03"}}[3], ${$h{"4S1PWR03"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 1: OBC MONITOR ENAB/DISA RELAY STATUS MONITOR <br>  DISA ENAB', CAPTION, '4S1IOMX' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S1IOMX</FONT></a></TD>\n", ${$h{"4S1IOMX"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S1IOMX"}}[3], ${$h{"4S1IOMX"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 1: POWER BUS 4 STATUS MONITOR <br>  ENAB DISA', CAPTION, '4S1PWR04' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S1PWR04</FONT></a></TD>\n", ${$h{"4S1PWR04"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S1PWR04"}}[3], ${$h{"4S1PWR04"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 1: POWER BUS 5 STATUS MONITOR <br>  ENAB DISA', CAPTION, '4S1PWR05' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S1PWR05</FONT></a></TD>\n", ${$h{"4S1PWR05"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S1PWR05"}}[3], ${$h{"4S1PWR05"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 1: POWER BUS 6 STATUS MONITOR <br>  ENAB DISA', CAPTION, '4S1PWR06' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S1PWR06</FONT></a></TD>\n", ${$h{"4S1PWR06"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S1PWR06"}}[3], ${$h{"4S1PWR06"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 1: POWER BUS 7 STATUS MONITOR <br>  ENAB DISA', CAPTION, '4S1PWR07' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S1PWR07</FONT></a></TD>\n", ${$h{"4S1PWR07"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S1PWR07"}}[3], ${$h{"4S1PWR07"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 1: POWER BUS 8 STATUS MONITOR <br>  DISA ENAB', CAPTION, '4S1PWR08' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S1PWR08</FONT></a></TD>\n", ${$h{"4S1PWR08"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S1PWR08"}}[3], ${$h{"4S1PWR08"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 1: POWER BUS 9 STATUS MONITOR <br>  DISA ENAB', CAPTION, '4S1PWR09' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S1PWR09</FONT></a></TD>\n", ${$h{"4S1PWR09"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S1PWR09"}}[3], ${$h{"4S1PWR09"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 1: POWER BUS 10 STATUS MONITOR <br>  ENAB DISA', CAPTION, '4S1PWR10' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S1PWR10</FONT></a></TD>\n", ${$h{"4S1PWR10"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S1PWR10"}}[3], ${$h{"4S1PWR10"}}[1];
printf SF "</TABLE>\n";

printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD><TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>SEA 2</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 2: POWER BUS 1 STATUS MONITOR <br>  ENAB DISA', CAPTION, '4S2PWR01' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S2PWR01</FONT></a></TD>\n", ${$h{"4S2PWR01"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S2PWR01"}}[3], ${$h{"4S2PWR01"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 2: +5 VOLT MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4SP52V' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4SP52V</FONT></a></TD>\n", ${$h{"4SP52V"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4SP52V"}}[3], ${$h{"4SP52V"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 2: POWER BUS 2 STATUS MONITOR <br>  ENAB DISA', CAPTION, '4S2PWR02' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S2PWR02</FONT></a></TD>\n", ${$h{"4S2PWR02"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S2PWR02"}}[3], ${$h{"4S2PWR02"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 2: OBC MONITOR RECEIVER CIRCUIT STATUS MONITOR <br>  TO RECV', CAPTION, '4S2IMOK' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S2IMOK</FONT></a></TD>\n", ${$h{"4S2IMOK"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S2IMOK"}}[3], ${$h{"4S2IMOK"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 2: POWER BUS 3 STATUS MONITOR <br>  ENAB DISA', CAPTION, '4S2PWR03' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S2PWR03</FONT></a></TD>\n", ${$h{"4S2PWR03"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S2PWR03"}}[3], ${$h{"4S2PWR03"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 2: OBC MONITOR ENAB/DISA RELAY STATUS MONITOR <br>  ENAB DISA', CAPTION, '4S2IOMX' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S2IOMX</FONT></a></TD>\n", ${$h{"4S2IOMX"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S2IOMX"}}[3], ${$h{"4S2IOMX"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 2: POWER BUS 4 STATUS MONITOR <br>  ENAB DISA', CAPTION, '4S2PWR04' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S2PWR04</FONT></a></TD>\n", ${$h{"4S2PWR04"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S2PWR04"}}[3], ${$h{"4S2PWR04"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 2: POWER BUS 5 STATUS MONITOR <br>  DISA ENAB', CAPTION, '4S2PWR05' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S2PWR05</FONT></a></TD>\n", ${$h{"4S2PWR05"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S2PWR05"}}[3], ${$h{"4S2PWR05"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 2: POWER BUS 6 STATUS MONITOR <br>  DISA ENAB', CAPTION, '4S2PWR06' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S2PWR06</FONT></a></TD>\n", ${$h{"4S2PWR06"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S2PWR06"}}[3], ${$h{"4S2PWR06"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 2: POWER BUS 7 STATUS MONITOR <br>  ENAB DISA', CAPTION, '4S2PWR07' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S2PWR07</FONT></a></TD>\n", ${$h{"4S2PWR07"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S2PWR07"}}[3], ${$h{"4S2PWR07"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 2: POWER BUS 8 STATUS MONITOR <br>  ENAB DISA', CAPTION, '4S2PWR08' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S2PWR08</FONT></a></TD>\n", ${$h{"4S2PWR08"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S2PWR08"}}[3], ${$h{"4S2PWR08"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 2: POWER BUS 9 STATUS MONITOR <br>  ENAB DISA', CAPTION, '4S2PWR09' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S2PWR09</FONT></a></TD>\n", ${$h{"4S2PWR09"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S2PWR09"}}[3], ${$h{"4S2PWR09"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 2: POWER BUS 10 STATUS MONITOR <br>  ENAB DISA', CAPTION, '4S2PWR10' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4S2PWR10</FONT></a></TD>\n", ${$h{"4S2PWR10"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4S2PWR10"}}[3], ${$h{"4S2PWR10"}}[1];
printf SF "</TABLE>\n";
printf SF "</TABLE>\n";
printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>EPHIN</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('EPHIN SENSOR HOUSING TEMP DEGF<br><font color=#FFFF00>(10.0) 81.0 </font><br><font color=#FF0000>(5.0) 81.0</font>', CAPTION, 'TEPHIN' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>TEPHIN</FONT></a></TD>\n", ${$h{"TEPHIN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.2f</FONT></TD>\n", ${$h{"TEPHIN"}}[3], ${$h{"TEPHIN"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('EPHIN HOUSEKEEPING EBOX: TEMPERATURE / DEG C DEGC<br><font color=#FFFF00>(-5.0) 35.0 </font><br><font color=#FF0000>(-20.0) 35.0</font>', CAPTION, '5EHSE300' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>5EHSE300</FONT></a></TD>\n", ${$h{"5EHSE300"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.2f</FONT></TD>\n", ${$h{"5EHSE300"}}[3], ${$h{"5EHSE300"}}[1];
printf SF "</TABLE>\n";

printf SF "<BR>\n";
close SF;

print_links("$outfile");
print SF "</BODY></HTML>\n";
close SF;
# end
}
1;
