sub soh_format {
  $outfile = shift @_;
  %h = @_;

  print_head("$outfile","Mechanisms", %h);

open (SF, ">>$outfile");

printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD><TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=3><FONT SIZE=4>SIM</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3SEAPENA</FONT></TD>\n", ${$h{"3SEAPENA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>SEA Power Enable Flag</FONT></TD>\n", ${$h{"3SEAPENA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SEAPENA"}}[3], ${$h{"3SEAPENA"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3SEAPSMA</FONT></TD>\n", ${$h{"3SEAPSMA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>SEA Power ON Flag</FONT></TD>\n", ${$h{"3SEAPSMA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SEAPSMA"}}[3], ${$h{"3SEAPSMA"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3MTRAEN</FONT></TD>\n", ${$h{"3MTRAEN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Motor/Brake Enable</FONT></TD>\n", ${$h{"3MTRAEN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3MTRAEN"}}[3], ${$h{"3MTRAEN"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3SEATMUP</FONT></TD>\n", ${$h{"3SEATMUP"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Heartbeat</FONT></TD>\n", ${$h{"3SEATMUP"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SEATMUP"}}[3], ${$h{"3SEATMUP"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3SEAID</FONT></TD>\n", ${$h{"3SEAID"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>SEA ID</FONT></TD>\n", ${$h{"3SEAID"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SEAID"}}[3], ${$h{"3SEAID"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3TSCPOS</FONT></TD>\n", ${$h{"3TSCPOS"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Translation Position</FONT></TD>\n", ${$h{"3TSCPOS"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%d</FONT></TD>\n", ${$h{"3TSCPOS"}}[3], ${$h{"3TSCPOS"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3FAPOS</FONT></TD>\n", ${$h{"3FAPOS"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Focus Position</FONT></TD>\n", ${$h{"3FAPOS"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%d</FONT></TD>\n", ${$h{"3FAPOS"}}[3], ${$h{"3FAPOS"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3TSCMOVE</FONT></TD>\n", ${$h{"3TSCMOVE"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TSC Moving Flag</FONT></TD>\n", ${$h{"3TSCMOVE"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3TSCMOVE"}}[3], ${$h{"3TSCMOVE"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3FAMOVE</FONT></TD>\n", ${$h{"3FAMOVE"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>FA Moving Flag</FONT></TD>\n", ${$h{"3FAMOVE"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3FAMOVE"}}[3], ${$h{"3FAMOVE"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3SEAINCM</FONT></TD>\n", ${$h{"3SEAINCM"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Invalid Command Flag</FONT></TD>\n", ${$h{"3SEAINCM"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SEAINCM"}}[3], ${$h{"3SEAINCM"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3SEARSET</FONT></TD>\n", ${$h{"3SEARSET"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Reset Flag</FONT></TD>\n", ${$h{"3SEARSET"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SEARSET"}}[3], ${$h{"3SEARSET"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3SEAROMF</FONT></TD>\n", ${$h{"3SEAROMF"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ROM Fail Flag</FONT></TD>\n", ${$h{"3SEAROMF"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SEAROMF"}}[3], ${$h{"3SEAROMF"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3SEARAMF</FONT></TD>\n", ${$h{"3SEARAMF"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>RAM Fail Flag</FONT></TD>\n", ${$h{"3SEARAMF"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SEARAMF"}}[3], ${$h{"3SEARAMF"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3MRMMXMV</FONT></TD>\n", ${$h{"3MRMMXMV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>MAX PWM Level</FONT></TD>\n", ${$h{"3MRMMXMV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%d</FONT></TD>\n", ${$h{"3MRMMXMV"}}[3], ${$h{"3MRMMXMV"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3SMOTOC</FONT></TD>\n", ${$h{"3SMOTOC"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Motor Overcurrent Cntr</FONT></TD>\n", ${$h{"3SMOTOC"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%d</FONT></TD>\n", ${$h{"3SMOTOC"}}[3], ${$h{"3SMOTOC"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3SMOTSTL</FONT></TD>\n", ${$h{"3SMOTSTL"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Motor Stall Cntr</FONT></TD>\n", ${$h{"3SMOTSTL"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%d</FONT></TD>\n", ${$h{"3SMOTSTL"}}[3], ${$h{"3SMOTSTL"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3LDRTMEK</FONT></TD>\n", ${$h{"3LDRTMEK"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Last Tab Detect Flag</FONT></TD>\n", ${$h{"3LDRTMEK"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3LDRTMEK"}}[3], ${$h{"3LDRTMEK"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3LDRTNO</FONT></TD>\n", ${$h{"3LDRTNO"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Last Tab Number</FONT></TD>\n", ${$h{"3LDRTNO"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3LDRTNO"}}[3], ${$h{"3LDRTNO"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3STAB2EN</FONT></TD>\n", ${$h{"3STAB2EN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Tab 2 Auto-Update Enable</FONT></TD>\n", ${$h{"3STAB2EN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3STAB2EN"}}[3], ${$h{"3STAB2EN"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3LDRTPOS</FONT></TD>\n", ${$h{"3LDRTPOS"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Last Tab Update Value</FONT></TD>\n", ${$h{"3LDRTPOS"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%d</FONT></TD>\n", ${$h{"3LDRTPOS"}}[3], ${$h{"3LDRTPOS"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3SMOTPEN</FONT></TD>\n", ${$h{"3SMOTPEN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Motor Power Flag</FONT></TD>\n", ${$h{"3SMOTPEN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SMOTPEN"}}[3], ${$h{"3SMOTPEN"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3SMOTSEL</FONT></TD>\n", ${$h{"3SMOTSEL"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Motor Select Flag</FONT></TD>\n", ${$h{"3SMOTSEL"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SMOTSEL"}}[3], ${$h{"3SMOTSEL"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3TRMTRAT</FONT></TD>\n", ${$h{"3TRMTRAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TSC Motor Temp</FONT></TD>\n", ${$h{"3TRMTRAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3TRMTRAT"}}[3], ${$h{"3TRMTRAT"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3FAMTRAT</FONT></TD>\n", ${$h{"3FAMTRAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>FA Motor Temp</FONT></TD>\n", ${$h{"3FAMTRAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3FAMTRAT"}}[3], ${$h{"3FAMTRAT"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3FAPSAT</FONT></TD>\n", ${$h{"3FAPSAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>SEA PS Temp</FONT></TD>\n", ${$h{"3FAPSAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3FAPSAT"}}[3], ${$h{"3FAPSAT"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3FASEAAT</FONT></TD>\n", ${$h{"3FASEAAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>SEA Box Temp</FONT></TD>\n", ${$h{"3FASEAAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3FASEAAT"}}[3], ${$h{"3FASEAAT"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4SP51V</FONT></TD>\n", ${$h{"4SP51V"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>SEA 1: +5V Monitor</FONT></TD>\n", ${$h{"4SP51V"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4SP51V"}}[3], ${$h{"4SP51V"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4SP52V</FONT></TD>\n", ${$h{"4SP52V"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>SEA 2: +5V Monitor</FONT></TD>\n", ${$h{"4SP52V"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4SP52V"}}[3], ${$h{"4SP52V"}}[1];
printf SF "</TABLE>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD><TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>OTG</FONT></TR>";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4HPOSARO</FONT></TD>\n", ${$h{"4HPOSARO"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4HPOSARO"}}[3], ${$h{"4HPOSARO"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4HPOSBRO</FONT></TD>\n", ${$h{"4HPOSBRO"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4HPOSBRO"}}[3], ${$h{"4HPOSBRO"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4LPOSARO</FONT></TD>\n", ${$h{"4LPOSARO"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4LPOSARO"}}[3], ${$h{"4LPOSARO"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4LPOSBRO</FONT></TD>\n", ${$h{"4LPOSBRO"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4LPOSBRO"}}[3], ${$h{"4LPOSBRO"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "</TABLE>\n";
printf SF "</TABLE>\n";
printf SF "<BR>\n";
close SF;

print_links("$outfile");
open (SF,">>$outfile");
print SF "</BODY></HTML>\n";
close SF;
# end
}
1;
