sub soh_format {
  my $outfile = shift @_;
  my %h = @_;
  print_head("$outfile","Top Level", %h);

open (SF, ">>$outfile");

printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD><TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>Safemode</FONT></TR>";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IU-B ON/OFF <br>  OFF ON', CAPTION, 'CIUB     ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CIUB     </FONT></a></TD>\n", ${$h{CIUB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CIUB}}[3], ${$h{CIUB}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('CTU TELEMETRY PROC ON/OFF (R) <br>  ON OFF', CAPTION, 'CTUTMPRD ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CTUTMPRD </FONT></a></TD>\n", ${$h{CTUTMPRD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CTUTMPRD}}[3], ${$h{CTUTMPRD}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IU-B OBC-A RUN/HALT <br>  HALT RUN', CAPTION, 'CIUBCARH ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CIUBCARH </FONT></a></TD>\n", ${$h{CIUBCARH}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CIUBCARH}}[3], ${$h{CIUBCARH}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IU OBC-A ONLINE/OFFLINE <br>  ONLN OFLN', CAPTION, 'CIUCALIN ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CIUCALIN </FONT></a></TD>\n", ${$h{CIUCALIN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CIUCALIN}}[3], ${$h{CIUCALIN}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IU OBC-B ONLINE/OFFLINE <br>  ONLN OFLN', CAPTION, 'CIUCBLIN ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CIUCBLIN </FONT></a></TD>\n", ${$h{CIUCBLIN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CIUCBLIN}}[3], ${$h{CIUCBLIN}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEQ COMPL/NOT COMPLETE OBC B PRI (CH0) <br>  NCMP CMPL', CAPTION, 'C1SQOBBP ' );\" onmouseout=\"return nd();\"> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEQ COMPL/NOT COMPLETE OBC B PRI (CH0) <br>  NCMP CMPL', CAPTION, 'C1SQOBBP ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>C1SQOBBP </FONT></a></a></TD>\n", ${$h{C1SQOBBP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{C1SQOBBP}}[3], ${$h{C1SQOBBP}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEQ COMPL/NOT COMPLETE OBC B PRI (CH1) <br>  NCMP CMPL', CAPTION, 'C2SQOBBP ' );\" onmouseout=\"return nd();\"> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEQ COMPL/NOT COMPLETE OBC B PRI (CH1) <br>  NCMP CMPL', CAPTION, 'C2SQOBBP ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>C2SQOBBP </FONT></a></a></TD>\n", ${$h{C2SQOBBP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{C2SQOBBP}}[3], ${$h{C2SQOBBP}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('CPE ENA/DIS (CH1) IOE-B <br>  ENAB DISA', CAPTION, 'ACPEB2X  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>ACPEB2X  </FONT></a></TD>\n", ${$h{ACPEB2X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{ACPEB2X}}[3], ${$h{ACPEB2X}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IOE STATUS NORMAL OR SAFE MODE <br>  SAFE NORM', CAPTION, 'AIOESWD4 ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AIOESWD4 </FONT></a></TD>\n", ${$h{AIOESWD4}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AIOESWD4}}[3], ${$h{AIOESWD4}}[1];

printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>CCDM</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FORMAT SELECTED <br>  FMT3 ERR7 FMT6 ERR8 FMT4 FMT2 FMT1 FMT5', CAPTION, 'CTUFMTSL ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CTUFMTSL </FONT></a></TD>\n", ${$h{CTUFMTSL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CTUFMTSL}}[3], ${$h{CTUFMTSL}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('ONLINE OBC HEARTBEAT <br>  0 1', CAPTION, 'CONLHTBT ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CONLHTBT </FONT></a></TD>\n", ${$h{CONLHTBT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CONLHTBT}}[3], ${$h{CONLHTBT}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('OFF-LINE OBC HEARTBEAT <br>  0 1', CAPTION, 'COFLHTBT ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>COFLHTBT </FONT></a></TD>\n", ${$h{COFLHTBT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{COFLHTBT}}[3], ${$h{COFLHTBT}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IU OBC-A ONLINE/OFFLINE <br>  ONLN OFLN', CAPTION, 'CIUCALIN ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CIUCALIN </FONT></a></TD>\n", ${$h{CIUCALIN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CIUCALIN}}[3], ${$h{CIUCALIN}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IU OBC-B ONLINE/OFFLINE <br>  ONLN OFLN', CAPTION, 'CIUCBLIN ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CIUCBLIN </FONT></a></TD>\n", ${$h{CIUCBLIN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CIUCBLIN}}[3], ${$h{CIUCBLIN}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IU-A OBC-A RUN/HALT <br>  HALT RUN', CAPTION, 'CIUACARH ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CIUACARH </FONT></a></TD>\n", ${$h{CIUACARH}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CIUACARH}}[3], ${$h{CIUACARH}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IU-A OBC-B RUN/HALT <br>  RUN HALT', CAPTION, 'CIUACBRH ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CIUACBRH </FONT></a></TD>\n", ${$h{CIUACBRH}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CIUACBRH}}[3], ${$h{CIUACBRH}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IU-A OBC-A RUN/HALT <br>  HALT RUN', CAPTION, 'CIUACARH ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CIUACARH </FONT></a></TD>\n", ${$h{CIUACARH}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CIUACBRH}}[3], ${$h{CIUACBRH}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IU-A ON/OFF <br>  OFF ON', CAPTION, 'CIUA     ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CIUA     </FONT></a></TD>\n", ${$h{CIUA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CIUA}}[3], ${$h{CIUA}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IU-B ON/OFF <br>  OFF ON', CAPTION, 'CIUB     ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CIUB     </FONT></a></TD>\n", ${$h{CIUB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CIUB}}[3], ${$h{CIUB}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('CTU TELEMETRY PROC ON/OFF (P) <br>  OFF ON', CAPTION, 'CTUTMPPR ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CTUTMPPR </FONT></a></TD>\n", ${$h{CTUTMPPR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CTUTMPPR}}[3], ${$h{CTUTMPPR}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('CTU TELEMETRY PROC ON/OFF (R) <br>  ON OFF', CAPTION, 'CTUTMPRD ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CTUTMPRD </FONT></a></TD>\n", ${$h{CTUTMPRD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CTUTMPRD}}[3], ${$h{CTUTMPRD}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RCTU-EP TLM PROC A ON/OFF (OH) <br>  OFF ON', CAPTION, 'CEPTLMA  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CEPTLMA  </FONT></a></TD>\n", ${$h{CEPTLMA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CEPTLMA}}[3], ${$h{CEPTLMA}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RCTU-EP TLM PROC B ON/OFF (OH) <br>  OFF ON', CAPTION, 'CEPTLMB  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CEPTLMB  </FONT></a></TD>\n", ${$h{CEPTLMB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CEPTLMB}}[3], ${$h{CEPTLMB}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RCTU-PC TLM PROC A ON/OFF (OH) <br>  OFF ON', CAPTION, 'CPCTLMA  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CPCTLMA  </FONT></a></TD>\n", ${$h{CPCTLMA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CPCTLMA}}[3], ${$h{CPCTLMA}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RCTU-PC TLM PROC B ON/OFF (OH) <br>  ON OFF', CAPTION, 'CPCTLMB  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CPCTLMB  </FONT></a></TD>\n", ${$h{CPCTLMB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CPCTLMB}}[3], ${$h{CPCTLMB}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RCTU-SI TLM PROC A ON/OFF (OH) <br>  OFF ON', CAPTION, 'CSITLMA  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CSITLMA  </FONT></a></TD>\n", ${$h{CSITLMA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CSITLMA}}[3], ${$h{CSITLMA}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RCTU-SI TLM PROC B ON/OFF (OH) <br>  OFF ON', CAPTION, 'CSITLMB  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CSITLMB  </FONT></a></TD>\n", ${$h{CSITLMB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CSITLMB}}[3], ${$h{CSITLMB}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RCTU-TS TLM PROC A ON/OFF (OH) <br>  OFF ON', CAPTION, 'CTSTLMA  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CTSTLMA  </FONT></a></TD>\n", ${$h{CTSTLMA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CTSTLMA}}[3], ${$h{CTSTLMA}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RCTU-TS TLM PROC B ON/OFF (OH) <br>  ON OFF', CAPTION, 'CTSTLMB  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CTSTLMB  </FONT></a></TD>\n", ${$h{CTSTLMB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{CTSTLMB}}[3], ${$h{CTSTLMB}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('NO. OF NON-FATAL ERRORS LOGGED BY FLIGHT S/W <br><font color=#FFFF00>(-100.0) 7.0 </font><br><font color=#FF0000>(-1000.0) 7.0</font>', CAPTION, 'COERRCN  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>COERRCN  </FONT></a></TD>\n", ${$h{COERRCN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%2.0f </FONT></TD>\n", ${$h{COERRCN}}[3], ${$h{COERRCN}}[1];
printf SF "</TABLE>\n";

printf SF "<TD><TABLE BORDER=0><TR><TD><FONT SIZE=2>\&nbsp</TR></TABLE>\n";

printf SF "<TD><TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>EPS</FONT></TR>\n";
#printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('LOAD BUS CURRENT (HIGH RANGE) AMP<br><font color=#FFFF00>(3.71) 48.46 </font><br><font color=#FF0000>(3.41) 48.46</font>', CAPTION, 'ELBI     ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>ELBI     </FONT></a></TD>\n", ${$h{ELBI}}[3];
#printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%5.2f </FONT></TD>\n", ${$h{ELBI}}[3], ${$h{ELBI}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('LOAD BUS VOLTAGE V<br><font color=#FFFF00>(26.0) 32.0 </font><br><font color=#FF0000>(24.5) 32.0</font>', CAPTION, 'ELBV     ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>ELBV     </FONT></a></TD>\n", ${$h{ELBV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%5.2f </FONT></TD>\n", ${$h{ELBV}}[3], ${$h{ELBV}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib (' <br>limits', CAPTION, 'POWER    ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>POWER    </FONT></a></TD>\n", ${$h{POWER}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%5.2f </FONT></TD>\n", ${$h{POWER}}[3], ${$h{POWER}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('LOAD BUS CURRENT RANGE -- ELDBCRNG <br>  HI LOW', CAPTION, 'ELDBCRNG ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>ELDBCRNG </FONT></a></TD>\n", ${$h{ELDBCRNG}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{ELDBCRNG}}[3], ${$h{ELDBCRNG}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('LOAD BUS CURRENT (LOW RANGE) AMP<br><font color=#FFFF00>(16) 50 </font><br><font color=#FF0000>(13.0) 50</font>', CAPTION, 'ELBI_LOW ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>ELBI_LOW </FONT></a></TD>\n", ${$h{ELBI_LOW}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%5.2f </FONT></TD>\n", ${$h{ELBI_LOW}}[3], ${$h{ELBI_LOW}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('EPS STATE <br>  STG1 ER10 ER11 ER12 ER13 ER15 ERR9 ER14 ERR7 STG2 STBY EXIT ECLP ENTR SUN ERR8', CAPTION, 'EPSTATE  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EPSTATE  </FONT></a></TD>\n", ${$h{EPSTATE}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{EPSTATE}}[3], ${$h{EPSTATE}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SUN PRESENCE FLAG <br>  SUN NSUN', CAPTION, 'AOSUNPRS ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOSUNPRS </FONT></a></TD>\n", ${$h{AOSUNPRS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOSUNPRS}}[3], ${$h{AOSUNPRS}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SOLAR ARRAY ILLUMINATION FLAG <br>  DARK ILLM', CAPTION, 'AOSAILLM ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOSAILLM </FONT></a></TD>\n", ${$h{AOSAILLM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOSAILLM}}[3], ${$h{AOSAILLM}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('S/A -Y CURRENT AMP<br><font color=#FFFF00>(1.86) 24.23 </font><br><font color=#FF0000>(1.7) 24.23</font>', CAPTION, 'ESAMYI   ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>ESAMYI   </FONT></a></TD>\n", ${$h{ESAMYI}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%5.3f </FONT></TD>\n", ${$h{ESAMYI}}[3], ${$h{ESAMYI}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('S/A +Y CURRENT AMP<br><font color=#FFFF00>(7.86) 24.23 </font><br><font color=#FF0000>(1.7) 24.23</font>', CAPTION, 'ESAPYI   ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>ESAPYI   </FONT></a></TD>\n", ${$h{ESAPYI}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%5.3f </FONT></TD>\n", ${$h{ESAPYI}}[3], ${$h{ESAPYI}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 1 K1 STATUS <br>  OPEN CLOS', CAPTION, 'EB1K1    ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB1K1    </FONT></a></TD>\n", ${$h{EB1K1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{EB1K1}}[3], ${$h{EB1K1}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 1 K2 STATUS <br>  OPEN CLOS', CAPTION, 'EB1K2    ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB1K2    </FONT></a></TD>\n", ${$h{EB1K2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{EB1K2}}[3], ${$h{EB1K2}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 2 K1 STATUS <br>  OPEN CLOS', CAPTION, 'EB2K1    ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB2K1    </FONT></a></TD>\n", ${$h{EB2K1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{EB2K1}}[3], ${$h{EB2K1}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 2 K2 STATUS <br>  OPEN CLOS', CAPTION, 'EB2K2    ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB2K2    </FONT></a></TD>\n", ${$h{EB2K2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{EB2K2}}[3], ${$h{EB2K2}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 3 K1 STATUS <br>  OPEN CLOS', CAPTION, 'EB3K1    ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB3K1    </FONT></a></TD>\n", ${$h{EB3K1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{EB3K1}}[3], ${$h{EB3K1}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 3 K2 STATUS <br>  OPEN CLOS', CAPTION, 'EB3K2    ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB3K2    </FONT></a></TD>\n", ${$h{EB3K2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{EB3K2}}[3], ${$h{EB3K2}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 1 K6/K7 UV PROT <br>  DISA ENAB', CAPTION, 'EB1UV    ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB1UV    </FONT></a></TD>\n", ${$h{EB1UV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{EB1UV}}[3], ${$h{EB1UV}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 2 K6/K7 UV PROT <br>  ENAB DISA', CAPTION, 'EB2UV    ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB2UV    </FONT></a></TD>\n", ${$h{EB2UV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{EB2UV}}[3], ${$h{EB2UV}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('BATT 3 K6/K7 UV PROT <br>  ENAB DISA', CAPTION, 'EB3UV    ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>EB3UV    </FONT></a></TD>\n", ${$h{EB3UV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{EB3UV}}[3], ${$h{EB3UV}}[1];

printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT></TR>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>THERMAL</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('THERMAL CONTROL PROCESS ENABLED/DISABLED <br>  DISA ENAB', CAPTION, '4OTCPEN     ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4OTCPEN     </FONT></a></TD>\n", ${$h{"4OTCPEN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{"4OTCPEN"}}[3], ${$h{"4OTCPEN"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('OBC ACTIVE CONTROL OF OBA HEATERS <br>  DISA ENAB', CAPTION, '4OACOBAH    ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4OACOBAH    </FONT></a></TD>\n", ${$h{"4OACOBAH"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{"4OACOBAH"}}[3], ${$h{"4OACOBAH"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('OBC ACTIVE CONTROL OF HRMA HEATERS <br>  ENAB DISA', CAPTION, '4OACHRMH    ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4OACHRMH    </FONT></a></TD>\n", ${$h{"4OACHRMH"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{"4OACHRMH"}}[3], ${$h{"4OACHRMH"}}[1];
printf SF "<TR><TD><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "</TABLE>\n";

printf SF "<TD><TABLE BORDER=0><TR><TD><FONT SIZE=2>\&nbsp</TR></TABLE>\n";

printf SF "<TD><TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>PCAD</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib (' <br>limits', CAPTION, 'AOATTER1_DEG ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOATTER1_DEG </FONT></a></TD>\n", ${$h{AOATTER1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%8.6f </FONT></TD>\n", ${$h{AOATTER1}}[3], ${$h{AOATTER1}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib (' <br>limits', CAPTION, 'AOATTER2_DEG ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOATTER2_DEG </FONT></a></TD>\n", ${$h{AOATTER2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%8.6f </FONT></TD>\n", ${$h{AOATTER2}}[3], ${$h{AOATTER2}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib (' <br>limits', CAPTION, 'AOATTER3_DEG ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOATTER3_DEG </FONT></a></TD>\n", ${$h{AOATTER3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%8.6f </FONT></TD>\n", ${$h{AOATTER3}}[3], ${$h{AOATTER3}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib (' <br>limits', CAPTION, 'AORATE1_DEG/SEC  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AORATE1_DEG/SEC  </FONT></a></TD>\n", ${$h{AORATE1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%8.6f </FONT></TD>\n", ${$h{AORATE1}}[3], ${$h{AORATE1}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib (' <br>limits', CAPTION, 'AORATE2_DEG/SEC  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AORATE2_DEG/SEC  </FONT></a></TD>\n", ${$h{AORATE2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%8.6f </FONT></TD>\n", ${$h{AORATE2}}[3], ${$h{AORATE2}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib (' <br>limits', CAPTION, 'AORATE3_DEG/SEC  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AORATE3_DEG/SEC  </FONT></a></TD>\n", ${$h{AORATE3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%8.6f </FONT></TD>\n", ${$h{AORATE3}}[3], ${$h{AORATE3}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib (' <br>limits', CAPTION, 'AORWSPD1_RPM ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AORWSPD1_RPM </FONT></a></TD>\n", ${$h{AORWSPD1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%9.3f </FONT></TD>\n", ${$h{AORWSPD1}}[3], ${$h{AORWSPD1}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib (' <br>limits', CAPTION, 'AORWSPD2_RPM ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AORWSPD2_RPM </FONT></a></TD>\n", ${$h{AORWSPD2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%9.3f </FONT></TD>\n", ${$h{AORWSPD2}}[3], ${$h{AORWSPD2}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib (' <br>limits', CAPTION, 'AORWSPD3_RPM ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AORWSPD3_RPM </FONT></a></TD>\n", ${$h{AORWSPD3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%9.3f </FONT></TD>\n", ${$h{AORWSPD3}}[3], ${$h{AORWSPD3}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib (' <br>limits', CAPTION, 'AORWSPD4_RPM ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AORWSPD4_RPM </FONT></a></TD>\n", ${$h{AORWSPD4}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%9.3f </FONT></TD>\n", ${$h{AORWSPD4}}[3], ${$h{AORWSPD4}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib (' <br>limits', CAPTION, 'AORWSPD5_RPM ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AORWSPD5_RPM </FONT></a></TD>\n", ${$h{AORWSPD5}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%9.3f </FONT></TD>\n", ${$h{AORWSPD5}}[3], ${$h{AORWSPD5}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib (' <br>limits', CAPTION, 'AORWSPD6_RPM ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AORWSPD6_RPM </FONT></a></TD>\n", ${$h{AORWSPD6}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%9.3f </FONT></TD>\n", ${$h{AORWSPD6}}[3], ${$h{AORWSPD6}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PCAD MODE <br>  STBY NULL RMAN PWRF NSUN NPNT NMAN', CAPTION, 'AOPCADMD ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOPCADMD </FONT></a></TD>\n", ${$h{AOPCADMD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOPCADMD}}[3], ${$h{AOPCADMD}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IRU-1 RANGE 1Y <br>  HIGH LOW', CAPTION, 'AIRU1R1Y ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AIRU1R1Y </FONT></a></TD>\n", ${$h{AIRU1R1Y}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AIRU1R1Y}}[3], ${$h{AIRU1R1Y}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IRU-1 RANGE 1X <br>  HIGH LOW', CAPTION, 'AIRU1R1X ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AIRU1R1X </FONT></a></TD>\n", ${$h{AIRU1R1X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AIRU1R1X}}[3], ${$h{AIRU1R1X}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib (' <br>limits', CAPTION, 'MOMENTUM ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>MOMENTUM </FONT></a></TD>\n", ${$h{MOMENTUM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%5.3f </FONT></TD>\n", ${$h{MOMENTUM}}[3], ${$h{MOMENTUM}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('COMMANDED ATTITUDE MONITOR FAULT FLAG <br>  ERR OK', CAPTION, 'AOMANMON ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOMANMON </FONT></a></TD>\n", ${$h{AOMANMON}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOMANMON}}[3], ${$h{AOMANMON}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SUN POSITION CHECK FAULT FLAG <br>  OK ERR', CAPTION, 'AOSUNMON ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOSUNMON </FONT></a></TD>\n", ${$h{AOSUNMON}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOSUNMON}}[3], ${$h{AOSUNMON}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IRU MONITOR FAULT FLAG <br>  OK ERR', CAPTION, 'AOIRUMON ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOIRUMON </FONT></a></TD>\n", ${$h{AOIRUMON}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOIRUMON}}[3], ${$h{AOIRUMON}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('ATTITUDE ERROR AND RATE ERROR MONITOR FAULT FLAG <br>  OK ERR', CAPTION, 'AOATTMON ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOATTMON </FONT></a></TD>\n", ${$h{AOATTMON}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOATTMON}}[3], ${$h{AOATTMON}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('REACTION WHEEL MOMENTUM MONITOR FAULT FLAG 1 <br>  OK ERR', CAPTION, 'AORWMON1 ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AORWMON1 </FONT></a></TD>\n", ${$h{AORWMON1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AORWMON1}}[3], ${$h{AORWMON1}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('REACTION WHEEL MOMENTUM MONITOR FAULT FLAG 2 <br>  OK ERR', CAPTION, 'AORWMON2 ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AORWMON2 </FONT></a></TD>\n", ${$h{AORWMON2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AORWMON2}}[3], ${$h{AORWMON2}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('REACTION WHEEL MOMENTUM MONITOR FAULT FLAG 3 <br>  OK ERR', CAPTION, 'AORWMON3 ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AORWMON3 </FONT></a></TD>\n", ${$h{AORWMON3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AORWMON3}}[3], ${$h{AORWMON3}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('REACTION WHEEL MOMENTUM MONITOR FAULT FLAG 4 <br>  OK ERR', CAPTION, 'AORWMON4 ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AORWMON4 </FONT></a></TD>\n", ${$h{AORWMON4}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AORWMON4}}[3], ${$h{AORWMON4}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('REACTION WHEEL MOMENTUM MONITOR FAULT FLAG 5 <br>  ERR OK', CAPTION, 'AORWMON5 ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AORWMON5 </FONT></a></TD>\n", ${$h{AORWMON5}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AORWMON5}}[3], ${$h{AORWMON5}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('REACTION WHEEL MOMENTUM MONITOR FAULT FLAG 6 <br>  OK ERR', CAPTION, 'AORWMON6 ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AORWMON6 </FONT></a></TD>\n", ${$h{AORWMON6}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AORWMON6}}[3], ${$h{AORWMON6}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SPACECRAFT MOMENTUM MONITOR FAULT FLAG <br>  OK ERR', CAPTION, 'AOMOMMON ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOMOMMON </FONT></a></TD>\n", ${$h{AOMOMMON}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOMOMMON}}[3], ${$h{AOMOMMON}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('REACTION WHEEL UNLOADING MONITOR FAULT FLAG <br>  OK ERR', CAPTION, 'AOULMON  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOULMON  </FONT></a></TD>\n", ${$h{AOULMON}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOULMON}}[3], ${$h{AOULMON}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SOLAR ARRAY POSITION MONITOR FAULT FLAG <br>  OK ERR', CAPTION, 'AOSAPMON ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOSAPMON </FONT></a></TD>\n", ${$h{AOSAPMON}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOSAPMON}}[3], ${$h{AOSAPMON}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SADA OVERTEMPERATURE FAULT FLAG <br>  ERR OK', CAPTION, 'AOSATMON ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOSATMON </FONT></a></TD>\n", ${$h{AOSATMON}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOSATMON}}[3], ${$h{AOSATMON}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('LAE DOME TEMPERATURE CHECK FAULT FLAG', CAPTION, 'AOLAEMON ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOLAEMON </FONT></a></TD>\n", ${$h{AOLAEMON}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOLAEMON}}[3], ${$h{AOLAEMON}}[1];
printf SF "<TR><TD><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "</TABLE>\n";

printf SF "<TD><TABLE BORDER=0><TR><TD><FONT SIZE=2>\&nbsp</FONT></TR></TABLE>\n";

printf SF "<TD><TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>Safing</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('CPE-A HEARTBEAT (TOGGLE) <br>  0 1', CAPTION, 'ACPEAHB  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>ACPEAHB  </FONT></a></TD>\n", ${$h{ACPEAHB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{ACPEAHB}}[3], ${$h{ACPEAHB}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('CPE OPERATION STATE <br>  NORM SAFE', CAPTION, 'AOCPESTL ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOCPESTL </FONT></a></TD>\n", ${$h{AOCPESTL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AOCPESTL}}[3], ${$h{AOCPESTL}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('ERROR COUNT CNTS<br><font color=#FFFF00>(-1) 9225 </font><br><font color=#FF0000>(-2) 9225</font>', CAPTION, 'AOCPESTC ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOCPESTC </FONT></a></TD>\n", ${$h{AOCPESTC}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%6.1f </FONT></TD>\n", ${$h{AOCPESTC}}[3], ${$h{AOCPESTC}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('LAST ERROR CODE <br>limits', CAPTION, 'AOCPESTG ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOCPESTG </FONT></a></TD>\n", ${$h{AOCPESTG}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%2.0f </FONT></TD>\n", ${$h{AOCPESTG}}[3], ${$h{AOCPESTG}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('CPE-A ALT CLK SEL <br>  ALT NORM', CAPTION, 'ACPAALCK ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>ACPAALCK </FONT></a></TD>\n", ${$h{ACPAALCK}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{ACPAALCK}}[3], ${$h{ACPAALCK}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('CPE-A CHECK SUM <br>  OK FAIL', CAPTION, 'ACPACKSM ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>ACPACKSM </FONT></a></TD>\n", ${$h{ACPACKSM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{ACPACKSM}}[3], ${$h{ACPACKSM}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('OFF-LINE OBC CALCULATED CHECKSUM <br><font color=#FFFF00>(-1331.0) -1329.0 </font><br><font color=#FF0000>(-1332) -1329.0</font>', CAPTION, 'COFLCXSM ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>COFLCXSM </FONT></a></TD>\n", ${$h{COFLCXSM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{COFLCXSM}}[3], ${$h{COFLCXSM}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FSSA-A (PWR LOSS RECOVERY SETUP) SECONDARY FLAG CPE-A <br>  BON AON', CAPTION, 'AFSSAFLG ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AFSSAFLG </FONT></a></TD>\n", ${$h{AFSSAFLG}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AFSSAFLG}}[3], ${$h{AFSSAFLG}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FSSA-B (PWR LOSS RECOVERY SETUP) SECONDARY FLAG CPE-B <br>  AON BON', CAPTION, 'AFSSBFLG ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AFSSBFLG </FONT></a></TD>\n", ${$h{AFSSBFLG}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AFSSBFLG}}[3], ${$h{AFSSBFLG}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('CONTROL MODE (PWR LOSS RECOV SETUP) SECONDARY FLAG CPE-A <br>  RWA RCS', CAPTION, 'ARCSFLGA ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>ARCSFLGA </FONT></a></TD>\n", ${$h{ARCSFLGA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{ARCSFLGA}}[3], ${$h{ARCSFLGA}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('CONTROL MODE (PWR LOSS RECOV SETUP) SECONDARY FLAG CPE-B <br>  RCS RWA', CAPTION, 'ARCSFLGB ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>ARCSFLGB </FONT></a></TD>\n", ${$h{ARCSFLGB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{ARCSFLGB}}[3], ${$h{ARCSFLGB}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEQ A PRESEL IU A/IU B (CH0) <br>  IUB IUA', CAPTION, 'C1SQAPIU ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>C1SQAPIU </FONT></a></TD>\n", ${$h{C1SQAPIU}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{C1SQAPIU}}[3], ${$h{C1SQAPIU}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEQ A PRESEL IU A/IU B (CH1) <br>  IUB IUA', CAPTION, 'C2SQAPIU ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>C2SQAPIU </FONT></a></TD>\n", ${$h{C2SQAPIU}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{C2SQAPIU}}[3], ${$h{C2SQAPIU}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEQ A PRESEL OBC A/OBC B (CH0) <br>  OBCB OBCA', CAPTION, 'C1SQAPO  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>C1SQAPO  </FONT></a></TD>\n", ${$h{C1SQAPO}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{C1SQAPO}}[3], ${$h{C1SQAPO}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEQ A PRESEL OBC A/OBC B (CH1) <br>  OBCB OBCA', CAPTION, 'C2SQAPO  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>C2SQAPO  </FONT></a></TD>\n", ${$h{C2SQAPO}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{C2SQAPO}}[3], ${$h{C2SQAPO}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEQ A PRESEL PASS 1/PASS 2 (CH0) <br>  PAS1 PAS2', CAPTION, 'C1SQAPPP ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>C1SQAPPP </FONT></a></TD>\n", ${$h{C1SQAPPP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{C1SQAPPP}}[3], ${$h{C1SQAPPP}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEQ A PRESEL PASS 1/PASS 2 (CH1) <br>  PAS1 PAS2', CAPTION, 'C2SQAPPP ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>C2SQAPPP </FONT></a></TD>\n", ${$h{C2SQAPPP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{C2SQAPPP}}[3], ${$h{C2SQAPPP}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEQ COMPL/NOT COMPLETE OBC B PRI (CH0) <br>  NCMP CMPL', CAPTION, 'C1SQOBBP ' );\" onmouseout=\"return nd();\"> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEQ COMPL/NOT COMPLETE OBC B PRI (CH0) <br>  NCMP CMPL', CAPTION, 'C1SQOBBP ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>C1SQOBBP </FONT></a></a></TD>\n", ${$h{C1SQOBBP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{C1SQOBBP}}[3], ${$h{C1SQOBBP}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEQ COMPL/NOT COMPLETE OBC B PRI (CH1) <br>  NCMP CMPL', CAPTION, 'C2SQOBBP ' );\" onmouseout=\"return nd();\"> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEQ COMPL/NOT COMPLETE OBC B PRI (CH1) <br>  NCMP CMPL', CAPTION, 'C2SQOBBP ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>C2SQOBBP </FONT></a></a></TD>\n", ${$h{C2SQOBBP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{C2SQOBBP}}[3], ${$h{C2SQOBBP}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEQ A ENA/DIS (CH0) <br>  DISA ENAB', CAPTION, 'C1SQAX   ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>C1SQAX   </FONT></a></TD>\n", ${$h{C1SQAX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{C1SQAX}}[3], ${$h{C1SQAX}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEQ A ENA/DIS (CH1) <br>  DISA ENAB', CAPTION, 'C2SQAX   ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>C2SQAX   </FONT></a></TD>\n", ${$h{C2SQAX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{C2SQAX}}[3], ${$h{C2SQAX}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEQ A PRESEL CTU A/CTU B (CH0) <br>  CTUB CTUA', CAPTION, 'C1SQAPCT ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>C1SQAPCT </FONT></a></TD>\n", ${$h{C1SQAPCT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{C1SQAPCT}}[3], ${$h{C1SQAPCT}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEQ A PRESEL CTU A/CTU B (CH1) <br>  CTUB CTUA', CAPTION, 'C2SQAPCT ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>C2SQAPCT </FONT></a></TD>\n", ${$h{C2SQAPCT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{C2SQAPCT}}[3], ${$h{C2SQAPCT}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IRU GYRO 1 SEL (PWR LOSS RECOV SETUP) CPE-A <br>  NO YES', CAPTION, 'AG1SELA  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AG1SELA  </FONT></a></TD>\n", ${$h{AG1SELA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AG1SELA}}[3], ${$h{AG1SELA}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IRU GYRO 1 SEL (PWR LOSS RECOV SETUP) CPE-B <br>  NO YES', CAPTION, 'AG1SELB  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AG1SELB  </FONT></a></TD>\n", ${$h{AG1SELB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AG1SELB}}[3], ${$h{AG1SELB}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IRU GYRO 2 SEL (PWR LOSS RECOV SETUP) CPE-A <br>  NO YES', CAPTION, 'AG2SELA  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AG2SELA  </FONT></a></TD>\n", ${$h{AG2SELA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AG2SELA}}[3], ${$h{AG2SELA}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IRU GYRO 2 SEL (PWR LOSS RECOV SETUP) CPE-B <br>  NO YES', CAPTION, 'AG2SELB  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AG2SELB  </FONT></a></TD>\n", ${$h{AG2SELB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AG2SELB}}[3], ${$h{AG2SELB}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IRU GYRO 3 SEL (PWR LOSS RECOV SETUP) CPE-A <br>  YES NO', CAPTION, 'AG3SELA  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AG3SELA  </FONT></a></TD>\n", ${$h{AG3SELA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AG3SELA}}[3], ${$h{AG3SELA}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IRU GYRO 3 SEL (PWR LOSS RECOV SETUP) CPE-B <br>  YES NO', CAPTION, 'AG3SELB  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AG3SELB  </FONT></a></TD>\n", ${$h{AG3SELB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AG3SELB}}[3], ${$h{AG3SELB}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IRU GYRO 4 SEL (PWR LOSS RECOV SETUP) CPE-A <br>  NO YES', CAPTION, 'AG4SELA  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AG4SELA  </FONT></a></TD>\n", ${$h{AG4SELA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AG4SELA}}[3], ${$h{AG4SELA}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IRU GYRO 4 SEL (PWR LOSS RECOV SETUP) CPE-B <br>  NO YES', CAPTION, 'AG4SELB  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AG4SELB  </FONT></a></TD>\n", ${$h{AG4SELB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{AG4SELB}}[3], ${$h{AG4SELB}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SCS 120 STATE', CAPTION, 'SCS120S  ' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>SCS120S  </FONT></a></TD>\n", ${$h{COSCS120S}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s </FONT></TD>\n", ${$h{COSCS120S}}[3], ${$h{COSCS120S}}[1];
printf SF "<TR><TD><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "</TABLE>\n";
printf SF "</TABLE>\n";
printf SF "<BR>\n";
close SF;

print_links("$outfile");
open (SF,">>$outfile");
print SF "</BODY></HTML>\n";
close SF;
}
1;
