sub soh_format {
  $outfile = shift @_;
  %h = @_;
  print_head("$outfile","Safe Mode Reponse", %h);

open (SF, ">>$outfile");

printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=2><FONT SIZE=4>Verify Safe Mode Entry</FONT>\n";
printf SF "<TD ALIGN=LEFT COLSPAN=2><FONT SIZE=4>Configure for CPE Telemetry</FONT><\/TR>\n";

printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUCALIN</FONT></TD>\n", ${$h{"CIUCALIN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CIUCALIN"}}[3], ${$h{"CIUCALIN"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CCSDSTMF</FONT></TD>\n", ${$h{"CCSDSTMF"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CCSDSTMF"}}[3], ${$h{"CCSDSTMF"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUCBLIN</FONT></TD>\n", ${$h{"CIUCBLIN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CIUCBLIN"}}[3], ${$h{"CIUCBLIN"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQOBBP</FONT></TD>\n", ${$h{"C1SQOBBP"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"C1SQOBBP"}}[3], ${$h{"C1SQOBBP"}}[1];

printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQOBBP</FONT></TD>\n", ${$h{"C2SQOBBP"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"C2SQOBBP"}}[3], ${$h{"C2SQOBBP"}}[1];
printf SF "<TD ALIGN=CENTER COLSPAN=4><FONT SIZE=4>Verify Chandra is Safe in Safe Mode</FONT><\/TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUA</FONT></TD>\n", ${$h{"CIUA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CIUA"}}[3], ${$h{"CIUA"}}[1];
printf SF "<TD ALIGN=LEFT COLSPAN=2><FONT SIZE=4>CPE in Control</FONT><\/TR>\n";
printf SF "<TD ALIGN=LEFT COLSPAN=2><FONT SIZE=4>Safe PCAD</FONT><\/TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUB</FONT></TD>\n", ${$h{"CIUB"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CIUB"}}[3], ${$h{"CIUB"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ACPEAHB</FONT></TD>\n", ${$h{"ACPEAHB"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"ACPEAHB"}}[3], ${$h{"ACPEAHB"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>6RATE1</FONT></TD>\n", ${$h{"6RATE1"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"6RATE1"}}[3], ${$h{"6RATE1"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUTMPPR</FONT></TD>\n", ${$h{"CTUTMPPR"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CTUTMPPR"}}[3], ${$h{"CTUTMPPR"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>61PSTS02</FONT></TD>\n", ${$h{"61PSTS02"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"61PSTS02"}}[3], ${$h{"61PSTS02"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>6RATE2</FONT></TD>\n", ${$h{"6RATE2"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"6RATE2"}}[3], ${$h{"6RATE2"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUTMPRD</FONT></TD>\n", ${$h{"CTUTMPRD"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CTUTMPRD"}}[3], ${$h{"CTUTMPRD"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>64PSTS01</FONT></TD>\n", ${$h{"64PSTS01"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"64PSTS01"}}[3], ${$h{"64PSTS01"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>6RATE3</FONT></TD>\n", ${$h{"6RATE3"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"6RATE3"}}[3], ${$h{"6RATE3"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>PVDETMA1</FONT></TD>\n", ${$h{"PVDETMA1"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"PVDETMA1"}}[3], ${$h{"PVDETMA1"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIOESWD4</FONT></TD>\n", ${$h{"AIOESWD4"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AIOESWD4"}}[3], ${$h{"AIOESWD4"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>6SUNACA3</FONT></TD>\n", ${$h{"6SUNACA3"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"6SUNACA3"}}[3], ${$h{"6SUNACA3"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>PVDETMB1</FONT></TD>\n", ${$h{"PVDETMB1"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"PVDETMB1"}}[3], ${$h{"PVDETMB1"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ACPEA1X</FONT></TD>\n", ${$h{"ACPEA1X"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"ACPEA1X"}}[3], ${$h{"ACPEA1X"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>6SAEST1</FONT></TD>\n", ${$h{"6SAEST1"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"6SAEST1"}}[3], ${$h{"6SAEST1"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQAPPP</FONT></TD>\n", ${$h{"C1SQAPPP"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"C1SQAPPP"}}[3], ${$h{"C1SQAPPP"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ACPEB1X</FONT></TD>\n", ${$h{"ACPEB1X"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"ACPEB1X"}}[3], ${$h{"ACPEB1X"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>6SAEST2</FONT></TD>\n", ${$h{"6SAEST2"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"6SAEST2"}}[3], ${$h{"6SAEST2"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQAPPP</FONT></TD>\n", ${$h{"C2SQAPPP"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"C2SQAPPP"}}[3], ${$h{"C2SQAPPP"}}[1];

printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=4><FONT SIZE=4>Verify Successful Backup OBC Actions</FONT><\/TR>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=2><FONT SIZE=4>Backup OBC State</FONT><\/TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUCBLIN</FONT></TD>\n", ${$h{"CIUCBLIN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CIUCBLIN"}}[3], ${$h{"CIUCBLIN"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUBCBRH</FONT></TD>\n", ${$h{"CIUBCBRH"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CIUBCBRH"}}[3], ${$h{"CIUBCBRH"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CONLOFP</FONT></TD>\n", ${$h{"CONLOFP"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CONLOFP"}}[3], ${$h{"CONLOFP"}}[1];

printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=4><FONT SIZE=4>SCS #31 Actions</FONT>\n";
printf SF "<TD ALIGN=LEFT COLSPAN=6><FONT SIZE=4>Science Instrument Safing (SCS #107)</FONT><\/TR>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=2><FONT SIZE=4>Bus & RCTU Reconfig</FONT>\n";
printf SF "<TD ALIGN=LEFT COLSPAN=2><FONT SIZE=4>PCAD Reconfig</FONT>\n";
printf SF "<TD ALIGN=LEFT COLSPAN=6><FONT SIZE=4>FSW</FONT><\/TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CCTXA</FONT></TD>\n", ${$h{"CCTXA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CCTXA"}}[3], ${$h{"CCTXA"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AVDEAX</FONT></TD>\n", ${$h{"AVDEAX"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AVDEAX"}}[3], ${$h{"AVDEAX"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CORADMEN</FONT></TD>\n", ${$h{"CORADMEN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CORADMEN"}}[3], ${$h{"CORADMEN"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS169S</FONT></TD>\n", ${$h{"COSCS169S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS169S"}}[3], ${$h{"COSCS169S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS213S</FONT></TD>\n", ${$h{"COSCS213S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS213S"}}[3], ${$h{"COSCS213S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CCTXB</FONT></TD>\n", ${$h{"CCTXB"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CCTXB"}}[3], ${$h{"CCTXB"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>PF1MV1C1</FONT></TD>\n", ${$h{"PF1MV1C1"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"PF1MV1C1"}}[3], ${$h{"PF1MV1C1"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS107S</FONT></TD>\n", ${$h{"COSCS107S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS107S"}}[3], ${$h{"COSCS107S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS170S</FONT></TD>\n", ${$h{"COSCS170S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS170S"}}[3], ${$h{"COSCS170S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS214S</FONT></TD>\n", ${$h{"COSCS214S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS214S"}}[3], ${$h{"COSCS214S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUEPA</FONT></TD>\n", ${$h{"CTUEPA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CTUEPA"}}[3], ${$h{"CTUEPA"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUTMRYB</FONT></TD>\n", ${$h{"CTUTMRYB"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CTUTMRYB"}}[3], ${$h{"CTUTMRYB"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS171S</FONT></TD>\n", ${$h{"COSCS171S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS171S"}}[3], ${$h{"COSCS171S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS215S</FONT></TD>\n", ${$h{"COSCS215S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS215S"}}[3], ${$h{"COSCS215S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUEPB</FONT></TD>\n", ${$h{"CTUEPB"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CTUEPB"}}[3], ${$h{"CTUEPB"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1G1I</FONT></TD>\n", ${$h{"AIRU1G1I"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"AIRU1G1I"}}[3], ${$h{"AIRU1G1I"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS128S</FONT></TD>\n", ${$h{"COSCS128S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS128S"}}[3], ${$h{"COSCS128S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS172S</FONT></TD>\n", ${$h{"COSCS172S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS172S"}}[3], ${$h{"COSCS172S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS216S</FONT></TD>\n", ${$h{"COSCS216S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS216S"}}[3], ${$h{"COSCS216S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUTMRQB</FONT></TD>\n", ${$h{"CTUTMRQB"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CTUTMRQB"}}[3], ${$h{"CTUTMRQB"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AG1SELA</FONT></TD>\n", ${$h{"AG1SELA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AG1SELA"}}[3], ${$h{"AG1SELA"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS129S</FONT></TD>\n", ${$h{"COSCS129S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS129S"}}[3], ${$h{"COSCS129S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS173S</FONT></TD>\n", ${$h{"COSCS173S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS173S"}}[3], ${$h{"COSCS173S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS217S</FONT></TD>\n", ${$h{"COSCS217S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS217S"}}[3], ${$h{"COSCS217S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUTMRYB</FONT></TD>\n", ${$h{"CTUTMRYB"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CTUTMRYB"}}[3], ${$h{"CTUTMRYB"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1G2I</FONT></TD>\n", ${$h{"AIRU1G2I"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"AIRU1G2I"}}[3], ${$h{"AIRU1G2I"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS130S</FONT></TD>\n", ${$h{"COSCS130S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS130S"}}[3], ${$h{"COSCS130S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS174S</FONT></TD>\n", ${$h{"COSCS174S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS174S"}}[3], ${$h{"COSCS174S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS218S</FONT></TD>\n", ${$h{"COSCS218S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS218S"}}[3], ${$h{"COSCS218S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CEPTLMB</FONT></TD>\n", ${$h{"CEPTLMB"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CEPTLMB"}}[3], ${$h{"CEPTLMB"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AG2SELA</FONT></TD>\n", ${$h{"AG2SELA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AG2SELA"}}[3], ${$h{"AG2SELA"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS131S</FONT></TD>\n", ${$h{"COSCS131S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS131S"}}[3], ${$h{"COSCS131S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS175S</FONT></TD>\n", ${$h{"COSCS175S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS175S"}}[3], ${$h{"COSCS175S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS219S</FONT></TD>\n", ${$h{"COSCS219S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS219S"}}[3], ${$h{"COSCS219S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUPCA</FONT></TD>\n", ${$h{"CTUPCA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CTUPCA"}}[3], ${$h{"CTUPCA"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1</FONT></TD>\n", ${$h{"AIRU1"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AIRU1"}}[3], ${$h{"AIRU1"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS132S</FONT></TD>\n", ${$h{"COSCS132S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS132S"}}[3], ${$h{"COSCS132S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS176S</FONT></TD>\n", ${$h{"COSCS176S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS176S"}}[3], ${$h{"COSCS176S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS220S</FONT></TD>\n", ${$h{"COSCS220S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS220S"}}[3], ${$h{"COSCS220S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUPCB</FONT></TD>\n", ${$h{"CTUPCB"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CTUPCB"}}[3], ${$h{"CTUPCB"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2</FONT></TD>\n", ${$h{"AIRU2"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AIRU2"}}[3], ${$h{"AIRU2"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS133S</FONT></TD>\n", ${$h{"COSCS133S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS133S"}}[3], ${$h{"COSCS133S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS177S</FONT></TD>\n", ${$h{"COSCS177S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS177S"}}[3], ${$h{"COSCS177S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS221S</FONT></TD>\n", ${$h{"COSCS221S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS221S"}}[3], ${$h{"COSCS221S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CPCTLMB</FONT></TD>\n", ${$h{"CPCTLMB"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CPCTLMB"}}[3], ${$h{"CPCTLMB"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2R1X</FONT></TD>\n", ${$h{"AIRU2R1X"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AIRU2R1X"}}[3], ${$h{"AIRU2R1X"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS134S</FONT></TD>\n", ${$h{"COSCS134S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS134S"}}[3], ${$h{"COSCS134S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS178S</FONT></TD>\n", ${$h{"COSCS178S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS178S"}}[3], ${$h{"COSCS178S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS222S</FONT></TD>\n", ${$h{"COSCS222S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS222S"}}[3], ${$h{"COSCS222S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2R2X</FONT></TD>\n", ${$h{"AIRU2R2X"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AIRU2R2X"}}[3], ${$h{"AIRU2R2X"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS135S</FONT></TD>\n", ${$h{"COSCS135S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS135S"}}[3], ${$h{"COSCS135S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS179S</FONT></TD>\n", ${$h{"COSCS179S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS179S"}}[3], ${$h{"COSCS179S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS223S</FONT></TD>\n", ${$h{"COSCS223S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS223S"}}[3], ${$h{"COSCS223S"}}[1];

printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2R1Y</FONT></TD>\n", ${$h{"AIRU2R1Y"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AIRU2R1Y"}}[3], ${$h{"AIRU2R1Y"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS136S</FONT></TD>\n", ${$h{"COSCS136S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS136S"}}[3], ${$h{"COSCS136S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS180S</FONT></TD>\n", ${$h{"COSCS180S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS180S"}}[3], ${$h{"COSCS180S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS224S</FONT></TD>\n", ${$h{"COSCS224S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS224S"}}[3], ${$h{"COSCS224S"}}[1];
printf SF "<TR><TD ALIGN=LEFT COLSPAN=2><FONT SIZE=4>Thermal & EPS Setup</FONT>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2R2Y</FONT></TD>\n", ${$h{"AIRU2R2Y"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AIRU2R2Y"}}[3], ${$h{"AIRU2R2Y"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS137S</FONT></TD>\n", ${$h{"COSCS137S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS137S"}}[3], ${$h{"COSCS137S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS181S</FONT></TD>\n", ${$h{"COSCS181S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS181S"}}[3], ${$h{"COSCS181S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS225S</FONT></TD>\n", ${$h{"COSCS225S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS225S"}}[3], ${$h{"COSCS225S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COTHEMEN</FONT></TD>\n", ${$h{"COTHEMEN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COTHEMEN"}}[3], ${$h{"COTHEMEN"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2G1I</FONT></TD>\n", ${$h{"AIRU2G1I"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"AIRU2G1I"}}[3], ${$h{"AIRU2G1I"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS138S</FONT></TD>\n", ${$h{"COSCS138S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS138S"}}[3], ${$h{"COSCS138S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS182S</FONT></TD>\n", ${$h{"COSCS182S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS182S"}}[3], ${$h{"COSCS182S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS226S</FONT></TD>\n", ${$h{"COSCS226S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS226S"}}[3], ${$h{"COSCS226S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4OACBATH</FONT></TD>\n", ${$h{"4OACBATH"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4OACBATH"}}[3], ${$h{"4OACBATH"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2G2I</FONT></TD>\n", ${$h{"AIRU2G2I"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"AIRU2G2I"}}[3], ${$h{"AIRU2G2I"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS139S</FONT></TD>\n", ${$h{"COSCS139S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS139S"}}[3], ${$h{"COSCS139S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS183S</FONT></TD>\n", ${$h{"COSCS183S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS183S"}}[3], ${$h{"COSCS183S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS227S</FONT></TD>\n", ${$h{"COSCS227S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS227S"}}[3], ${$h{"COSCS227S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4OPPMEN</FONT></TD>\n", ${$h{"4OPPMEN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4OPPMEN"}}[3], ${$h{"4OPPMEN"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AG3SELA</FONT></TD>\n", ${$h{"AG3SELA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AG3SELA"}}[3], ${$h{"AG3SELA"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS140S</FONT></TD>\n", ${$h{"COSCS140S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS140S"}}[3], ${$h{"COSCS140S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS184S</FONT></TD>\n", ${$h{"COSCS184S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS184S"}}[3], ${$h{"COSCS184S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS228S</FONT></TD>\n", ${$h{"COSCS228S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS228S"}}[3], ${$h{"COSCS228S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4OOTGMEF</FONT></TD>\n", ${$h{"4OOTGMEF"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4OOTGMEF"}}[3], ${$h{"4OOTGMEF"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AG4SELA</FONT></TD>\n", ${$h{"AG4SELA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AG4SELA"}}[3], ${$h{"AG4SELA"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS141S</FONT></TD>\n", ${$h{"COSCS141S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS141S"}}[3], ${$h{"COSCS141S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS185S</FONT></TD>\n", ${$h{"COSCS185S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS185S"}}[3], ${$h{"COSCS185S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS229S</FONT></TD>\n", ${$h{"COSCS229S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS229S"}}[3], ${$h{"COSCS229S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4OTCPEN</FONT></TD>\n", ${$h{"4OTCPEN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4OTCPEN"}}[3], ${$h{"4OTCPEN"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AVDEBX</FONT></TD>\n", ${$h{"AVDEBX"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AVDEBX"}}[3], ${$h{"AVDEBX"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS142S</FONT></TD>\n", ${$h{"COSCS142S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS142S"}}[3], ${$h{"COSCS142S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS186S</FONT></TD>\n", ${$h{"COSCS186S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS186S"}}[3], ${$h{"COSCS186S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS230S</FONT></TD>\n", ${$h{"COSCS230S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS230S"}}[3], ${$h{"COSCS230S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4OACHRMH</FONT></TD>\n", ${$h{"4OACHRMH"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4OACHRMH"}}[3], ${$h{"4OACHRMH"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ADEAPWR</FONT></TD>\n", ${$h{"ADEAPWR"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"ADEAPWR"}}[3], ${$h{"ADEAPWR"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS143S</FONT></TD>\n", ${$h{"COSCS143S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS143S"}}[3], ${$h{"COSCS143S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS187S</FONT></TD>\n", ${$h{"COSCS187S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS187S"}}[3], ${$h{"COSCS187S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS231S</FONT></TD>\n", ${$h{"COSCS231S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS231S"}}[3], ${$h{"COSCS231S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4OACOBAH</FONT></TD>\n", ${$h{"4OACOBAH"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4OACOBAH"}}[3], ${$h{"4OACOBAH"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ADEBPWR</FONT></TD>\n", ${$h{"ADEBPWR"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"ADEBPWR"}}[3], ${$h{"ADEBPWR"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS144S</FONT></TD>\n", ${$h{"COSCS144S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS144S"}}[3], ${$h{"COSCS144S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS188S</FONT></TD>\n", ${$h{"COSCS188S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS188S"}}[3], ${$h{"COSCS188S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS232S</FONT></TD>\n", ${$h{"COSCS232S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS232S"}}[3], ${$h{"COSCS232S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4OOTGDAS</FONT></TD>\n", ${$h{"4OOTGDAS"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4OOTGDAS"}}[3], ${$h{"4OOTGDAS"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ASPEAX</FONT></TD>\n", ${$h{"ASPEAX"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"ASPEAX"}}[3], ${$h{"ASPEAX"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS145S</FONT></TD>\n", ${$h{"COSCS145S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS145S"}}[3], ${$h{"COSCS145S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS189S</FONT></TD>\n", ${$h{"COSCS189S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS189S"}}[3], ${$h{"COSCS189S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS233S</FONT></TD>\n", ${$h{"COSCS233S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS233S"}}[3], ${$h{"COSCS233S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COTLRDSF</FONT></TD>\n", ${$h{"COTLRDSF"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COTLRDSF"}}[3], ${$h{"COTLRDSF"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIOEA</FONT></TD>\n", ${$h{"AIOEA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AIOEA"}}[3], ${$h{"AIOEA"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS146S</FONT></TD>\n", ${$h{"COSCS146S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS146S"}}[3], ${$h{"COSCS146S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS190S</FONT></TD>\n", ${$h{"COSCS190S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS190S"}}[3], ${$h{"COSCS190S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS234S</FONT></TD>\n", ${$h{"COSCS234S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS234S"}}[3], ${$h{"COSCS234S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EGCTTEL3</FONT></TD>\n", ${$h{"EGCTTEL3"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"EGCTTEL3"}}[3], ${$h{"EGCTTEL3"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIOEB</FONT></TD>\n", ${$h{"AIOEB"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AIOEB"}}[3], ${$h{"AIOEB"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS147S</FONT></TD>\n", ${$h{"COSCS147S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS147S"}}[3], ${$h{"COSCS147S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS191S</FONT></TD>\n", ${$h{"COSCS191S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS191S"}}[3], ${$h{"COSCS191S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS235S</FONT></TD>\n", ${$h{"COSCS235S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS235S"}}[3], ${$h{"COSCS235S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EGCTTEL1</FONT></TD>\n", ${$h{"EGCTTEL1"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"EGCTTEL1"}}[3], ${$h{"EGCTTEL1"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AFSSAA</FONT></TD>\n", ${$h{"AFSSAA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AFSSAA"}}[3], ${$h{"AFSSAA"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS148S</FONT></TD>\n", ${$h{"COSCS148S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS148S"}}[3], ${$h{"COSCS148S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS192S</FONT></TD>\n", ${$h{"COSCS192S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS192S"}}[3], ${$h{"COSCS192S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS236S</FONT></TD>\n", ${$h{"COSCS236S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS236S"}}[3], ${$h{"COSCS236S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AFSSAB</FONT></TD>\n", ${$h{"AFSSAB"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AFSSAB"}}[3], ${$h{"AFSSAB"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS149S</FONT></TD>\n", ${$h{"COSCS149S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS149S"}}[3], ${$h{"COSCS149S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS193S</FONT></TD>\n", ${$h{"COSCS193S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS193S"}}[3], ${$h{"COSCS193S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS237S</FONT></TD>\n", ${$h{"COSCS237S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS237S"}}[3], ${$h{"COSCS237S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUFMTSL</FONT></TD>\n", ${$h{"CTUFMTSL"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CTUFMTSL"}}[3], ${$h{"CTUFMTSL"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS150S</FONT></TD>\n", ${$h{"COSCS150S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS150S"}}[3], ${$h{"COSCS150S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS194S</FONT></TD>\n", ${$h{"COSCS194S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS194S"}}[3], ${$h{"COSCS194S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS238S</FONT></TD>\n", ${$h{"COSCS238S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS238S"}}[3], ${$h{"COSCS238S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ACPEB1X</FONT></TD>\n", ${$h{"ACPEB1X"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"ACPEB1X"}}[3], ${$h{"ACPEB1X"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS151S</FONT></TD>\n", ${$h{"COSCS151S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS151S"}}[3], ${$h{"COSCS151S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS195S</FONT></TD>\n", ${$h{"COSCS195S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS195S"}}[3], ${$h{"COSCS195S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS239S</FONT></TD>\n", ${$h{"COSCS239S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS239S"}}[3], ${$h{"COSCS239S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ACPEB2X</FONT></TD>\n", ${$h{"ACPEB2X"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"ACPEB2X"}}[3], ${$h{"ACPEB2X"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS152S</FONT></TD>\n", ${$h{"COSCS152S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS152S"}}[3], ${$h{"COSCS152S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS196S</FONT></TD>\n", ${$h{"COSCS196S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS196S"}}[3], ${$h{"COSCS196S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS240S</FONT></TD>\n", ${$h{"COSCS240S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS240S"}}[3], ${$h{"COSCS240S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS153S</FONT></TD>\n", ${$h{"COSCS153S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS153S"}}[3], ${$h{"COSCS153S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS197S</FONT></TD>\n", ${$h{"COSCS197S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS197S"}}[3], ${$h{"COSCS197S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS241S</FONT></TD>\n", ${$h{"COSCS241S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS241S"}}[3], ${$h{"COSCS241S"}}[1];

printf SF "<TR><TD ALIGN=CENTER COLSPAN=4>Verify EIA Sequencer Pass 2 Run<FONT SIZE=4><iFONT>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS154S</FONT></TD>\n", ${$h{"COSCS154S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS154S"}}[3], ${$h{"COSCS154S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS198S</FONT></TD>\n", ${$h{"COSCS198S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS198S"}}[3], ${$h{"COSCS198S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS242S</FONT></TD>\n", ${$h{"COSCS242S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS242S"}}[3], ${$h{"COSCS242S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1R1X</FONT></TD>\n", ${$h{"AIRU1R1X"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AIRU1R1X"}}[3], ${$h{"AIRU1R1X"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ACPEA1X</FONT></TD>\n", ${$h{"ACPEA1X"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"ACPEA1X"}}[3], ${$h{"ACPEA1X"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS155S</FONT></TD>\n", ${$h{"COSCS155S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS155S"}}[3], ${$h{"COSCS155S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS199S</FONT></TD>\n", ${$h{"COSCS199S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS199S"}}[3], ${$h{"COSCS199S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS243S</FONT></TD>\n", ${$h{"COSCS243S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS243S"}}[3], ${$h{"COSCS243S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2R1X</FONT></TD>\n", ${$h{"AIRU2R1X"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AIRU2R1X"}}[3], ${$h{"AIRU2R1X"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ACPEB1X</FONT></TD>\n", ${$h{"ACPEB1X"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"ACPEB1X"}}[3], ${$h{"ACPEB1X"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS156S</FONT></TD>\n", ${$h{"COSCS156S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS156S"}}[3], ${$h{"COSCS156S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS200S</FONT></TD>\n", ${$h{"COSCS200S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS200S"}}[3], ${$h{"COSCS200S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS244S</FONT></TD>\n", ${$h{"COSCS244S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS244S"}}[3], ${$h{"COSCS244S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1R2X</FONT></TD>\n", ${$h{"AIRU1R2X"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AIRU1R2X"}}[3], ${$h{"AIRU1R2X"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQAX</FONT></TD>\n", ${$h{"C1SQAX"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"C1SQAX"}}[3], ${$h{"C1SQAX"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS157S</FONT></TD>\n", ${$h{"COSCS157S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS157S"}}[3], ${$h{"COSCS157S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS201S</FONT></TD>\n", ${$h{"COSCS201S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS201S"}}[3], ${$h{"COSCS201S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS245S</FONT></TD>\n", ${$h{"COSCS245S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS245S"}}[3], ${$h{"COSCS245S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2R2X</FONT></TD>\n", ${$h{"AIRU2R2X"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AIRU2R2X"}}[3], ${$h{"AIRU2R2X"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQAX</FONT></TD>\n", ${$h{"C2SQAX"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"C2SQAX"}}[3], ${$h{"C2SQAX"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS158S</FONT></TD>\n", ${$h{"COSCS158S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS158S"}}[3], ${$h{"COSCS158S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS202S</FONT></TD>\n", ${$h{"COSCS202S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS202S"}}[3], ${$h{"COSCS202S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS246S</FONT></TD>\n", ${$h{"COSCS246S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS246S"}}[3], ${$h{"COSCS246S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1R1Y</FONT></TD>\n", ${$h{"AIRU1R1Y"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AIRU1R1Y"}}[3], ${$h{"AIRU1R1Y"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQBX</FONT></TD>\n", ${$h{"C1SQBX"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"C1SQBX"}}[3], ${$h{"C1SQBX"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS159S</FONT></TD>\n", ${$h{"COSCS159S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS159S"}}[3], ${$h{"COSCS159S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS203S</FONT></TD>\n", ${$h{"COSCS203S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS203S"}}[3], ${$h{"COSCS203S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS247S</FONT></TD>\n", ${$h{"COSCS247S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS247S"}}[3], ${$h{"COSCS247S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2R1Y</FONT></TD>\n", ${$h{"AIRU2R1Y"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AIRU2R1Y"}}[3], ${$h{"AIRU2R1Y"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQBX</FONT></TD>\n", ${$h{"C2SQBX"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"C2SQBX"}}[3], ${$h{"C2SQBX"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS160S</FONT></TD>\n", ${$h{"COSCS160S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS160S"}}[3], ${$h{"COSCS160S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS204S</FONT></TD>\n", ${$h{"COSCS204S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS204S"}}[3], ${$h{"COSCS204S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS248S</FONT></TD>\n", ${$h{"COSCS248S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS248S"}}[3], ${$h{"COSCS248S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1R2Y</FONT></TD>\n", ${$h{"AIRU1R2Y"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AIRU1R2Y"}}[3], ${$h{"AIRU1R2Y"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS161S</FONT></TD>\n", ${$h{"COSCS161S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS161S"}}[3], ${$h{"COSCS161S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS205S</FONT></TD>\n", ${$h{"COSCS205S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS205S"}}[3], ${$h{"COSCS205S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS249S</FONT></TD>\n", ${$h{"COSCS249S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS249S"}}[3], ${$h{"COSCS249S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2R2Y</FONT></TD>\n", ${$h{"AIRU2R2Y"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AIRU2R2Y"}}[3], ${$h{"AIRU2R2Y"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS162S</FONT></TD>\n", ${$h{"COSCS162S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS162S"}}[3], ${$h{"COSCS162S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS206S</FONT></TD>\n", ${$h{"COSCS206S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS206S"}}[3], ${$h{"COSCS206S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS250S</FONT></TD>\n", ${$h{"COSCS250S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS250S"}}[3], ${$h{"COSCS250S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS163S</FONT></TD>\n", ${$h{"COSCS163S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS163S"}}[3], ${$h{"COSCS163S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS207S</FONT></TD>\n", ${$h{"COSCS207S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS207S"}}[3], ${$h{"COSCS207S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS251S</FONT></TD>\n", ${$h{"COSCS251S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS251S"}}[3], ${$h{"COSCS251S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS164S</FONT></TD>\n", ${$h{"COSCS164S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS164S"}}[3], ${$h{"COSCS164S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS208S</FONT></TD>\n", ${$h{"COSCS208S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS208S"}}[3], ${$h{"COSCS208S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS252S</FONT></TD>\n", ${$h{"COSCS252S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS252S"}}[3], ${$h{"COSCS252S"}}[1];
printf SF "<TR><TD ALIGN=LEFT COLSPAN=4><FONT SIZE=4>Verify EPS is Power Positive</FONT>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS165S</FONT></TD>\n", ${$h{"COSCS165S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS165S"}}[3], ${$h{"COSCS165S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS209S</FONT></TD>\n", ${$h{"COSCS209S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS209S"}}[3], ${$h{"COSCS209S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS253S</FONT></TD>\n", ${$h{"COSCS253S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS253S"}}[3], ${$h{"COSCS253S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ELBV</FONT></TD>\n", ${$h{"ELBV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%5.2f</FONT></TD>\n", ${$h{"ELBV"}}[3], ${$h{"ELBV"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS166S</FONT></TD>\n", ${$h{"COSCS166S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS166S"}}[3], ${$h{"COSCS166S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS210S</FONT></TD>\n", ${$h{"COSCS210S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS210S"}}[3], ${$h{"COSCS210S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS254S</FONT></TD>\n", ${$h{"COSCS254S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS254S"}}[3], ${$h{"COSCS254S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ELBI_LOW</FONT></TD>\n", ${$h{"ELBI_LOW"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%5.2f</FONT></TD>\n", ${$h{"ELBI_LOW"}}[3], ${$h{"ELBI_LOW"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS167S</FONT></TD>\n", ${$h{"COSCS167S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS167S"}}[3], ${$h{"COSCS167S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS211S</FONT></TD>\n", ${$h{"COSCS211S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS211S"}}[3], ${$h{"COSCS211S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS255S</FONT></TD>\n", ${$h{"COSCS255S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS255S"}}[3], ${$h{"COSCS255S"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EPSTATE</FONT></TD>\n", ${$h{"EPSTATE"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"EPSTATE"}}[3], ${$h{"EPSTATE"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS168S</FONT></TD>\n", ${$h{"COSCS168S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS168S"}}[3], ${$h{"COSCS168S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSCS212S</FONT></TD>\n", ${$h{"COSCS212S"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"COSCS212S"}}[3], ${$h{"COSCS212S"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSAILLM</FONT></TD>\n", ${$h{"AOSAILLM"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"AOSAILLM"}}[3], ${$h{"AOSAILLM"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ESAMYI</FONT></TD>\n", ${$h{"ESAMYI"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"ESAMYI"}}[3], ${$h{"ESAMYI"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT COLSPAN=2><FONT SIZE=4>Gratings</FONT>\n";
printf SF "<TD ALIGN=LEFT COLSPAN=2><FONT SIZE=4>SIM</FONT>\n";
printf SF "<TD ALIGN=LEFT COLSPAN=2><FONT SIZE=4>HRC</FONT>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ESAPYI</FONT></TD>\n", ${$h{"ESAPYI"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"ESAPYI"}}[3], ${$h{"ESAPYI"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4M5IRAX</FONT></TD>\n", ${$h{"4M5IRAX"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4M5IRAX"}}[3], ${$h{"4M5IRAX"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3TSCPOS</FONT></TD>\n", ${$h{"3TSCPOS"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%d</FONT></TD>\n", ${$h{"3TSCPOS"}}[3], ${$h{"3TSCPOS"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>2S1ONST</FONT></TD>\n", ${$h{"2S1ONST"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"2S1ONST"}}[3], ${$h{"2S1ONST"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EB1V</FONT></TD>\n", ${$h{"EB1V"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"EB1V"}}[3], ${$h{"EB1V"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4HEXRAX</FONT></TD>\n", ${$h{"4HEXRAX"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4HEXRAX"}}[3], ${$h{"4HEXRAX"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3SMOTPEN</FONT></TD>\n", ${$h{"3SMOTPEN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SMOTPEN"}}[3], ${$h{"3SMOTPEN"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>2S2ONST</FONT></TD>\n", ${$h{"2S2ONST"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"2S2ONST"}}[3], ${$h{"2S2ONST"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EB1DI</FONT></TD>\n", ${$h{"EB1DI"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"EB1DI"}}[3], ${$h{"EB1DI"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4LEXRAX</FONT></TD>\n", ${$h{"4LEXRAX"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4LEXRAX"}}[3], ${$h{"4LEXRAX"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>3SMOTSEL</FONT></TD>\n", ${$h{"3SMOTSEL"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SMOTSEL"}}[3], ${$h{"3SMOTSEL"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>2SPTPAST</FONT></TD>\n", ${$h{"2SPTPAST"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"2SPTPAST"}}[3], ${$h{"2SPTPAST"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EB1CI</FONT></TD>\n", ${$h{"EB1CI"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"EB1CI"}}[3], ${$h{"EB1CI"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4M28IRAX</FONT></TD>\n", ${$h{"4M28IRAX"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4M28IRAX"}}[3], ${$h{"4M28IRAX"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>2SPBPAST</FONT></TD>\n", ${$h{"2SPBPAST"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"2SPBPAST"}}[3], ${$h{"2SPBPAST"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EB1UV</FONT></TD>\n", ${$h{"EB1UV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"EB1UV"}}[3], ${$h{"EB1UV"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4M5IRBX</FONT></TD>\n", ${$h{"4M5IRBX"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4M5IRBX"}}[3], ${$h{"4M5IRBX"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>2IMTPAST</FONT></TD>\n", ${$h{"2IMTPAST"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"2IMTPAST"}}[3], ${$h{"2IMTPAST"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EB2V</FONT></TD>\n", ${$h{"EB2V"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"EB2V"}}[3], ${$h{"EB2V"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4HEXRBX</FONT></TD>\n", ${$h{"4HEXRBX"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4HEXRBX"}}[3], ${$h{"4HEXRBX"}}[1];
printf SF "<TD ALIGN=LEFT COLSPAN=2><FONT SIZE=4>ACIS</FONT>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>2IMBPAST</FONT></TD>\n", ${$h{"2IMBPAST"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"2IMBPAST"}}[3], ${$h{"2IMBPAST"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EB2DI</FONT></TD>\n", ${$h{"EB2DI"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"EB2DI"}}[3], ${$h{"EB2DI"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4LEXRBX</FONT></TD>\n", ${$h{"4LEXRBX"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4LEXRBX"}}[3], ${$h{"4LEXRBX"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>1DPICACU</FONT></TD>\n", ${$h{"1DPICACU"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"1DPICACU"}}[3], ${$h{"1DPICACU"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>2S1HVST</FONT></TD>\n", ${$h{"2S1HVST"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"2S1HVST"}}[3], ${$h{"2S1HVST"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EB2CI</FONT></TD>\n", ${$h{"EB2CI"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"EB2CI"}}[3], ${$h{"EB2CI"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4M28IRBX</FONT></TD>\n", ${$h{"4M28IRBX"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4M28IRBX"}}[3], ${$h{"4M28IRBX"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>1DPICBCU</FONT></TD>\n", ${$h{"1DPICBCU"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"1DPICBCU"}}[3], ${$h{"1DPICBCU"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>2S2HVST</FONT></TD>\n", ${$h{"2S2HVST"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"2S2HVST"}}[3], ${$h{"2S2HVST"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EB2UV</FONT></TD>\n", ${$h{"EB2UV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"EB2UV"}}[3], ${$h{"EB2UV"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>1CBAT</FONT></TD>\n", ${$h{"1CBAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"1CBAT"}}[3], ${$h{"1CBAT"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>2SCTHAST</FONT></TD>\n", ${$h{"2SCTHAST"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"2SCTHAST"}}[3], ${$h{"2SCTHAST"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EB3V</FONT></TD>\n", ${$h{"EB3V"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"EB3V"}}[3], ${$h{"EB3V"}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>2MCNAAMD</FONT></TD>\n", ${$h{"2MCNAAMD"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"2MCNAAMD"}}[3], ${$h{"2MCNAAMD"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EB3DI</FONT></TD>\n", ${$h{"EB3DI"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"EB3DI"}}[3], ${$h{"EB3DI"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EB3CI</FONT></TD>\n", ${$h{"EB3CI"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"EB3CI"}}[3], ${$h{"EB3CI"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EB3UV</FONT></TD>\n", ${$h{"EB3UV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"EB3UV"}}[3], ${$h{"EB3UV"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=2><FONT SIZE=4>Verify OBC-B Thermal Control</FONT>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUCBLIN</FONT></TD>\n", ${$h{"CIUCBLIN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"CIUCBLIN"}}[3], ${$h{"CIUCBLIN"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4OTCPEN</FONT></TD>\n", ${$h{"4OTCPEN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4OTCPEN"}}[3], ${$h{"4OTCPEN"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4OACHRMH</FONT></TD>\n", ${$h{"4OACHRMH"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4OACHRMH"}}[3], ${$h{"4OACHRMH"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4OACOBAH</FONT></TD>\n", ${$h{"4OACOBAH"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4OACOBAH"}}[3], ${$h{"4OACOBAH"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4OTCDBSL</FONT></TD>\n", ${$h{"4OTCDBSL"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4OTCDBSL"}}[3], ${$h{"4OTCDBSL"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>4OCDIPSL</FONT></TD>\n", ${$h{"4OCDIPSL"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"4OCDIPSL"}}[3], ${$h{"4OCDIPSL"}}[1];

printf SF "</TABLE>\n";
printf SF "<BR>\n";
close SF;

print_links("$outfile");
print SF "</BODY></HTML>\n";
close SF;
# end
}
1;
