sub soh_format {
  $outfile = shift @_;
  %h = @_;

  print_head("$outfile","S/C Configuration", %h);

open (SF, ">>$outfile");
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD><TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>Flight Software</FONT></TR>";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SCS 128 STATE <br>  INAC SUSP ACT DISA', CAPTION, 'COSCS128S' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>COSCS128S</FONT></a></TD>\n", ${$h{COSCS128S}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSCS128S}}[3], ${$h{COSCS128S}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SCS 129 STATE <br>  ACT INAC SUSP DISA', CAPTION, 'COSCS129S' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>COSCS129S</FONT></a></TD>\n", ${$h{COSCS129S}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSCS129S}}[3], ${$h{COSCS129S}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SCS 130 STATE <br>  INAC SUSP ACT DISA', CAPTION, 'COSCS130S' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>COSCS130S</FONT></a></TD>\n", ${$h{COSCS130S}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSCS130S}}[3], ${$h{COSCS130S}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SCS 107 STATE <br>  INAC SUSP ACT DISA', CAPTION, 'COSCS107S' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>COSCS107S</FONT></a></TD>\n", ${$h{COSCS107S}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSCS107S}}[3], ${$h{COSCS107S}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('RAD MON PROCESS STATE <br>  ENAB DISA', CAPTION, 'CORADMEN' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>CORADMEN</FONT></a></TD>\n", ${$h{CORADMEN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CORADMEN}}[3], ${$h{CORADMEN}}[1];
printf SF "<TR><TD><FONT SIZE=2>&nbsp</TR>\n";
printf SF "</TABLE>\n";

printf SF "<TD><TABLE BORDER=0><TR><TD><FONT SIZE=2>\&nbsp</TR></TABLE>\n";

printf SF "<TD><TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>Attitude</FONT></TR>\n";

printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('ESTIMATED SPACECRAFT ATTITUDE QUATERION 1 (ECI) <br>limits', CAPTION, 'AOATTQT1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOATTQT1</FONT></a></TD>\n", ${$h{AOATTQT1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%10.7f</FONT></TD>\n", ${$h{AOATTQT1}}[3], ${$h{AOATTQT1}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('ESTIMATED SPACECRAFT ATTITUDE QUATERION 2 (ECI) <br>limits', CAPTION, 'AOATTQT2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOATTQT2</FONT></a></TD>\n", ${$h{AOATTQT2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%10.7f</FONT></TD>\n", ${$h{AOATTQT2}}[3], ${$h{AOATTQT2}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('ESTIMATED SPACECRAFT ATTITUDE QUATERION 3 (ECI) <br>limits', CAPTION, 'AOATTQT3' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOATTQT3</FONT></a></TD>\n", ${$h{AOATTQT3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%10.7f</FONT></TD>\n", ${$h{AOATTQT3}}[3], ${$h{AOATTQT3}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('ESTIMATED SPACECRAFT ATTITUDE QUATERION 4 (ECI) <br>limits', CAPTION, 'AOATTQT4' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOATTQT4</FONT></a></TD>\n", ${$h{AOATTQT4}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%10.7f</FONT></TD>\n", ${$h{AOATTQT4}}[3], ${$h{AOATTQT4}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FSS ALPHA ANGLE MEAS DEG<br>limits', CAPTION, 'AOALPANG' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOALPANG</FONT></a></TD>\n", ${$h{AOALPANG}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOALPANG}}[3], ${$h{AOALPANG}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FSS BETA ANGLE MEAS DEG<br>limits', CAPTION, 'AOBETANG' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOBETANG</FONT></a></TD>\n", ${$h{AOBETANG}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOBETANG}}[3], ${$h{AOBETANG}}[1];
printf SF "</TABLE>\n";

printf SF "<TD><TABLE BORDER=0><TR><TD><FONT SIZE=2>\&nbsp</TR></TABLE>\n";

printf SF "<TD><TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>SIM \& OTGs</FONT></TR>\n";

printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA TSC POSITION STEP<br><font color=#FFFF00>(-103951.0) 104445.0 </font><br><font color=#FF0000>(-104428.0) 104445.0</font>', CAPTION, '3TSCPOS' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3TSCPOS</FONT></a></TD>\n", ${$h{"3TSCPOS"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%d</FONT></TD>\n", ${$h{"3TSCPOS"}}[3], ${$h{"3TSCPOS"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA FA POSITION STEP<br><font color=#FFFF00>(-11313.0) 6462.0 </font><br><font color=#FF0000>(-11580.0) 6462.0</font>', CAPTION, '3FAPOS' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3FAPOS</FONT></a></TD>\n", ${$h{"3FAPOS"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%d</FONT></TD>\n", ${$h{"3FAPOS"}}[3], ${$h{"3FAPOS"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('HETG ROTATION ANGLE POSITION MONITOR A DEG<br>limits', CAPTION, '4HPOSARO' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4HPOSARO</FONT></a></TD>\n", ${$h{"4HPOSARO"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4HPOSARO"}}[3], ${$h{"4HPOSARO"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('LETG ROTATION ANGLE POSITION MONITOR B DEG<br>limits', CAPTION, '4LPOSBRO' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4LPOSBRO</FONT></a></TD>\n", ${$h{"4LPOSBRO"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4LPOSBRO"}}[3], ${$h{"4LPOSBRO"}}[1];
printf SF "<TR><TD><FONT SIZE=2>&nbsp</TR>\n";
printf SF "<TR><TD><FONT SIZE=2>&nbsp</TR>\n";
printf SF "</TABLE>\n";

printf SF "<TD><TABLE BORDER=0><TR><TD><FONT SIZE=2>\&nbsp</TR></TABLE>\n";

printf SF "<TD><TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>Misc</FONT></TR>\n";

printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('ACTUATOR SELECTION FLAG (MUPS OR RCS) <br>  MUPS RCS', CAPTION, 'AOFTHRST' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOFTHRST</FONT></a></TD>\n", ${$h{AOFTHRST}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOFTHRST}}[3], ${$h{AOFTHRST}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('ATTITUDE COMMAND MODE FLAG <br>  MNVR STDY NULL DTHR', CAPTION, 'AOFATTMD' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOFATTMD</FONT></a></TD>\n", ${$h{AOFATTMD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOFATTMD}}[3], ${$h{AOFATTMD}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SUN_POS_MON S/W STATE <br>  ACT INAC INIT DISA SUSP', CAPTION, 'AOPSSUPM' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOPSSUPM</FONT></a></TD>\n", ${$h{AOPSSUPM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSSUPM}}[3], ${$h{AOPSSUPM}}[1];
printf SF "<TR><TD><FONT SIZE=2>&nbsp</TR>\n";
printf SF "<TR><TD><FONT SIZE=2>&nbsp</TR>\n";
printf SF "<TR><TD><FONT SIZE=2>&nbsp</TR>\n";
printf SF "</TABLE>\n";
printf SF "</TABLE>\n";

printf SF "<BR>\n";

printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=11><FONT SIZE=4>Stars \& Fids</FONT></TR>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=1><FONT SIZE=3>Image</FONT>\n";
printf SF "<TD><FONT SIZE=2>&nbsp\n";
printf SF "<TD ALIGN=CENTER COLSPAN=1><FONT SIZE=3>Status Flags</FONT>\n";
printf SF "<TD><FONT SIZE=2>&nbsp\n";
printf SF "<TD ALIGN=CENTER COLSPAN=1><FONT SIZE=3>Image Function</FONT>\n";
printf SF "<TD><FONT SIZE=2>&nbsp\n";
printf SF "<TD ALIGN=CENTER COLSPAN=1><FONT SIZE=3>Centroid Y Angle</FONT>\n";
printf SF "<TD><FONT SIZE=2>&nbsp\n";
printf SF "<TD ALIGN=CENTER COLSPAN=1><FONT SIZE=3>Centroid Z Angle</FONT>\n";
printf SF "<TD><FONT SIZE=2>&nbsp\n";
printf SF "<TD ALIGN=CENTER COLSPAN=1><FONT SIZE=3>Magnitude</FONT></TR>\n";

#printf SF "<TR><TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE 0 NUMBER <br>  4 7 6 5 2 1 0 3', CAPTION, 'AOIMNUM0' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOIMNUM0</FONT></a></TD>\n", ${$h{AOIMNUM0}}[3];
printf SF "<TR><TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIMNUM0}}[3], ${$h{AOIMNUM0}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE 0 STATUS FLAG <br>  NULL FID STAR', CAPTION, 'AOIMAGE0' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOIMAGE0</FONT></a></TD>\n", ${$h{AOIMAGE0}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIMAGE0}}[3], ${$h{AOIMAGE0}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE FUNCTION (IMAGE 0) (OBC) <br>  NONE TRAK SRCH RACQ', CAPTION, 'AOACFCT0' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACFCT0</FONT></a></TD>\n", ${$h{AOACFCT0}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOACFCT0}}[3], ${$h{AOACFCT0}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('YAG CENTROID Y ANGLE (IMAGE 0) (OBC) ASEC<br><font color=#FFFF00>(-2520.0) 2520.0 </font><br><font color=#FF0000>(-2521.0) 2520.0</font>', CAPTION, 'AOACYAN0' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACYAN0</FONT></a></TD>\n", ${$h{AOACYAN0}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACYAN0}}[3], ${$h{AOACYAN0}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('ZAG CENTROID Z ANGLE (IMAGE 0) (OBC) ASEC<br><font color=#FFFF00>(-2520.0) 2520.0 </font><br><font color=#FF0000>(-2521.0) 2520.0</font>', CAPTION, 'AOACZAN0' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACZAN0</FONT></a></TD>\n", ${$h{AOACZAN0}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACZAN0}}[3], ${$h{AOACZAN0}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('STAR OR FIDUCIAL MAGNITUDE (IMAGE 0) (OBC) <br>limits', CAPTION, 'AOACMAG0' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACMAG0</FONT></a></TD>\n", ${$h{AOACMAG0}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACMAG0}}[3], ${$h{AOACMAG0}}[1];
#printf SF "<TR><TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE 1 NUMBER <br>  7 0 1 2 3 4 5 6', CAPTION, 'AOIMNUM1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOIMNUM1</FONT></a></TD>\n", ${$h{AOIMNUM1}}[3];
printf SF "<TR><TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIMNUM1}}[3], ${$h{AOIMNUM1}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE 1 STATUS FLAG <br>  FID STAR NULL', CAPTION, 'AOIMAGE1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOIMAGE1</FONT></a></TD>\n", ${$h{AOIMAGE1}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIMAGE1}}[3], ${$h{AOIMAGE1}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE FUNCTION (IMAGE 1) (OBC) <br>  NONE RACQ TRAK SRCH', CAPTION, 'AOACFCT1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACFCT1</FONT></a></TD>\n", ${$h{AOACFCT1}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOACFCT1}}[3], ${$h{AOACFCT1}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('YAG CENTROID Y ANGLE (IMAGE 1) (OBC) ASEC<br><font color=#FFFF00>(-2520.0) 2520.0 </font><br><font color=#FF0000>(-2521.0) 2520.0</font>', CAPTION, 'AOACYAN1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACYAN1</FONT></a></TD>\n", ${$h{AOACYAN1}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACYAN1}}[3], ${$h{AOACYAN1}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('ZAG CENTROID Z ANGLE (IMAGE 1) (OBC) ASEC<br><font color=#FFFF00>(-2520.0) 2520.0 </font><br><font color=#FF0000>(-2521.0) 2520.0</font>', CAPTION, 'AOACZAN1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACZAN1</FONT></a></TD>\n", ${$h{AOACZAN1}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACZAN1}}[3], ${$h{AOACZAN1}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('STAR OR FIDUCIAL MAGNITUDE (IMAGE 1) (OBC) <br>limits', CAPTION, 'AOACMAG1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACMAG1</FONT></a></TD>\n", ${$h{AOACMAG1}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACMAG1}}[3], ${$h{AOACMAG1}}[1];
#printf SF "<TR><TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE 2 NUMBER <br>  6 5 4 3 2 0 7 1', CAPTION, 'AOIMNUM2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOIMNUM2</FONT></a></TD>\n", ${$h{AOIMNUM2}}[3];
printf SF "<TR><TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIMNUM2}}[3], ${$h{AOIMNUM2}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE 2 STATUS FLAG <br>  NULL FID STAR', CAPTION, 'AOIMAGE2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOIMAGE2</FONT></a></TD>\n", ${$h{AOIMAGE2}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIMAGE2}}[3], ${$h{AOIMAGE2}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE FUNCTION (IMAGE 2) (OBC) <br>  NONE TRAK SRCH RACQ', CAPTION, 'AOACFCT2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACFCT2</FONT></a></TD>\n", ${$h{AOACFCT2}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOACFCT2}}[3], ${$h{AOACFCT2}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('YAG CENTROID Y ANGLE (IMAGE 2) (OBC) ASEC<br><font color=#FFFF00>(-2520.0) 2520.0 </font><br><font color=#FF0000>(-2521.0) 2520.0</font>', CAPTION, 'AOACYAN2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACYAN2</FONT></a></TD>\n", ${$h{AOACYAN2}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACYAN2}}[3], ${$h{AOACYAN2}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('ZAG CENTROID Z ANGLE (IMAGE 2) (OBC) ASEC<br><font color=#FFFF00>(-2520.0) 2520.0 </font><br><font color=#FF0000>(-2521.0) 2520.0</font>', CAPTION, 'AOACZAN2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACZAN2</FONT></a></TD>\n", ${$h{AOACZAN2}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACZAN2}}[3], ${$h{AOACZAN2}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('STAR OR FIDUCIAL MAGNITUDE (IMAGE 2) (OBC) <br>limits', CAPTION, 'AOACMAG2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACMAG2</FONT></a></TD>\n", ${$h{AOACMAG2}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACMAG2}}[3], ${$h{AOACMAG2}}[1];
#printf SF "<TR><TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE 3 NUMBER <br>  4 7 6 5 2 0 1 3', CAPTION, 'AOIMNUM3' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOIMNUM3</FONT></a></TD>\n", ${$h{AOIMNUM3}}[3];
printf SF "<TR><TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIMNUM3}}[3], ${$h{AOIMNUM3}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE 3 STATUS FLAG <br>  NULL STAR FID', CAPTION, 'AOIMAGE3' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOIMAGE3</FONT></a></TD>\n", ${$h{AOIMAGE3}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIMAGE3}}[3], ${$h{AOIMAGE3}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE FUNCTION (IMAGE 3) (OBC) <br>  RACQ SRCH TRAK NONE', CAPTION, 'AOACFCT3' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACFCT3</FONT></a></TD>\n", ${$h{AOACFCT3}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOACFCT3}}[3], ${$h{AOACFCT3}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('YAG CENTROID Y ANGLE (IMAGE 3) (OBC) ASEC<br><font color=#FFFF00>(-2520.0) 2520.0 </font><br><font color=#FF0000>(-2521.0) 2520.0</font>', CAPTION, 'AOACYAN3' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACYAN3</FONT></a></TD>\n", ${$h{AOACYAN3}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACYAN3}}[3], ${$h{AOACYAN3}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('ZAG CENTROID Z ANGLE (IMAGE 3) (OBC) ASEC<br><font color=#FFFF00>(-2520.0) 2520.0 </font><br><font color=#FF0000>(-2521.0) 2520.0</font>', CAPTION, 'AOACZAN3' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACZAN3</FONT></a></TD>\n", ${$h{AOACZAN3}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACZAN3}}[3], ${$h{AOACZAN3}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('STAR OR FIDUCIAL MAGNITUDE (IMAGE 3) (OBC) <br>limits', CAPTION, 'AOACMAG3' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACMAG3</FONT></a></TD>\n", ${$h{AOACMAG3}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACMAG3}}[3], ${$h{AOACMAG3}}[1];
#printf SF "<TR><TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE 4 NUMBER <br>  3 7 6 4 2 1 0 5', CAPTION, 'AOIMNUM4' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOIMNUM4</FONT></a></TD>\n", ${$h{AOIMNUM4}}[3];
printf SF "<TR><TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIMNUM4}}[3], ${$h{AOIMNUM4}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE 4 STATUS FLAG <br>  FID STAR NULL', CAPTION, 'AOIMAGE4' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOIMAGE4</FONT></a></TD>\n", ${$h{AOIMAGE4}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIMAGE4}}[3], ${$h{AOIMAGE4}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE FUNCTION (IMAGE 4) (OBC) <br>  TRAK SRCH RACQ NONE', CAPTION, 'AOACFCT4' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACFCT4</FONT></a></TD>\n", ${$h{AOACFCT4}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOACFCT4}}[3], ${$h{AOACFCT4}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('YAG CENTROID Y ANGLE (IMAGE 4) (OBC) ASEC<br><font color=#FFFF00>(-2520.0) 2520.0 </font><br><font color=#FF0000>(-2521.0) 2520.0</font>', CAPTION, 'AOACYAN4' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACYAN4</FONT></a></TD>\n", ${$h{AOACYAN4}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACYAN4}}[3], ${$h{AOACYAN4}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('ZAG CENTROID Z ANGLE (IMAGE 4) (OBC) ASEC<br><font color=#FFFF00>(-2520.0) 2520.0 </font><br><font color=#FF0000>(-2521.0) 2520.0</font>', CAPTION, 'AOACZAN4' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACZAN4</FONT></a></TD>\n", ${$h{AOACZAN4}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACZAN4}}[3], ${$h{AOACZAN4}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('STAR OR FIDUCIAL MAGNITUDE (IMAGE 4) (OBC) <br>limits', CAPTION, 'AOACMAG4' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACMAG4</FONT></a></TD>\n", ${$h{AOACMAG4}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACMAG4}}[3], ${$h{AOACMAG4}}[1];
#printf SF "<TR><TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE 5 NUMBER <br>  3 6 7 4 1 0 5 2', CAPTION, 'AOIMNUM5' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOIMNUM5</FONT></a></TD>\n", ${$h{AOIMNUM5}}[3];
printf SF "<TR><TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIMNUM5}}[3], ${$h{AOIMNUM5}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE 5 STATUS FLAG <br>  FID STAR NULL', CAPTION, 'AOIMAGE5' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOIMAGE5</FONT></a></TD>\n", ${$h{AOIMAGE5}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIMAGE5}}[3], ${$h{AOIMAGE5}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE FUNCTION (IMAGE 5) (OBC) <br>  RACQ NONE TRAK SRCH', CAPTION, 'AOACFCT5' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACFCT5</FONT></a></TD>\n", ${$h{AOACFCT5}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOACFCT5}}[3], ${$h{AOACFCT5}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('YAG CENTROID Y ANGLE (IMAGE 5) (OBC) ASEC<br><font color=#FFFF00>(-2520.0) 2520.0 </font><br><font color=#FF0000>(-2521.0) 2520.0</font>', CAPTION, 'AOACYAN5' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACYAN5</FONT></a></TD>\n", ${$h{AOACYAN5}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACYAN5}}[3], ${$h{AOACYAN5}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('ZAG CENTROID Z ANGLE (IMAGE 5) (OBC) ASEC<br><font color=#FFFF00>(-2520.0) 2520.0 </font><br><font color=#FF0000>(-2521.0) 2520.0</font>', CAPTION, 'AOACZAN5' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACZAN5</FONT></a></TD>\n", ${$h{AOACZAN5}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACZAN5}}[3], ${$h{AOACZAN5}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('STAR OR FIDUCIAL MAGNITUDE (IMAGE 5) (OBC) <br>limits', CAPTION, 'AOACMAG5' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACMAG5</FONT></a></TD>\n", ${$h{AOACMAG5}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACMAG5}}[3], ${$h{AOACMAG5}}[1];
#printf SF "<TR><TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE 6 NUMBER <br>  5 6 4 3 2 1 0 7', CAPTION, 'AOIMNUM6' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOIMNUM6</FONT></a></TD>\n", ${$h{AOIMNUM6}}[3];
printf SF "<TR><TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIMNUM6}}[3], ${$h{AOIMNUM6}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE 6 STATUS FLAG <br>  FID STAR NULL', CAPTION, 'AOIMAGE6' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOIMAGE6</FONT></a></TD>\n", ${$h{AOIMAGE6}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIMAGE6}}[3], ${$h{AOIMAGE6}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE FUNCTION (IMAGE 6) (OBC) <br>  RACQ SRCH NONE TRAK', CAPTION, 'AOACFCT6' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACFCT6</FONT></a></TD>\n", ${$h{AOACFCT6}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOACFCT6}}[3], ${$h{AOACFCT6}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('YAG CENTROID Y ANGLE (IMAGE 6) (OBC) ASEC<br><font color=#FFFF00>(-2520.0) 2520.0 </font><br><font color=#FF0000>(-2521.0) 2520.0</font>', CAPTION, 'AOACYAN6' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACYAN6</FONT></a></TD>\n", ${$h{AOACYAN6}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACYAN6}}[3], ${$h{AOACYAN6}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('ZAG CENTROID Z ANGLE (IMAGE 6) (OBC) ASEC<br><font color=#FFFF00>(-2520.0) 2520.0 </font><br><font color=#FF0000>(-2521.0) 2520.0</font>', CAPTION, 'AOACZAN6' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACZAN6</FONT></a></TD>\n", ${$h{AOACZAN6}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACZAN6}}[3], ${$h{AOACZAN6}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('STAR OR FIDUCIAL MAGNITUDE (IMAGE 6) (OBC) <br>limits', CAPTION, 'AOACMAG6' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACMAG6</FONT></a></TD>\n", ${$h{AOACMAG6}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACMAG6}}[3], ${$h{AOACMAG6}}[1];
#printf SF "<TR><TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE 7 NUMBER <br>  7 0 1 2 3 4 5 6', CAPTION, 'AOIMNUM7' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOIMNUM7</FONT></a></TD>\n", ${$h{AOIMNUM7}}[3];
printf SF "<TR><TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIMNUM7}}[3], ${$h{AOIMNUM7}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE 7 STATUS FLAG <br>  FID STAR NULL', CAPTION, 'AOIMAGE7' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOIMAGE7</FONT></a></TD>\n", ${$h{AOIMAGE7}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIMAGE7}}[3], ${$h{AOIMAGE7}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('IMAGE FUNCTION (IMAGE 7) (OBC) <br>  NONE TRAK SRCH RACQ', CAPTION, 'AOACFCT7' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACFCT7</FONT></a></TD>\n", ${$h{AOACFCT7}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOACFCT7}}[3], ${$h{AOACFCT7}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('YAG CENTROID Y ANGLE (IMAGE 7) (OBC) ASEC<br><font color=#FFFF00>(-2520.0) 2520.0 </font><br><font color=#FF0000>(-2521.0) 2520.0</font>', CAPTION, 'AOACYAN7' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACYAN7</FONT></a></TD>\n", ${$h{AOACYAN7}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACYAN7}}[3], ${$h{AOACYAN7}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('ZAG CENTROID Z ANGLE (IMAGE 7) (OBC) ASEC<br><font color=#FFFF00>(-2520.0) 2520.0 </font><br><font color=#FF0000>(-2521.0) 2520.0</font>', CAPTION, 'AOACZAN7' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACZAN7</FONT></a></TD>\n", ${$h{AOACZAN7}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACZAN7}}[3], ${$h{AOACZAN7}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp\n";
#printf SF "<TD ALIGN=CENTER> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('STAR OR FIDUCIAL MAGNITUDE (IMAGE 7) (OBC) <br>limits', CAPTION, 'AOACMAG7' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>AOACMAG7</FONT></a></TD>\n", ${$h{AOACMAG7}}[3];
printf SF "<TD ALIGN=CENTER><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACMAG7}}[3], ${$h{AOACMAG7}}[1];
printf SF "</TABLE>\n";
printf SF "<BR>\n";
close SF;

print_links("$outfile");
open (SF,">>$outfile");
print SF "</BODY></HTML>\n";
close SF;
# end
}
1;
