sub soh_format {
  $outfile = shift @_;
  %h = @_;
  print_head("$outfile","CCDM", %h);

open (SF, ">>$outfile");

printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>CTU</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CCTXA</FONT></TD>\n", ${$h{CCTXA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CCTXA}}[3], ${$h{CCTXA}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CEM5VPPR</FONT></TD>\n", ${$h{CEM5VPPR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CEM5VPPR}}[3], ${$h{CEM5VPPR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSTSA</FONT></TD>\n", ${$h{CSTSA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CSTSA}}[3], ${$h{CSTSA}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CUSOBPWR</FONT></TD>\n", ${$h{CUSOBPWR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CUSOBPWR}}[3], ${$h{CUSOBPWR}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CCTXB</FONT></TD>\n", ${$h{CCTXB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CCTXB}}[3], ${$h{CCTXB}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CEM5VPRD</FONT></TD>\n", ${$h{CEM5VPRD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CEM5VPRD}}[3], ${$h{CEM5VPRD}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSTSB</FONT></TD>\n", ${$h{CSTSB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CSTSB}}[3], ${$h{CSTSB}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CVEEP</FONT></TD>\n", ${$h{CVEEP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CVEEP}}[3], ${$h{CVEEP}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CE5VPCPR</FONT></TD>\n", ${$h{CE5VPCPR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CE5VPCPR}}[3], ${$h{CE5VPCPR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSBKWR1</FONT></TD>\n", ${$h{CSBKWR1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CSBKWR1}}[3], ${$h{CSBKWR1}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUBITRS</FONT></TD>\n", ${$h{CTUBITRS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CTUBITRS}}[3], ${$h{CTUBITRS}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CVEER</FONT></TD>\n", ${$h{CVEER}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CVEER}}[3], ${$h{CVEER}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CE5VPCRD</FONT></TD>\n", ${$h{CE5VPCRD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CE5VPCRD}}[3], ${$h{CE5VPCRD}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSBKWR2</FONT></TD>\n", ${$h{CSBKWR2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CSBKWR2}}[3], ${$h{CSBKWR2}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CUSOAPWR</FONT></TD>\n", ${$h{CUSOAPWR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CUSOAPWR}}[3], ${$h{CUSOAPWR}}[1];
#printf SF "</TABLE>\n";

printf SF "<TR>\n";
#printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>EIA</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AHKNATPR</FONT></TD>\n", ${$h{AHKNATPR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AHKNATPR}}[3], ${$h{AHKNATPR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CPORD1X</FONT></TD>\n", ${$h{CPORD1X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CPORD1X}}[3], ${$h{CPORD1X}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQATI1</FONT></TD>\n", ${$h{C2SQATI1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQATI1}}[3], ${$h{C2SQATI1}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQOBAR</FONT></TD>\n", ${$h{C2SQOBAR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQOBAR}}[3], ${$h{C2SQOBAR}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AHKNATRD</FONT></TD>\n", ${$h{AHKNATRD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AHKNATRD}}[3], ${$h{AHKNATRD}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CPORD2X</FONT></TD>\n", ${$h{CPORD2X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CPORD2X}}[3], ${$h{CPORD2X}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQATI2</FONT></TD>\n", ${$h{C2SQATI2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQATI2}}[3], ${$h{C2SQATI2}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQOBBP</FONT></TD>\n", ${$h{C2SQOBBP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQOBBP}}[3], ${$h{C2SQOBBP}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQAPCT</FONT></TD>\n", ${$h{C1SQAPCT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQAPCT}}[3], ${$h{C1SQAPCT}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CRORD1X</FONT></TD>\n", ${$h{CRORD1X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CRORD1X}}[3], ${$h{CRORD1X}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQATPP</FONT></TD>\n", ${$h{C2SQATPP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQATPP}}[3], ${$h{C2SQATPP}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQOBBR</FONT></TD>\n", ${$h{C2SQOBBR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQOBBR}}[3], ${$h{C2SQOBBR}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQAPIU</FONT></TD>\n", ${$h{C1SQAPIU}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQAPIU}}[3], ${$h{C1SQAPIU}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CRORD2X</FONT></TD>\n", ${$h{CRORD2X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CRORD2X}}[3], ${$h{CRORD2X}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQATPS</FONT></TD>\n", ${$h{C2SQATPS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQATPS}}[3], ${$h{C2SQATPS}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQPTLX</FONT></TD>\n", ${$h{C2SQPTLX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQPTLX}}[3], ${$h{C2SQPTLX}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQAPO</FONT></TD>\n", ${$h{C1SQAPO}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQAPO}}[3], ${$h{C1SQAPO}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQBTPP</FONT></TD>\n", ${$h{C1SQBTPP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQBTPP}}[3], ${$h{C1SQBTPP}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQAX</FONT></TD>\n", ${$h{C2SQAX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQAX}}[3], ${$h{C2SQAX}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQRTLX</FONT></TD>\n", ${$h{C2SQRTLX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQRTLX}}[3], ${$h{C2SQRTLX}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQAPPP</FONT></TD>\n", ${$h{C1SQAPPP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQAPPP}}[3], ${$h{C1SQAPPP}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQBTPS</FONT></TD>\n", ${$h{C1SQBTPS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQBTPS}}[3], ${$h{C1SQBTPS}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQBPCT</FONT></TD>\n", ${$h{C2SQBPCT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQBPCT}}[3], ${$h{C2SQBPCT}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CM1CKBP1</FONT></TD>\n", ${$h{CM1CKBP1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CM1CKBP1}}[3], ${$h{CM1CKBP1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQATI1</FONT></TD>\n", ${$h{C1SQATI1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQATI1}}[3], ${$h{C1SQATI1}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQBX</FONT></TD>\n", ${$h{C1SQBX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQBX}}[3], ${$h{C1SQBX}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQBPIU</FONT></TD>\n", ${$h{C2SQBPIU}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQBPIU}}[3], ${$h{C2SQBPIU}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CM1CKBP2</FONT></TD>\n", ${$h{CM1CKBP2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CM1CKBP2}}[3], ${$h{CM1CKBP2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQATI2</FONT></TD>\n", ${$h{C1SQATI2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQATI2}}[3], ${$h{C1SQATI2}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQOBAP</FONT></TD>\n", ${$h{C1SQOBAP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQOBAP}}[3], ${$h{C1SQOBAP}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQBPO</FONT></TD>\n", ${$h{C2SQBPO}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQBPO}}[3], ${$h{C2SQBPO}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CM1CKBR1</FONT></TD>\n", ${$h{CM1CKBR1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CM1CKBR1}}[3], ${$h{CM1CKBR1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQATPP</FONT></TD>\n", ${$h{C1SQATPP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQATPP}}[3], ${$h{C1SQATPP}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQOBAR</FONT></TD>\n", ${$h{C1SQOBAR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQOBAR}}[3], ${$h{C1SQOBAR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQBPPP</FONT></TD>\n", ${$h{C2SQBPPP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQBPPP}}[3], ${$h{C2SQBPPP}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CM1CKBR2</FONT></TD>\n", ${$h{CM1CKBR2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CM1CKBR2}}[3], ${$h{CM1CKBR2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQATPS</FONT></TD>\n", ${$h{C1SQATPS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQATPS}}[3], ${$h{C1SQATPS}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQOBBP</FONT></TD>\n", ${$h{C1SQOBBP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQOBBP}}[3], ${$h{C1SQOBBP}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQBTI1</FONT></TD>\n", ${$h{C2SQBTI1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQBTI1}}[3], ${$h{C2SQBTI1}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CM2CKBP1</FONT></TD>\n", ${$h{CM2CKBP1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CM2CKBP1}}[3], ${$h{CM2CKBP1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQAX</FONT></TD>\n", ${$h{C1SQAX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQAX}}[3], ${$h{C1SQAX}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQOBBR</FONT></TD>\n", ${$h{C1SQOBBR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQOBBR}}[3], ${$h{C1SQOBBR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQBTI2</FONT></TD>\n", ${$h{C2SQBTI2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQBTI2}}[3], ${$h{C2SQBTI2}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CM2CKBP2</FONT></TD>\n", ${$h{CM2CKBP2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CM2CKBP2}}[3], ${$h{CM2CKBP2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQBPCT</FONT></TD>\n", ${$h{C1SQBPCT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQBPCT}}[3], ${$h{C1SQBPCT}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQPTLX</FONT></TD>\n", ${$h{C1SQPTLX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQPTLX}}[3], ${$h{C1SQPTLX}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQBTPP</FONT></TD>\n", ${$h{C2SQBTPP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQBTPP}}[3], ${$h{C2SQBTPP}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CM2CKBR1</FONT></TD>\n", ${$h{CM2CKBR1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CM2CKBR1}}[3], ${$h{CM2CKBR1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQBPIU</FONT></TD>\n", ${$h{C1SQBPIU}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQBPIU}}[3], ${$h{C1SQBPIU}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQRTLX</FONT></TD>\n", ${$h{C1SQRTLX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQRTLX}}[3], ${$h{C1SQRTLX}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQBTPS</FONT></TD>\n", ${$h{C2SQBTPS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQBTPS}}[3], ${$h{C2SQBTPS}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CM2CKBR2</FONT></TD>\n", ${$h{CM2CKBR2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CM2CKBR2}}[3], ${$h{CM2CKBR2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQBPO</FONT></TD>\n", ${$h{C1SQBPO}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQBPO}}[3], ${$h{C1SQBPO}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQAPCT</FONT></TD>\n", ${$h{C2SQAPCT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQAPCT}}[3], ${$h{C2SQAPCT}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQBX</FONT></TD>\n", ${$h{C2SQBX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQBX}}[3], ${$h{C2SQBX}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CM3CKBP1</FONT></TD>\n", ${$h{CM3CKBP1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CM3CKBP1}}[3], ${$h{CM3CKBP1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQBPPP</FONT></TD>\n", ${$h{C1SQBPPP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQBPPP}}[3], ${$h{C1SQBPPP}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQAPIU</FONT></TD>\n", ${$h{C2SQAPIU}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQAPIU}}[3], ${$h{C2SQAPIU}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQOBAP</FONT></TD>\n", ${$h{C2SQOBAP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQOBAP}}[3], ${$h{C2SQOBAP}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CM3CKBP2</FONT></TD>\n", ${$h{CM3CKBP2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CM3CKBP2}}[3], ${$h{CM3CKBP2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQBTI1</FONT></TD>\n", ${$h{C1SQBTI1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQBTI1}}[3], ${$h{C1SQBTI1}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQAPO</FONT></TD>\n", ${$h{C2SQAPO}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQAPO}}[3], ${$h{C2SQAPO}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CEIAPR</FONT></TD>\n", ${$h{CEIAPR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CEIAPR}}[3], ${$h{CEIAPR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CM3CKBR1</FONT></TD>\n", ${$h{CM3CKBR1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CM3CKBR1}}[3], ${$h{CM3CKBR1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C1SQBTI2</FONT></TD>\n", ${$h{C1SQBTI2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C1SQBTI2}}[3], ${$h{C1SQBTI2}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>C2SQAPPP</FONT></TD>\n", ${$h{C2SQAPPP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{C2SQAPPP}}[3], ${$h{C2SQAPPP}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CEIARD</FONT></TD>\n", ${$h{CEIARD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CEIARD}}[3], ${$h{CEIARD}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CM3CKBR2</FONT></TD>\n", ${$h{CM3CKBR2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CM3CKBR2}}[3], ${$h{CM3CKBR2}}[1];
#printf SF "</TABLE>\n";

printf SF "<TR>\n";
#printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>IU</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CCOACBFA</FONT></TD>\n", ${$h{CCOACBFA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CCOACBFA}}[3], ${$h{CCOACBFA}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUACBDL</FONT></TD>\n", ${$h{CIUACBDL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUACBDL}}[3], ${$h{CIUACBDL}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUBCAEX</FONT></TD>\n", ${$h{CIUBCAEX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUBCAEX}}[3], ${$h{CIUBCAEX}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUBCBSL</FONT></TD>\n", ${$h{CIUBCBSL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUBCBSL}}[3], ${$h{CIUBCBSL}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CCOACBFB</FONT></TD>\n", ${$h{CCOACBFB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CCOACBFB}}[3], ${$h{CCOACBFB}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUACBEX</FONT></TD>\n", ${$h{CIUACBEX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUACBEX}}[3], ${$h{CIUACBEX}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUBCAFL</FONT></TD>\n", ${$h{CIUBCAFL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUBCAFL}}[3], ${$h{CIUBCAFL}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUBEPDL</FONT></TD>\n", ${$h{CIUBEPDL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUBEPDL}}[3], ${$h{CIUBEPDL}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CCOBCBFB</FONT></TD>\n", ${$h{CCOBCBFB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CCOBCBFB}}[3], ${$h{CCOBCBFB}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUACBFL</FONT></TD>\n", ${$h{CIUACBFL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUACBFL}}[3], ${$h{CIUACBFL}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUBCAPA</FONT></TD>\n", ${$h{CIUBCAPA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUBCAPA}}[3], ${$h{CIUBCAPA}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUBPL1L</FONT></TD>\n", ${$h{CIUBPL1L}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUBPL1L}}[3], ${$h{CIUBPL1L}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CCOBCBFB</FONT></TD>\n", ${$h{CCOBCBFB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CCOBCBFB}}[3], ${$h{CCOBCBFB}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUACBPA</FONT></TD>\n", ${$h{CIUACBPA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUACBPA}}[3], ${$h{CIUACBPA}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUSB</FONT></TD>\n", ${$h{CIUSB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUSB}}[3], ${$h{CIUSB}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUBPL2L</FONT></TD>\n", ${$h{CIUBPL2L}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUBPL2L}}[3], ${$h{CIUBPL2L}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUACADL</FONT></TD>\n", ${$h{CIUACADL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUACADL}}[3], ${$h{CIUACADL}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUACBRH</FONT></TD>\n", ${$h{CIUACBRH}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUACBRH}}[3], ${$h{CIUACBRH}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUBCARH</FONT></TD>\n", ${$h{CIUBCARH}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUBCARH}}[3], ${$h{CIUBCARH}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUCALIN</FONT></TD>\n", ${$h{CIUCALIN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUCALIN}}[3], ${$h{CIUCALIN}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUACAEX</FONT></TD>\n", ${$h{CIUACAEX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUACAEX}}[3], ${$h{CIUACAEX}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUSA</FONT></TD>\n", ${$h{CIUSA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUSA}}[3], ${$h{CIUSA}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUBCASL</FONT></TD>\n", ${$h{CIUBCASL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUBCASL}}[3], ${$h{CIUBCASL}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUCBLIN</FONT></TD>\n", ${$h{CIUCBLIN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUCBLIN}}[3], ${$h{CIUCBLIN}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUACAFL</FONT></TD>\n", ${$h{CIUACAFL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUACAFL}}[3], ${$h{CIUACAFL}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUACBSL</FONT></TD>\n", ${$h{CIUACBSL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUACBSL}}[3], ${$h{CIUACBSL}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUBCBDL</FONT></TD>\n", ${$h{CIUBCBDL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUBCBDL}}[3], ${$h{CIUBCBDL}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUMACAC</FONT></TD>\n", ${$h{CIUMACAC}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUMACAC}}[3], ${$h{CIUMACAC}}[1];
#printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CNVLCD</FONT></TD>\n", ${$h{CNVLCD}}[3];
#printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CNVLCD}}[3], ${$h{CNVLCD}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUACAPA</FONT></TD>\n", ${$h{CIUACAPA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUACAPA}}[3], ${$h{CIUACAPA}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUAEPDL</FONT></TD>\n", ${$h{CIUAEPDL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUAEPDL}}[3], ${$h{CIUAEPDL}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUBCBEX</FONT></TD>\n", ${$h{CIUBCBEX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUBCBEX}}[3], ${$h{CIUBCBEX}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUMACAS</FONT></TD>\n", ${$h{CIUMACAS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUMACAS}}[3], ${$h{CIUMACAS}}[1];
#printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUACAPA</FONT></TD>\n", ${$h{CIUACAPA}}[3];
#printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUACAPA}}[3], ${$h{CIUACAPA}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUACARH</FONT></TD>\n", ${$h{CIUACARH}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUACARH}}[3], ${$h{CIUACARH}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUAPL1L</FONT></TD>\n", ${$h{CIUAPL1L}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUAPL1L}}[3], ${$h{CIUAPL1L}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUBCBFL</FONT></TD>\n", ${$h{CIUBCBFL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUBCBFL}}[3], ${$h{CIUBCBFL}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CCSDSVCD</FONT></TD>\n", ${$h{CCSDSVCD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%d</FONT></TD>\n", ${$h{CCSDSVCD}}[3], ${$h{CCSDSVCD}}[1];
#printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUACARH</FONT></TD>\n", ${$h{CIUACARH}}[3];
#printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUACARH}}[3], ${$h{CIUACARH}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUACASL</FONT></TD>\n", ${$h{CIUACASL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUACASL}}[3], ${$h{CIUACASL}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUAPL2L</FONT></TD>\n", ${$h{CIUAPL2L}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUAPL2L}}[3], ${$h{CIUAPL2L}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUBCBPA</FONT></TD>\n", ${$h{CIUBCBPA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUBCBPA}}[3], ${$h{CIUBCBPA}}[1];
#printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUACASL</FONT></TD>\n", ${$h{CIUACASL}}[3];
#printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUACASL}}[3], ${$h{CIUACASL}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUBCADL</FONT></TD>\n", ${$h{CIUBCADL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUBCADL}}[3], ${$h{CIUBCADL}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CIUBCBRH</FONT></TD>\n", ${$h{CIUBCBRH}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CIUBCBRH}}[3], ${$h{CIUBCBRH}}[1];
#printf SF "</TABLE>\n";

printf SF "<TR>\n";
#printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>OBC</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CCACKSUM</FONT></TD>\n", ${$h{CCACKSUM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CCACKSUM}}[3], ${$h{CCACKSUM}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CCBCKSUM</FONT></TD>\n", ${$h{CCBCKSUM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CCBCKSUM}}[3], ${$h{CCBCKSUM}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CCAONLIN</FONT></TD>\n", ${$h{CCAONLIN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CCAONLIN}}[3], ${$h{CCAONLIN}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CCBONLIN</FONT></TD>\n", ${$h{CCBONLIN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CCBONLIN}}[3], ${$h{CCBONLIN}}[1];
#printf SF "</TABLE>\n";

printf SF "<TR>\n";
#printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>PSU</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EHRCPPWR</FONT></TD>\n", ${$h{EHRCPPWR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EHRCPPWR}}[3], ${$h{EHRCPPWR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ERA1PPWR</FONT></TD>\n", ${$h{ERA1PPWR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ERA1PPWR}}[3], ${$h{ERA1PPWR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ERAIRTNS</FONT></TD>\n", ${$h{ERAIRTNS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ERAIRTNS}}[3], ${$h{ERAIRTNS}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ETX2IRCS</FONT></TD>\n", ${$h{ETX2IRCS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ETX2IRCS}}[3], ${$h{ETX2IRCS}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>EHRCRPWR</FONT></TD>\n", ${$h{EHRCRPWR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{EHRCRPWR}}[3], ${$h{EHRCRPWR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ERA2IRCS</FONT></TD>\n", ${$h{ERA2IRCS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ERA2IRCS}}[3], ${$h{ERA2IRCS}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ETX1IRCS</FONT></TD>\n", ${$h{ETX1IRCS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ETX1IRCS}}[3], ${$h{ETX1IRCS}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ETX2PPWR</FONT></TD>\n", ${$h{ETX2PPWR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ETX2PPWR}}[3], ${$h{ETX2PPWR}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ERA1IRCS</FONT></TD>\n", ${$h{ERA1IRCS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ERA1IRCS}}[3], ${$h{ERA1IRCS}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ERA2PPWR</FONT></TD>\n", ${$h{ERA2PPWR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ERA2PPWR}}[3], ${$h{ERA2PPWR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ETX1PPWR</FONT></TD>\n", ${$h{ETX1PPWR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ETX1PPWR}}[3], ${$h{ETX1PPWR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ETXIRTNS</FONT></TD>\n", ${$h{ETXIRTNS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ETXIRTNS}}[3], ${$h{ETXIRTNS}}[1];
#printf SF "</TABLE>\n";

printf SF "<TR>\n";
#printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>EP RCTU</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CEPTLMA</FONT></TD>\n", ${$h{CEPTLMA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CEPTLMA}}[3], ${$h{CEPTLMA}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CEPTLMB</FONT></TD>\n", ${$h{CEPTLMB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CEPTLMB}}[3], ${$h{CEPTLMB}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUEPA</FONT></TD>\n", ${$h{CTUEPA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CTUEPA}}[3], ${$h{CTUEPA}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUEPB</FONT></TD>\n", ${$h{CTUEPB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CTUEPB}}[3], ${$h{CTUEPB}}[1];
#printf SF "</TABLE>\n";

printf SF "<TR>\n";
#printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>PC RCTU</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CPCCMCTP</FONT></TD>\n", ${$h{CPCCMCTP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CPCCMCTP}}[3], ${$h{CPCCMCTP}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CPCOCLRD</FONT></TD>\n", ${$h{CPCOCLRD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CPCOCLRD}}[3], ${$h{CPCOCLRD}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CPCPERD</FONT></TD>\n", ${$h{CPCPERD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CPCPERD}}[3], ${$h{CPCPERD}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUPCA</FONT></TD>\n", ${$h{CTUPCA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CTUPCA}}[3], ${$h{CTUPCA}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CPCCMCTR</FONT></TD>\n", ${$h{CPCCMCTR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CPCCMCTR}}[3], ${$h{CPCCMCTR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CPCOCMPR</FONT></TD>\n", ${$h{CPCOCMPR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CPCOCMPR}}[3], ${$h{CPCOCMPR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CPCTLMA</FONT></TD>\n", ${$h{CPCTLMA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CPCTLMA}}[3], ${$h{CPCTLMA}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUPCB</FONT></TD>\n", ${$h{CTUPCB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CTUPCB}}[3], ${$h{CTUPCB}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CPCOCLPR</FONT></TD>\n", ${$h{CPCOCLPR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CPCOCLPR}}[3], ${$h{CPCOCLPR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CPCPEPR</FONT></TD>\n", ${$h{CPCPEPR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CPCPEPR}}[3], ${$h{CPCPEPR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CPCTLMB</FONT></TD>\n", ${$h{CPCTLMB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CPCTLMB}}[3], ${$h{CPCTLMB}}[1];
#printf SF "</TABLE>\n";

printf SF "<TR>\n";
#printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>SI RCTU</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSICMCTP</FONT></TD>\n", ${$h{CSICMCTP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CSICMCTP}}[3], ${$h{CSICMCTP}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSIOCLRD</FONT></TD>\n", ${$h{CSIOCLRD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CSIOCLRD}}[3], ${$h{CSIOCLRD}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSIPEPR</FONT></TD>\n", ${$h{CSIPEPR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CSIPEPR}}[3], ${$h{CSIPEPR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSITLMB</FONT></TD>\n", ${$h{CSITLMB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CSITLMB}}[3], ${$h{CSITLMB}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSICMCTR</FONT></TD>\n", ${$h{CSICMCTR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CSICMCTR}}[3], ${$h{CSICMCTR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSIOCMPR</FONT></TD>\n", ${$h{CSIOCMPR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CSIOCMPR}}[3], ${$h{CSIOCMPR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSIPERD</FONT></TD>\n", ${$h{CSIPERD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CSIPERD}}[3], ${$h{CSIPERD}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUSIA</FONT></TD>\n", ${$h{CTUSIA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CTUSIA}}[3], ${$h{CTUSIA}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSIOCLPR</FONT></TD>\n", ${$h{CSIOCLPR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CSIOCLPR}}[3], ${$h{CSIOCLPR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSIOCMRD</FONT></TD>\n", ${$h{CSIOCMRD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CSIOCMRD}}[3], ${$h{CSIOCMRD}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSITLMA</FONT></TD>\n", ${$h{CSITLMA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CSITLMA}}[3], ${$h{CSITLMA}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUSIB</FONT></TD>\n", ${$h{CTUSIB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CTUSIB}}[3], ${$h{CTUSIB}}[1];
#printf SF "</TABLE>\n";

printf SF "<TR>\n";
#printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>TS RCTU</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTSCMCTP</FONT></TD>\n", ${$h{CTSCMCTP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CTSCMCTP}}[3], ${$h{CTSCMCTP}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTSOCLRD</FONT></TD>\n", ${$h{CTSOCLRD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CTSOCLRD}}[3], ${$h{CTSOCLRD}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTSPEPR</FONT></TD>\n", ${$h{CTSPEPR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CTSPEPR}}[3], ${$h{CTSPEPR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTSTLMB</FONT></TD>\n", ${$h{CTSTLMB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CTSTLMB}}[3], ${$h{CTSTLMB}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTSCMCTR</FONT></TD>\n", ${$h{CTSCMCTR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CTSCMCTR}}[3], ${$h{CTSCMCTR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTSOCMPR</FONT></TD>\n", ${$h{CTSOCMPR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CTSOCMPR}}[3], ${$h{CTSOCMPR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTSPERD</FONT></TD>\n", ${$h{CTSPERD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CTSPERD}}[3], ${$h{CTSPERD}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUTSA</FONT></TD>\n", ${$h{CTUTSA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CTUTSA}}[3], ${$h{CTUTSA}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTSOCLPR</FONT></TD>\n", ${$h{CTSOCLPR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CTSOCLPR}}[3], ${$h{CTSOCLPR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTSOCMRD</FONT></TD>\n", ${$h{CTSOCMRD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CTSOCMRD}}[3], ${$h{CTSOCMRD}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTSTLMA</FONT></TD>\n", ${$h{CTSTLMA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CTSTLMA}}[3], ${$h{CTSTLMA}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTUTSB</FONT></TD>\n", ${$h{CTUTSB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CTUTSB}}[3], ${$h{CTUTSB}}[1];
#printf SF "</TABLE>\n";

printf SF "<TR>\n";
#printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>RF</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CPA1V</FONT></TD>\n", ${$h{CPA1V}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CPA1V}}[3], ${$h{CPA1V}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTXAPWR</FONT></TD>\n", ${$h{CTXAPWR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CTXAPWR}}[3], ${$h{CTXAPWR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CAUXCMDA</FONT></TD>\n", ${$h{CAUXCMDA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CAUXCMDA}}[3], ${$h{CAUXCMDA}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CRFMODE1</FONT></TD>\n", ${$h{CRFMODE1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CRFMODE1}}[3], ${$h{CRFMODE1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CPA2V</FONT></TD>\n", ${$h{CPA2V}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CPA2V}}[3], ${$h{CPA2V}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTXBPWR</FONT></TD>\n", ${$h{CTXBPWR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CTXBPWR}}[3], ${$h{CTXBPWR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CAUXCMDB</FONT></TD>\n", ${$h{CAUXCMDB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CAUXCMDB}}[3], ${$h{CAUXCMDB}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CRFMODE2</FONT></TD>\n", ${$h{CRFMODE2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CRFMODE2}}[3], ${$h{CRFMODE2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CPA1PWR</FONT></TD>\n", ${$h{CPA1PWR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CPA1PWR}}[3], ${$h{CPA1PWR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTXAV</FONT></TD>\n", ${$h{CTXAV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CTXAV}}[3], ${$h{CTXAV}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CCOHODRA</FONT></TD>\n", ${$h{CCOHODRA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CCOHODRA}}[3], ${$h{CCOHODRA}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CXPNAMOD</FONT></TD>\n", ${$h{CXPNAMOD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CXPNAMOD}}[3], ${$h{CXPNAMOD}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CPA2PWR</FONT></TD>\n", ${$h{CPA2PWR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CPA2PWR}}[3], ${$h{CPA2PWR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CTXBV</FONT></TD>\n", ${$h{CTXBV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CTXBV}}[3], ${$h{CTXBV}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CCOHODRB</FONT></TD>\n", ${$h{CCOHODRB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CCOHODRB}}[3], ${$h{CCOHODRB}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CXPNARNG</FONT></TD>\n", ${$h{CXPNARNG}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CXPNARNG}}[3], ${$h{CXPNARNG}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CRXAV</FONT></TD>\n", ${$h{CRXAV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CRXAV}}[3], ${$h{CRXAV}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CRXASIG</FONT></TD>\n", ${$h{CRXASIG}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CRXASIG}}[3], ${$h{CRXASIG}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CRDRVA</FONT></TD>\n", ${$h{CRDRVA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CRDRVA}}[3], ${$h{CRDRVA}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CXPNBMOD</FONT></TD>\n", ${$h{CXPNBMOD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CXPNBMOD}}[3], ${$h{CXPNBMOD}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CRXAV</FONT></TD>\n", ${$h{CRXAV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CRXAV}}[3], ${$h{CRXAV}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CRXBSIG</FONT></TD>\n", ${$h{CRXBSIG}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CRXBSIG}}[3], ${$h{CRXBSIG}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CRDRVB</FONT></TD>\n", ${$h{CRDRVB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CRDRVB}}[3], ${$h{CRDRVB}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CXPNBRNG</FONT></TD>\n", ${$h{CXPNBRNG}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CXPNBRNG}}[3], ${$h{CXPNBRNG}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CRXBV</FONT></TD>\n", ${$h{CRXBV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CRXBV}}[3], ${$h{CRXBV}}[1];
#printf SF "</TABLE>\n";

printf SF "<TR>\n";
#printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>SSR</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSSR1CVA</FONT></TD>\n", ${$h{CSSR1CVA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CSSR1CVA}}[3], ${$h{CSSR1CVA}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSAOPIP</FONT></TD>\n", ${$h{COSAOPIP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSAOPIP}}[3], ${$h{COSAOPIP}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSBPBEN</FONT></TD>\n", ${$h{COSBPBEN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSBPBEN}}[3], ${$h{COSBPBEN}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>OSSRACP1</FONT></TD>\n", ${$h{OSSRACP1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{OSSRACP1}}[3], ${$h{OSSRACP1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSSR1CVB</FONT></TD>\n", ${$h{CSSR1CVB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CSSR1CVB}}[3], ${$h{CSSR1CVB}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSAPORO</FONT></TD>\n", ${$h{COSAPORO}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSAPORO}}[3], ${$h{COSAPORO}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSBPBPR</FONT></TD>\n", ${$h{COSBPBPR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSBPBPR}}[3], ${$h{COSBPBPR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>OSSRACP2</FONT></TD>\n", ${$h{OSSRACP2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{OSSRACP2}}[3], ${$h{OSSRACP2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSSR2CVA</FONT></TD>\n", ${$h{CSSR2CVA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CSSR2CVA}}[3], ${$h{CSSR2CVA}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSAPROV</FONT></TD>\n", ${$h{COSAPROV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSAPROV}}[3], ${$h{COSAPROV}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSBPORO</FONT></TD>\n", ${$h{COSBPORO}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSBPORO}}[3], ${$h{COSBPORO}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>OSSRADIF</FONT></TD>\n", ${$h{OSSRADIF}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{OSSRADIF}}[3], ${$h{OSSRADIF}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSSR2CVB</FONT></TD>\n", ${$h{CSSR2CVB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{CSSR2CVB}}[3], ${$h{CSSR2CVB}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSARCIN</FONT></TD>\n", ${$h{COSARCIN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSARCIN}}[3], ${$h{COSARCIN}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSBPROV</FONT></TD>\n", ${$h{COSBPROV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSBPROV}}[3], ${$h{COSBPROV}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>OSSRADP1</FONT></TD>\n", ${$h{OSSRADP1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{OSSRADP1}}[3], ${$h{OSSRADP1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSSR1CAV</FONT></TD>\n", ${$h{CSSR1CAV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CSSR1CAV}}[3], ${$h{CSSR1CAV}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSARCRY</FONT></TD>\n", ${$h{COSARCRY}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSARCRY}}[3], ${$h{COSARCRY}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSBRCEN</FONT></TD>\n", ${$h{COSBRCEN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSBRCEN}}[3], ${$h{COSBRCEN}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>OSSRADP2</FONT></TD>\n", ${$h{OSSRADP2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{OSSRADP2}}[3], ${$h{OSSRADP2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>CSSR2CBV</FONT></TD>\n", ${$h{CSSR2CBV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{CSSR2CBV}}[3], ${$h{CSSR2CBV}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSASTTO</FONT></TD>\n", ${$h{COSASTTO}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSASTTO}}[3], ${$h{COSASTTO}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSBRCIN</FONT></TD>\n", ${$h{COSBRCIN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSBRCIN}}[3], ${$h{COSBRCIN}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>OSSRAIFS</FONT></TD>\n", ${$h{OSSRAIFS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{OSSRAIFS}}[3], ${$h{OSSRAIFS}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TCM_SSR1</FONT></TD>\n", ${$h{TCM_SSR1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{TCM_SSR1}}[3], ${$h{TCM_SSR1}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSBCMRS</FONT></TD>\n", ${$h{COSBCMRS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSBCMRS}}[3], ${$h{COSBCMRS}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSBRCPR</FONT></TD>\n", ${$h{COSBRCPR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSBRCPR}}[3], ${$h{COSBRCPR}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>OSSRBEDC</FONT></TD>\n", ${$h{OSSRBEDC}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{OSSRBEDC}}[3], ${$h{OSSRBEDC}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TCM_SSR2</FONT></TD>\n", ${$h{TCM_SSR2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{TCM_SSR2}}[3], ${$h{TCM_SSR2}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSBCMTO</FONT></TD>\n", ${$h{COSBCMTO}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSBCMTO}}[3], ${$h{COSBCMTO}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSBRCRY</FONT></TD>\n", ${$h{COSBRCRY}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSBRCRY}}[3], ${$h{COSBRCRY}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>OSSRBRPG</FONT></TD>\n", ${$h{OSSRBRPG}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{OSSRBRPG}}[3], ${$h{OSSRBRPG}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSACMRS</FONT></TD>\n", ${$h{COSACMRS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSACMRS}}[3], ${$h{COSACMRS}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSBLCMV</FONT></TD>\n", ${$h{COSBLCMV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSBLCMV}}[3], ${$h{COSBLCMV}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSBSTTO</FONT></TD>\n", ${$h{COSBSTTO}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSBSTTO}}[3], ${$h{COSBSTTO}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSACMTO</FONT></TD>\n", ${$h{COSACMTO}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSACMTO}}[3], ${$h{COSACMTO}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSBOPIP</FONT></TD>\n", ${$h{COSBOPIP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{COSBOPIP}}[3], ${$h{COSBOPIP}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>COSSR</FONT></TD>\n", ${$h{COSSR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{COSSR}}[3], ${$h{COSSR}}[1];
printf SF "</TABLE>\n";
printf SF "<BR>\n";
close SF;

print_links("$outfile");
print SF "</BODY></HTML>\n";
close SF;
# end
}
1;
