sub soh_format {
  $outfile = shift @_;
  %h = @_;

  print_head("$outfile","Mechanisms", %h);

open (SF, ">>$outfile");

printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD><TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=3><FONT SIZE=4>SIM</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA-A POWER ENABLE ON/OFF STATUS <br>  ON OFF', CAPTION, '3SEAPENA' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3SEAPENA</FONT></a></TD>\n", ${$h{"3SEAPENA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>SEA Power Enable Flag</FONT></TD>\n", ${$h{"3SEAPENA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SEAPENA"}}[3], ${$h{"3SEAPENA"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA-A POWER SUPPLY ON/OFF MONITOR <br>  OFF ON', CAPTION, '3SEAPSMA' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3SEAPSMA</FONT></a></TD>\n", ${$h{"3SEAPSMA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>SEA Power ON Flag</FONT></TD>\n", ${$h{"3SEAPSMA"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SEAPSMA"}}[3], ${$h{"3SEAPSMA"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('MOTOR BRAKE ENBL/DISBL A <br>  DISA ENAB', CAPTION, '3MTRAEN' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3MTRAEN</FONT></a></TD>\n", ${$h{"3MTRAEN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Motor/Brake Enable</FONT></TD>\n", ${$h{"3MTRAEN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3MTRAEN"}}[3], ${$h{"3MTRAEN"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA TLM UPDATE FLAG (TOGGLE W/EA UPDATE) <br>  0 1', CAPTION, '3SEATMUP' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3SEATMUP</FONT></a></TD>\n", ${$h{"3SEATMUP"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Heartbeat</FONT></TD>\n", ${$h{"3SEATMUP"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SEATMUP"}}[3], ${$h{"3SEATMUP"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA IDENTIFICATION <br>  A B', CAPTION, '3SEAID' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3SEAID</FONT></a></TD>\n", ${$h{"3SEAID"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>SEA ID</FONT></TD>\n", ${$h{"3SEAID"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SEAID"}}[3], ${$h{"3SEAID"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA TSC POSITION STEP<br><font color=#FFFF00>(-103951.0) 104445.0 </font><br><font color=#FF0000>(-104428.0) 104445.0</font>', CAPTION, '3TSCPOS' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3TSCPOS</FONT></a></TD>\n", ${$h{"3TSCPOS"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Translation Position</FONT></TD>\n", ${$h{"3TSCPOS"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%d</FONT></TD>\n", ${$h{"3TSCPOS"}}[3], ${$h{"3TSCPOS"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA FA POSITION STEP<br><font color=#FFFF00>(-11313.0) 6462.0 </font><br><font color=#FF0000>(-11580.0) 6462.0</font>', CAPTION, '3FAPOS' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3FAPOS</FONT></a></TD>\n", ${$h{"3FAPOS"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Focus Position</FONT></TD>\n", ${$h{"3FAPOS"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%d</FONT></TD>\n", ${$h{"3FAPOS"}}[3], ${$h{"3FAPOS"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA TSC IN MOTION FLAG <br>  STOP MOVE', CAPTION, '3TSCMOVE' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3TSCMOVE</FONT></a></TD>\n", ${$h{"3TSCMOVE"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TSC Moving Flag</FONT></TD>\n", ${$h{"3TSCMOVE"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3TSCMOVE"}}[3], ${$h{"3TSCMOVE"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA FA IN MOTION FLAG <br>  STOP MOVE', CAPTION, '3FAMOVE' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3FAMOVE</FONT></a></TD>\n", ${$h{"3FAMOVE"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>FA Moving Flag</FONT></TD>\n", ${$h{"3FAMOVE"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3FAMOVE"}}[3], ${$h{"3FAMOVE"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA INVALID COMMAND GROUP FLAG <br>  VALD NVAL', CAPTION, '3SEAINCM' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3SEAINCM</FONT></a></TD>\n", ${$h{"3SEAINCM"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Invalid Command Flag</FONT></TD>\n", ${$h{"3SEAINCM"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SEAINCM"}}[3], ${$h{"3SEAINCM"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA RESET FLAG <br>  RSET NORM', CAPTION, '3SEARSET' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3SEARSET</FONT></a></TD>\n", ${$h{"3SEARSET"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Reset Flag</FONT></TD>\n", ${$h{"3SEARSET"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SEARSET"}}[3], ${$h{"3SEARSET"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA PROM CHECKSUM FAIL FLAG <br>  NFAL FAIL', CAPTION, '3SEAROMF' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3SEAROMF</FONT></a></TD>\n", ${$h{"3SEAROMF"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ROM Fail Flag</FONT></TD>\n", ${$h{"3SEAROMF"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SEAROMF"}}[3], ${$h{"3SEAROMF"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA RAM FAILURE DETECTION FLAG <br>  NFAL FAIL', CAPTION, '3SEARAMF' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3SEARAMF</FONT></a></TD>\n", ${$h{"3SEARAMF"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>RAM Fail Flag</FONT></TD>\n", ${$h{"3SEARAMF"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SEARAMF"}}[3], ${$h{"3SEARAMF"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA MAX PWM LEVEL MOST RECENT MOVE <br><font color=#FFFF00>(-2.0) 11.0 </font><br><font color=#FF0000>(-3.0) 11.0</font>', CAPTION, '3MRMMXMV' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3MRMMXMV</FONT></a></TD>\n", ${$h{"3MRMMXMV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>MAX PWM Level</FONT></TD>\n", ${$h{"3MRMMXMV"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%d</FONT></TD>\n", ${$h{"3MRMMXMV"}}[3], ${$h{"3MRMMXMV"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA MOTOR DRIVE OVERCURRENT COUNTER CNTS<br><font color=#FFFF00>(-2.0) 10.0 </font><br><font color=#FF0000>(-3.0) 10.0</font>', CAPTION, '3SMOTOC' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3SMOTOC</FONT></a></TD>\n", ${$h{"3SMOTOC"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Motor Overcurrent Cntr</FONT></TD>\n", ${$h{"3SMOTOC"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%d</FONT></TD>\n", ${$h{"3SMOTOC"}}[3], ${$h{"3SMOTOC"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA MOTOR STALL COUNTER CNTS<br><font color=#FFFF00>(-2.0) 1.0 </font><br><font color=#FF0000>(-3.0) 1.0</font>', CAPTION, '3SMOTSTL' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3SMOTSTL</FONT></a></TD>\n", ${$h{"3SMOTSTL"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Motor Stall Cntr</FONT></TD>\n", ${$h{"3SMOTSTL"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%d</FONT></TD>\n", ${$h{"3SMOTSTL"}}[3], ${$h{"3SMOTSTL"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA MECHANISM FOR LAST DETECTED REFERENCE TAB <br>  TSC FA', CAPTION, '3LDRTMEK' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3LDRTMEK</FONT></a></TD>\n", ${$h{"3LDRTMEK"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Last Tab Detect Flag</FONT></TD>\n", ${$h{"3LDRTMEK"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3LDRTMEK"}}[3], ${$h{"3LDRTMEK"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA TAB NUMBER OF REFERENCE TAB LAST DETECTED <br>  0 1 2 3', CAPTION, '3LDRTNO' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3LDRTNO</FONT></a></TD>\n", ${$h{"3LDRTNO"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Last Tab Number</FONT></TD>\n", ${$h{"3LDRTNO"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3LDRTNO"}}[3], ${$h{"3LDRTNO"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA TAB2 AUTO POSITION UPDATE ENAB/DISA STATUS <br>  DISA ENAB', CAPTION, '3STAB2EN' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3STAB2EN</FONT></a></TD>\n", ${$h{"3STAB2EN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Tab 2 Auto-Update Enable</FONT></TD>\n", ${$h{"3STAB2EN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3STAB2EN"}}[3], ${$h{"3STAB2EN"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA LAST DETECTED REF TAB POSITION STEP<br><font color=#FFFF00>(-10.0) 250.0 </font><br><font color=#FF0000>(-25.0) 250.0</font>', CAPTION, '3LDRTPOS' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3LDRTPOS</FONT></a></TD>\n", ${$h{"3LDRTPOS"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Last Tab Update Value</FONT></TD>\n", ${$h{"3LDRTPOS"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%d</FONT></TD>\n", ${$h{"3LDRTPOS"}}[3], ${$h{"3LDRTPOS"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA MOTOR DRIVER POWER RELAY STATUS <br>  ON OFF', CAPTION, '3SMOTPEN' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3SMOTPEN</FONT></a></TD>\n", ${$h{"3SMOTPEN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Motor Power Flag</FONT></TD>\n", ${$h{"3SMOTPEN"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SMOTPEN"}}[3], ${$h{"3SMOTPEN"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA MOTOR SELECTION RELAY STATUS <br>  TSC FA', CAPTION, '3SMOTSEL' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3SMOTSEL</FONT></a></TD>\n", ${$h{"3SMOTSEL"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>Motor Select Flag</FONT></TD>\n", ${$h{"3SMOTSEL"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{"3SMOTSEL"}}[3], ${$h{"3SMOTSEL"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA A TRANSLATION DRIVE MOTOR TEMP DEGC<br><font color=#FFFF00>(-30) 45.0 </font><br><font color=#FF0000>(-48.0) 45.0</font>', CAPTION, '3TRMTRAT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3TRMTRAT</FONT></a></TD>\n", ${$h{"3TRMTRAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>TSC Motor Temp</FONT></TD>\n", ${$h{"3TRMTRAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3TRMTRAT"}}[3], ${$h{"3TRMTRAT"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA-A FOCUS DRIVE MOTOR TEMP DEGC<br><font color=#FFFF00>(-20) 20 </font><br><font color=#FF0000>(-48.0) 20</font>', CAPTION, '3FAMTRAT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3FAMTRAT</FONT></a></TD>\n", ${$h{"3FAMTRAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>FA Motor Temp</FONT></TD>\n", ${$h{"3FAMTRAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3FAMTRAT"}}[3], ${$h{"3FAMTRAT"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA A POWER SUPPLY TEMP DEGC<br><font color=#FFFF00>(-20) 60 </font><br><font color=#FF0000>(-39.5) 60</font>', CAPTION, '3FAPSAT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3FAPSAT</FONT></a></TD>\n", ${$h{"3FAPSAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>SEA PS Temp</FONT></TD>\n", ${$h{"3FAPSAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3FAPSAT"}}[3], ${$h{"3FAPSAT"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA-A BOX TEMP DEGC<br><font color=#FFFF00>(-20) 30.0 </font><br><font color=#FF0000>(-39.5) 30.0</font>', CAPTION, '3FASEAAT' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>3FASEAAT</FONT></a></TD>\n", ${$h{"3FASEAAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>SEA Box Temp</FONT></TD>\n", ${$h{"3FASEAAT"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"3FASEAAT"}}[3], ${$h{"3FASEAAT"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 1: +5 VOLT MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4SP51V' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4SP51V</FONT></a></TD>\n", ${$h{"4SP51V"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>SEA 1: +5V Monitor</FONT></TD>\n", ${$h{"4SP51V"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4SP51V"}}[3], ${$h{"4SP51V"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('SEA 2: +5 VOLT MONITOR VDC<br><font color=#FFFF00>(-1099.0) 1099.0 </font><br><font color=#FF0000>(-1100.0) 1099.0</font>', CAPTION, '4SP52V' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4SP52V</FONT></a></TD>\n", ${$h{"4SP52V"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>SEA 2: +5V Monitor</FONT></TD>\n", ${$h{"4SP52V"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4SP52V"}}[3], ${$h{"4SP52V"}}[1];
printf SF "</TABLE>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD><TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=CENTER COLSPAN=2><FONT SIZE=4>OTG</FONT></TR>";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('HETG ROTATION ANGLE POSITION MONITOR A DEG<br>limits', CAPTION, '4HPOSARO' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4HPOSARO</FONT></a></TD>\n", ${$h{"4HPOSARO"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4HPOSARO"}}[3], ${$h{"4HPOSARO"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('HETG ROTATION ANGLE POSITION MONITOR B DEG<br>limits', CAPTION, '4HPOSBRO' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4HPOSBRO</FONT></a></TD>\n", ${$h{"4HPOSBRO"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4HPOSBRO"}}[3], ${$h{"4HPOSBRO"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('LETG ROTATION ANGLE POSITION MONITOR A DEG<br>limits', CAPTION, '4LPOSARO' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4LPOSARO</FONT></a></TD>\n", ${$h{"4LPOSARO"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4LPOSARO"}}[3], ${$h{"4LPOSARO"}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('LETG ROTATION ANGLE POSITION MONITOR B DEG<br>limits', CAPTION, '4LPOSBRO' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>4LPOSBRO</FONT></a></TD>\n", ${$h{"4LPOSBRO"}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{"4LPOSBRO"}}[3], ${$h{"4LPOSBRO"}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TR>\n";
printf SF "</TABLE>\n";
printf SF "</TABLE>\n";
printf SF "<BR>\n";
close SF;

print_links("$outfile");
open (SF,">>$outfile");
print SF "</BODY></HTML>\n";
close SF;
# end
}
1;
