sub soh_format {
  $outfile = shift @_;
  %h = @_;
  print_head("$outfile","PCAD", %h);

open (SF, ">>$outfile");

printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>ACA</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AACA1CAL</FONT></TD>\n", ${$h{AACA1CAL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AACA1CAL}}[3], ${$h{AACA1CAL}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AARAMF</FONT></TD>\n", ${$h{AARAMF}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AARAMF}}[3], ${$h{AARAMF}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOACCALF</FONT></TD>\n", ${$h{AOACCALF}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOACCALF}}[3], ${$h{AOACCALF}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>APEA1X</FONT></TD>\n", ${$h{APEA1X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{APEA1X}}[3], ${$h{APEA1X}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AACA1PWR</FONT></TD>\n", ${$h{AACA1PWR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AACA1PWR}}[3], ${$h{AACA1PWR}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AARESTF</FONT></TD>\n", ${$h{AARESTF}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AARESTF}}[3], ${$h{AARESTF}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOACPWRF</FONT></TD>\n", ${$h{AOACPWRF}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOACPWRF}}[3], ${$h{AOACPWRF}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>APEA2X</FONT></TD>\n", ${$h{APEA2X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{APEA2X}}[3], ${$h{APEA2X}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AACA2CAL</FONT></TD>\n", ${$h{AACA2CAL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AACA2CAL}}[3], ${$h{AACA2CAL}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AAROMF</FONT></TD>\n", ${$h{AAROMF}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AAROMF}}[3], ${$h{AAROMF}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOACRAMF</FONT></TD>\n", ${$h{AOACRAMF}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOACRAMF}}[3], ${$h{AOACRAMF}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOFWIND0</FONT></TD>\n", ${$h{AOFWIND0}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOFWIND0}}[3], ${$h{AOFWIND0}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AACA2PWR</FONT></TD>\n", ${$h{AACA2PWR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AACA2PWR}}[3], ${$h{AACA2PWR}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AASNERF</FONT></TD>\n", ${$h{AASNERF}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AASNERF}}[3], ${$h{AASNERF}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOACROMF</FONT></TD>\n", ${$h{AOACROMF}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOACROMF}}[3], ${$h{AOACROMF}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOFWIND1</FONT></TD>\n", ${$h{AOFWIND1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOFWIND1}}[3], ${$h{AOFWIND1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AACALF</FONT></TD>\n", ${$h{AACALF}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AACALF}}[3], ${$h{AACALF}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AAUPXSF</FONT></TD>\n", ${$h{AAUPXSF}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AAUPXSF}}[3], ${$h{AAUPXSF}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOACRSET</FONT></TD>\n", ${$h{AOACRSET}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOACRSET}}[3], ${$h{AOACRSET}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOFWIND2</FONT></TD>\n", ${$h{AOFWIND2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOFWIND2}}[3], ${$h{AOFWIND2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AACH1T</FONT></TD>\n", ${$h{AACH1T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AACH1T}}[3], ${$h{AACH1T}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOBRTSUC</FONT></TD>\n", ${$h{AOBRTSUC}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOBRTSUC}}[3], ${$h{AOBRTSUC}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOACSNTX</FONT></TD>\n", ${$h{AOACSNTX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOACSNTX}}[3], ${$h{AOACSNTX}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOFWIND3</FONT></TD>\n", ${$h{AOFWIND3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOFWIND3}}[3], ${$h{AOFWIND3}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AACH2T</FONT></TD>\n", ${$h{AACH2T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AACH2T}}[3], ${$h{AACH2T}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOFREACQ</FONT></TD>\n", ${$h{AOFREACQ}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOFREACQ}}[3], ${$h{AOFREACQ}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOACSTAT</FONT></TD>\n", ${$h{AOACSTAT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOACSTAT}}[3], ${$h{AOACSTAT}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOFWIND4</FONT></TD>\n", ${$h{AOFWIND4}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOFWIND4}}[3], ${$h{AOFWIND4}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AAPEA1DP</FONT></TD>\n", ${$h{AAPEA1DP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AAPEA1DP}}[3], ${$h{AAPEA1DP}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOACHIBK</FONT></TD>\n", ${$h{AOACHIBK}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOACHIBK}}[3], ${$h{AOACHIBK}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOACSUMF</FONT></TD>\n", ${$h{AOACSUMF}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOACSUMF}}[3], ${$h{AOACSUMF}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOFWIND5</FONT></TD>\n", ${$h{AOFWIND5}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOFWIND5}}[3], ${$h{AOFWIND5}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AAPEA2DP</FONT></TD>\n", ${$h{AAPEA2DP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AAPEA2DP}}[3], ${$h{AAPEA2DP}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOACINTT</FONT></TD>\n", ${$h{AOACINTT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOACINTT}}[3], ${$h{AOACINTT}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOGUIDSL</FONT></TD>\n", ${$h{AOGUIDSL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOGUIDSL}}[3], ${$h{AOGUIDSL}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOFWIND6</FONT></TD>\n", ${$h{AOFWIND6}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOFWIND6}}[3], ${$h{AOFWIND6}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AAPSF</FONT></TD>\n", ${$h{AAPSF}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AAPSF}}[3], ${$h{AAPSF}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOABERRN</FONT></TD>\n", ${$h{AOABERRN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOABERRN}}[3], ${$h{AOABERRN}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPEASEL</FONT></TD>\n", ${$h{AOPEASEL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPEASEL}}[3], ${$h{AOPEASEL}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOFWIND7</FONT></TD>\n", ${$h{AOFWIND7}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOFWIND7}}[3], ${$h{AOFWIND7}}[1];
printf SF "</TABLE>\n";
printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>CPE</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ACPA5CV</FONT></TD>\n", ${$h{ACPA5CV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{ACPA5CV}}[3], ${$h{ACPA5CV}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ACPEA1X</FONT></TD>\n", ${$h{ACPEA1X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ACPEA1X}}[3], ${$h{ACPEA1X}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOCPESTC</FONT></TD>\n", ${$h{AOCPESTC}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%d</FONT></TD>\n", ${$h{AOCPESTC}}[3], ${$h{AOCPESTC}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ACPB5CV</FONT></TD>\n", ${$h{ACPB5CV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{ACPB5CV}}[3], ${$h{ACPB5CV}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ACPEA2X</FONT></TD>\n", ${$h{ACPEA2X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ACPEA2X}}[3], ${$h{ACPEA2X}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOCPESTL</FONT></TD>\n", ${$h{AOCPESTL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOCPESTL}}[3], ${$h{AOCPESTL}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ACPEA</FONT></TD>\n", ${$h{ACPEA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ACPEA}}[3], ${$h{ACPEA}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ACPEB1X</FONT></TD>\n", ${$h{ACPEB1X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ACPEB1X}}[3], ${$h{ACPEB1X}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOCPESTO</FONT></TD>\n", ${$h{AOCPESTO}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOCPESTO}}[3], ${$h{AOCPESTO}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ACPEB</FONT></TD>\n", ${$h{ACPEB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ACPEB}}[3], ${$h{ACPEB}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ACPEB2X</FONT></TD>\n", ${$h{ACPEB2X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ACPEB2X}}[3], ${$h{ACPEB2X}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOCPESTQ</FONT></TD>\n", ${$h{AOCPESTQ}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOCPESTQ}}[3], ${$h{AOCPESTQ}}[1];
printf SF "</TABLE>\n";
printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>ADE</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ADE1P5CV</FONT></TD>\n", ${$h{ADE1P5CV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{ADE1P5CV}}[3], ${$h{ADE1P5CV}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ADEAPWR</FONT></TD>\n", ${$h{ADEAPWR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ADEAPWR}}[3], ${$h{ADEAPWR}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ADEBPWR</FONT></TD>\n", ${$h{ADEBPWR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ADEBPWR}}[3], ${$h{ADEBPWR}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOADESEL</FONT></TD>\n", ${$h{AOADESEL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOADESEL}}[3], ${$h{AOADESEL}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ADE2P5CV</FONT></TD>\n", ${$h{ADE2P5CV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{ADE2P5CV}}[3], ${$h{ADE2P5CV}}[1];
printf SF "</TABLE>\n";
printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>FLCA</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AFLCAAH</FONT></TD>\n", ${$h{AFLCAAH}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AFLCAAH}}[3], ${$h{AFLCAAH}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AFLCAAX</FONT></TD>\n", ${$h{AFLCAAX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AFLCAAX}}[3], ${$h{AFLCAAX}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AFLCABH</FONT></TD>\n", ${$h{AFLCABH}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AFLCABH}}[3], ${$h{AFLCABH}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AFLCABX</FONT></TD>\n", ${$h{AFLCABX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AFLCABX}}[3], ${$h{AFLCABX}}[1];
printf SF "</TABLE>\n";
printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>FSSA</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AFSSAA</FONT></TD>\n", ${$h{AFSSAA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AFSSAA}}[3], ${$h{AFSSAA}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AFSSBFLG</FONT></TD>\n", ${$h{AFSSBFLG}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AFSSBFLG}}[3], ${$h{AFSSBFLG}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSUNAC1</FONT></TD>\n", ${$h{AOSUNAC1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOSUNAC1}}[3], ${$h{AOSUNAC1}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOFSSOK</FONT></TD>\n", ${$h{AOFSSOK}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOFSSOK}}[3], ${$h{AOFSSOK}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AFSSAB</FONT></TD>\n", ${$h{AFSSAB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AFSSAB}}[3], ${$h{AFSSAB}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AFSSPC1V</FONT></TD>\n", ${$h{AFSSPC1V}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AFSSPC1V}}[3], ${$h{AFSSPC1V}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSUNAC2</FONT></TD>\n", ${$h{AOSUNAC2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOSUNAC2}}[3], ${$h{AOSUNAC2}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOFSSSEL</FONT></TD>\n", ${$h{AOFSSSEL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOFSSSEL}}[3], ${$h{AOFSSSEL}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AFSSAFLG</FONT></TD>\n", ${$h{AFSSAFLG}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AFSSAFLG}}[3], ${$h{AFSSAFLG}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AFSSPC2V</FONT></TD>\n", ${$h{AFSSPC2V}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AFSSPC2V}}[3], ${$h{AFSSPC2V}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSUNAC3</FONT></TD>\n", ${$h{AOSUNAC3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOSUNAC3}}[3], ${$h{AOSUNAC3}}[1];
printf SF "</TABLE>\n";
printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>IRU</FONT><TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AG1SELA</FONT></TD>\n", ${$h{AG1SELA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AG1SELA}}[3], ${$h{AG1SELA}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AI1AX2X</FONT></TD>\n", ${$h{AI1AX2X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AI1AX2X}}[3], ${$h{AI1AX2X}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1R1X</FONT></TD>\n", ${$h{AIRU1R1X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AIRU1R1X}}[3], ${$h{AIRU1R1X}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2R1X</FONT></TD>\n", ${$h{AIRU2R1X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AIRU2R1X}}[3], ${$h{AIRU2R1X}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AG1SELB</FONT></TD>\n", ${$h{AG1SELB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AG1SELB}}[3], ${$h{AG1SELB}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AI1AX2Y</FONT></TD>\n", ${$h{AI1AX2Y}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AI1AX2Y}}[3], ${$h{AI1AX2Y}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1R1Y</FONT></TD>\n", ${$h{AIRU1R1Y}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AIRU1R1Y}}[3], ${$h{AIRU1R1Y}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2R1Y</FONT></TD>\n", ${$h{AIRU2R1Y}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AIRU2R1Y}}[3], ${$h{AIRU2R1Y}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AG2SELA</FONT></TD>\n", ${$h{AG2SELA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AG2SELA}}[3], ${$h{AG2SELA}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AI2AX1X</FONT></TD>\n", ${$h{AI2AX1X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AI2AX1X}}[3], ${$h{AI2AX1X}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1R2X</FONT></TD>\n", ${$h{AIRU1R2X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AIRU1R2X}}[3], ${$h{AIRU1R2X}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2R2X</FONT></TD>\n", ${$h{AIRU2R2X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AIRU2R2X}}[3], ${$h{AIRU2R2X}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AG2SELB</FONT></TD>\n", ${$h{AG2SELB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AG2SELB}}[3], ${$h{AG2SELB}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AI2AX1Y</FONT></TD>\n", ${$h{AI2AX1Y}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AI2AX1Y}}[3], ${$h{AI2AX1Y}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1R2Y</FONT></TD>\n", ${$h{AIRU1R2Y}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AIRU1R2Y}}[3], ${$h{AIRU1R2Y}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2R2Y</FONT></TD>\n", ${$h{AIRU2R2Y}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AIRU2R2Y}}[3], ${$h{AIRU2R2Y}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AG3SELA</FONT></TD>\n", ${$h{AG3SELA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AG3SELA}}[3], ${$h{AG3SELA}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AI2AX2X</FONT></TD>\n", ${$h{AI2AX2X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AI2AX2X}}[3], ${$h{AI2AX2X}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1VFT</FONT></TD>\n", ${$h{AIRU1VFT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AIRU1VFT}}[3], ${$h{AIRU1VFT}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2VFT</FONT></TD>\n", ${$h{AIRU2VFT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AIRU2VFT}}[3], ${$h{AIRU2VFT}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AG3SELB</FONT></TD>\n", ${$h{AG3SELB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AG3SELB}}[3], ${$h{AG3SELB}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AI2AX2Y</FONT></TD>\n", ${$h{AI2AX2Y}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AI2AX2Y}}[3], ${$h{AI2AX2Y}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2</FONT></TD>\n", ${$h{AIRU2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AIRU2}}[3], ${$h{AIRU2}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOGYRSEL</FONT></TD>\n", ${$h{AOGYRSEL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOGYRSEL}}[3], ${$h{AOGYRSEL}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AG4SELA</FONT></TD>\n", ${$h{AG4SELA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AG4SELA}}[3], ${$h{AG4SELA}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1</FONT></TD>\n", ${$h{AIRU1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AIRU1}}[3], ${$h{AIRU1}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2BT</FONT></TD>\n", ${$h{AIRU2BT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AIRU2BT}}[3], ${$h{AIRU2BT}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOIRUHLD</FONT></TD>\n", ${$h{AOIRUHLD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIRUHLD}}[3], ${$h{AOIRUHLD}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AG4SELB</FONT></TD>\n", ${$h{AG4SELB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AG4SELB}}[3], ${$h{AG4SELB}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1BT</FONT></TD>\n", ${$h{AIRU1BT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AIRU1BT}}[3], ${$h{AIRU1BT}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2G1I</FONT></TD>\n", ${$h{AIRU2G1I}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AIRU2G1I}}[3], ${$h{AIRU2G1I}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOIRURT1</FONT></TD>\n", ${$h{AOIRURT1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIRURT1}}[3], ${$h{AOIRURT1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AGWS1V</FONT></TD>\n", ${$h{AGWS1V}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AGWS1V}}[3], ${$h{AGWS1V}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1G1I</FONT></TD>\n", ${$h{AIRU1G1I}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AIRU1G1I}}[3], ${$h{AIRU1G1I}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2G1T</FONT></TD>\n", ${$h{AIRU2G1T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AIRU2G1T}}[3], ${$h{AIRU2G1T}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOIRURT2</FONT></TD>\n", ${$h{AOIRURT2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIRURT2}}[3], ${$h{AOIRURT2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AGWS2V</FONT></TD>\n", ${$h{AGWS2V}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AGWS2V}}[3], ${$h{AGWS2V}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1G1T</FONT></TD>\n", ${$h{AIRU1G1T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AIRU1G1T}}[3], ${$h{AIRU1G1T}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2G2I</FONT></TD>\n", ${$h{AIRU2G2I}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AIRU2G2I}}[3], ${$h{AIRU2G2I}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOIRURT3</FONT></TD>\n", ${$h{AOIRURT3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIRURT3}}[3], ${$h{AOIRURT3}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AI1AX1X</FONT></TD>\n", ${$h{AI1AX1X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AI1AX1X}}[3], ${$h{AI1AX1X}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1G2I</FONT></TD>\n", ${$h{AIRU1G2I}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AIRU1G2I}}[3], ${$h{AIRU1G2I}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU2G2T</FONT></TD>\n", ${$h{AIRU2G2T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AIRU2G2T}}[3], ${$h{AIRU2G2T}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOIRURT4</FONT></TD>\n", ${$h{AOIRURT4}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOIRURT4}}[3], ${$h{AOIRURT4}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AI1AX1Y</FONT></TD>\n", ${$h{AI1AX1Y}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AI1AX1Y}}[3], ${$h{AI1AX1Y}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIRU1G2T</FONT></TD>\n", ${$h{AIRU1G2T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AIRU1G2T}}[3], ${$h{AIRU1G2T}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOGBIAS1</FONT></TD>\n", ${$h{AOGBIAS1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOGBIAS1}}[3], ${$h{AOGBIAS1}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOGBIAS2</FONT></TD>\n", ${$h{AOGBIAS2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOGBIAS2}}[3], ${$h{AOGBIAS2}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOGBIAS3</FONT></TD>\n", ${$h{AOGBIAS3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOGBIAS3}}[3], ${$h{AOGBIAS3}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "</TABLE>\n";
printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>IOE</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIOAP5CV</FONT></TD>\n", ${$h{AIOAP5CV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AIOAP5CV}}[3], ${$h{AIOAP5CV}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIOEA</FONT></TD>\n", ${$h{AIOEA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AIOEA}}[3], ${$h{AIOEA}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIOESWD3</FONT></TD>\n", ${$h{AIOESWD3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AIOESWD3}}[3], ${$h{AIOESWD3}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIOBP5CV</FONT></TD>\n", ${$h{AIOBP5CV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AIOBP5CV}}[3], ${$h{AIOBP5CV}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIOEB</FONT></TD>\n", ${$h{AIOEB}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AIOEB}}[3], ${$h{AIOEB}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AIOESWD4</FONT></TD>\n", ${$h{AIOESWD4}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AIOESWD4}}[3], ${$h{AIOESWD4}}[1];
printf SF "</TABLE>\n";
printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>ATTITUDE</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOALPSUN</FONT></TD>\n", ${$h{AOALPSUN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOALPSUN}}[3], ${$h{AOALPSUN}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOCINTNM</FONT></TD>\n", ${$h{AOCINTNM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOCINTNM}}[3], ${$h{AOCINTNM}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOCMDRT1</FONT></TD>\n", ${$h{AOCMDRT1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOCMDRT1}}[3], ${$h{AOCMDRT1}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOMVRINH</FONT></TD>\n", ${$h{AOMVRINH}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOMVRINH}}[3], ${$h{AOMVRINH}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOATTER1</FONT></TD>\n", ${$h{AOATTER1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOATTER1}}[3], ${$h{AOATTER1}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOCINTNP</FONT></TD>\n", ${$h{AOCINTNP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOCINTNP}}[3], ${$h{AOCINTNP}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOCMDRT2</FONT></TD>\n", ${$h{AOCMDRT2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOCMDRT2}}[3], ${$h{AOCMDRT2}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORATE1</FONT></TD>\n", ${$h{AORATE1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AORATE1}}[3], ${$h{AORATE1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOATTER2</FONT></TD>\n", ${$h{AOATTER2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOATTER2}}[3], ${$h{AOATTER2}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOCINTRM</FONT></TD>\n", ${$h{AOCINTRM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOCINTRM}}[3], ${$h{AOCINTRM}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOCMDRT3</FONT></TD>\n", ${$h{AOCMDRT3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOCMDRT3}}[3], ${$h{AOCMDRT3}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORATE2</FONT></TD>\n", ${$h{AORATE2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AORATE2}}[3], ${$h{AORATE2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOATTER3</FONT></TD>\n", ${$h{AOATTER3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOATTER3}}[3], ${$h{AOATTER3}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOCINTSA</FONT></TD>\n", ${$h{AOCINTSA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOCINTSA}}[3], ${$h{AOCINTSA}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AODITHEN</FONT></TD>\n", ${$h{AODITHEN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AODITHEN}}[3], ${$h{AODITHEN}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORATE3</FONT></TD>\n", ${$h{AORATE3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AORATE3}}[3], ${$h{AORATE3}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOATUPST</FONT></TD>\n", ${$h{AOATUPST}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOATUPST}}[3], ${$h{AOATUPST}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOCINTSP</FONT></TD>\n", ${$h{AOCINTSP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOCINTSP}}[3], ${$h{AOCINTSP}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AODITHR1</FONT></TD>\n", ${$h{AODITHR1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AODITHR1}}[3], ${$h{AODITHR1}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSUNER1</FONT></TD>\n", ${$h{AOSUNER1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOSUNER1}}[3], ${$h{AOSUNER1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOAUTTXN</FONT></TD>\n", ${$h{AOAUTTXN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOAUTTXN}}[3], ${$h{AOAUTTXN}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOCMDAC1</FONT></TD>\n", ${$h{AOCMDAC1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOCMDAC1}}[3], ${$h{AOCMDAC1}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AODITHR2</FONT></TD>\n", ${$h{AODITHR2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AODITHR2}}[3], ${$h{AODITHR2}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSUNER2</FONT></TD>\n", ${$h{AOSUNER2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOSUNER2}}[3], ${$h{AOSUNER2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOBETSUN</FONT></TD>\n", ${$h{AOBETSUN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOBETSUN}}[3], ${$h{AOBETSUN}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOCMDAC2</FONT></TD>\n", ${$h{AOCMDAC2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOCMDAC2}}[3], ${$h{AOCMDAC2}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AODITHR3</FONT></TD>\n", ${$h{AODITHR3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AODITHR3}}[3], ${$h{AODITHR3}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSUNER3</FONT></TD>\n", ${$h{AOSUNER3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOSUNER3}}[3], ${$h{AOSUNER3}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOCINTAH</FONT></TD>\n", ${$h{AOCINTAH}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOCINTAH}}[3], ${$h{AOCINTAH}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOCMDAC3</FONT></TD>\n", ${$h{AOCMDAC3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOCMDAC3}}[3], ${$h{AOCMDAC3}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOFGRAVG</FONT></TD>\n", ${$h{AOFGRAVG}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOFGRAVG}}[3], ${$h{AOFGRAVG}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSUNPRS</FONT></TD>\n", ${$h{AOSUNPRS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOSUNPRS}}[3], ${$h{AOSUNPRS}}[1];
printf SF "</TABLE>\n";
printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>MOMENTUM</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOFTHRST</FONT></TD>\n", ${$h{AOFTHRST}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOFTHRST}}[3], ${$h{AOFTHRST}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSYMOM1</FONT></TD>\n", ${$h{AOSYMOM1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOSYMOM1}}[3], ${$h{AOSYMOM1}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOTHRST1</FONT></TD>\n", ${$h{AOTHRST1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOTHRST1}}[3], ${$h{AOTHRST1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOFUNLST</FONT></TD>\n", ${$h{AOFUNLST}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOFUNLST}}[3], ${$h{AOFUNLST}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSYMOM2</FONT></TD>\n", ${$h{AOSYMOM2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOSYMOM2}}[3], ${$h{AOSYMOM2}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOTHRST2</FONT></TD>\n", ${$h{AOTHRST2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOTHRST2}}[3], ${$h{AOTHRST2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOMUPDEN</FONT></TD>\n", ${$h{AOMUPDEN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOMUPDEN}}[3], ${$h{AOMUPDEN}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSYMOM3</FONT></TD>\n", ${$h{AOSYMOM3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOSYMOM3}}[3], ${$h{AOSYMOM3}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOTHRST3</FONT></TD>\n", ${$h{AOTHRST3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOTHRST3}}[3], ${$h{AOTHRST3}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n";
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOTHRST4</FONT></TD>\n", ${$h{AOTHRST4}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOTHRST4}}[3], ${$h{AOTHRST4}}[1];
printf SF "</TABLE>\n";
printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>RWA</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWEN1</FONT></TD>\n", ${$h{AORWEN1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AORWEN1}}[3], ${$h{AORWEN1}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AWD1CV5V</FONT></TD>\n", ${$h{AWD1CV5V}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AWD1CV5V}}[3], ${$h{AWD1CV5V}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ARWA1BT</FONT></TD>\n", ${$h{ARWA1BT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{ARWA1BT}}[3], ${$h{ARWA1BT}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ARWA1PH1</FONT></TD>\n", ${$h{ARWA1PH1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ARWA1PH1}}[3], ${$h{ARWA1PH1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWEN2</FONT></TD>\n", ${$h{AORWEN2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AORWEN2}}[3], ${$h{AORWEN2}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AWD1TQI</FONT></TD>\n", ${$h{AWD1TQI}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AWD1TQI}}[3], ${$h{AWD1TQI}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ARWA2BT</FONT></TD>\n", ${$h{ARWA2BT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{ARWA2BT}}[3], ${$h{ARWA2BT}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ARWA1PH2</FONT></TD>\n", ${$h{ARWA1PH2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ARWA1PH2}}[3], ${$h{ARWA1PH2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWEN3</FONT></TD>\n", ${$h{AORWEN3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AORWEN3}}[3], ${$h{AORWEN3}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AWD2CV5V</FONT></TD>\n", ${$h{AWD2CV5V}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AWD2CV5V}}[3], ${$h{AWD2CV5V}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ARWA3BT</FONT></TD>\n", ${$h{ARWA3BT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{ARWA3BT}}[3], ${$h{ARWA3BT}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ARWA1RH1</FONT></TD>\n", ${$h{ARWA1RH1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ARWA1RH1}}[3], ${$h{ARWA1RH1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWEN4</FONT></TD>\n", ${$h{AORWEN4}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AORWEN4}}[3], ${$h{AORWEN4}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AWD2TQI</FONT></TD>\n", ${$h{AWD2TQI}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AWD2TQI}}[3], ${$h{AWD2TQI}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ARWA4BT</FONT></TD>\n", ${$h{ARWA4BT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{ARWA4BT}}[3], ${$h{ARWA4BT}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ARWA1RH2</FONT></TD>\n", ${$h{ARWA1RH2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ARWA1RH2}}[3], ${$h{ARWA1RH2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWEN5</FONT></TD>\n", ${$h{AORWEN5}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AORWEN5}}[3], ${$h{AORWEN5}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AWD3CV5V</FONT></TD>\n", ${$h{AWD3CV5V}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AWD3CV5V}}[3], ${$h{AWD3CV5V}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ARWA5BT</FONT></TD>\n", ${$h{ARWA5BT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{ARWA5BT}}[3], ${$h{ARWA5BT}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ARWA4PH1</FONT></TD>\n", ${$h{ARWA4PH1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ARWA4PH1}}[3], ${$h{ARWA4PH1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWEN6</FONT></TD>\n", ${$h{AORWEN6}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AORWEN6}}[3], ${$h{AORWEN6}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AWD3TQI</FONT></TD>\n", ${$h{AWD3TQI}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AWD3TQI}}[3], ${$h{AWD3TQI}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ARWA6BT</FONT></TD>\n", ${$h{ARWA6BT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{ARWA6BT}}[3], ${$h{ARWA6BT}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ARWA4PH2</FONT></TD>\n", ${$h{ARWA4PH2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ARWA4PH2}}[3], ${$h{ARWA4PH2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWSPD1</FONT></TD>\n", ${$h{AORWSPD1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AORWSPD1}}[3], ${$h{AORWSPD1}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AWD4CV5V</FONT></TD>\n", ${$h{AWD4CV5V}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AWD4CV5V}}[3], ${$h{AWD4CV5V}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AWDE1X</FONT></TD>\n", ${$h{AWDE1X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AWDE1X}}[3], ${$h{AWDE1X}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ARWA4RH1</FONT></TD>\n", ${$h{ARWA4RH1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ARWA4RH1}}[3], ${$h{ARWA4RH1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWSPD2</FONT></TD>\n", ${$h{AORWSPD2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AORWSPD2}}[3], ${$h{AORWSPD2}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AWD4TQI</FONT></TD>\n", ${$h{AWD4TQI}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AWD4TQI}}[3], ${$h{AWD4TQI}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AWDE2X</FONT></TD>\n", ${$h{AWDE2X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AWDE2X}}[3], ${$h{AWDE2X}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ARWA4RH2</FONT></TD>\n", ${$h{ARWA4RH2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ARWA4RH2}}[3], ${$h{ARWA4RH2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWSPD3</FONT></TD>\n", ${$h{AORWSPD3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AORWSPD3}}[3], ${$h{AORWSPD3}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AWD5CV5V</FONT></TD>\n", ${$h{AWD5CV5V}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AWD5CV5V}}[3], ${$h{AWD5CV5V}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AWDE3X</FONT></TD>\n", ${$h{AWDE3X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AWDE3X}}[3], ${$h{AWDE3X}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWAVAI</FONT></TD>\n", ${$h{AORWAVAI}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AORWAVAI}}[3], ${$h{AORWAVAI}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWSPD4</FONT></TD>\n", ${$h{AORWSPD4}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AORWSPD4}}[3], ${$h{AORWSPD4}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AWD5TQI</FONT></TD>\n", ${$h{AWD5TQI}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AWD5TQI}}[3], ${$h{AWD5TQI}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AWDE4X</FONT></TD>\n", ${$h{AWDE4X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AWDE4X}}[3], ${$h{AWDE4X}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWBIAS</FONT></TD>\n", ${$h{AORWBIAS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AORWBIAS}}[3], ${$h{AORWBIAS}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWSPD5</FONT></TD>\n", ${$h{AORWSPD5}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AORWSPD5}}[3], ${$h{AORWSPD5}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AWD6CV5V</FONT></TD>\n", ${$h{AWD6CV5V}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AWD6CV5V}}[3], ${$h{AWD6CV5V}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AWDE5X</FONT></TD>\n", ${$h{AWDE5X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AWDE5X}}[3], ${$h{AWDE5X}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWDEN</FONT></TD>\n", ${$h{AORWDEN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AORWDEN}}[3], ${$h{AORWDEN}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWSPD6</FONT></TD>\n", ${$h{AORWSPD6}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AORWSPD6}}[3], ${$h{AORWSPD6}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AWD6TQI</FONT></TD>\n", ${$h{AWD6TQI}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AWD6TQI}}[3], ${$h{AWD6TQI}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AWDE6X</FONT></TD>\n", ${$h{AWDE6X}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AWDE6X}}[3], ${$h{AWDE6X}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWTYPE</FONT></TD>\n", ${$h{AORWTYPE}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AORWTYPE}}[3], ${$h{AORWTYPE}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n", ${$h{AORWHOLD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n", ${$h{AORWHOLD}}[3];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n", ${$h{AORWHOLD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n", ${$h{AORWHOLD}}[3];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n", ${$h{AORWHOLD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT></TD>\n", ${$h{AORWHOLD}}[3];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AORWHOLD</FONT></TD>\n", ${$h{AORWHOLD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AORWHOLD}}[3], ${$h{AORWHOLD}}[1];
printf SF "</TABLE>\n";
printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>SOLAR ARRAY</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSAANG1</FONT></TD>\n", ${$h{AOSAANG1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOSAANG1}}[3], ${$h{AOSAANG1}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSADAOK</FONT></TD>\n", ${$h{AOSADAOK}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOSADAOK}}[3], ${$h{AOSADAOK}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSAILLM</FONT></TD>\n", ${$h{AOSAILLM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOSAILLM}}[3], ${$h{AOSAILLM}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSPESEL</FONT></TD>\n", ${$h{AOSPESEL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOSPESEL}}[3], ${$h{AOSPESEL}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSAANG2</FONT></TD>\n", ${$h{AOSAANG2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOSAANG2}}[3], ${$h{AOSAANG2}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSADEN</FONT></TD>\n", ${$h{AOSADEN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOSADEN}}[3], ${$h{AOSADEN}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSAMDGD</FONT></TD>\n", ${$h{AOSAMDGD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOSAMDGD}}[3], ${$h{AOSAMDGD}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSAMODE</FONT></TD>\n", ${$h{AOSAMODE}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOSAMODE}}[3], ${$h{AOSAMODE}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSACMD1</FONT></TD>\n", ${$h{AOSACMD1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOSACMD1}}[3], ${$h{AOSACMD1}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSAEST1</FONT></TD>\n", ${$h{AOSAEST1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOSAEST1}}[3], ${$h{AOSAEST1}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSARES1</FONT></TD>\n", ${$h{AOSARES1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOSARES1}}[3], ${$h{AOSARES1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSACMD2</FONT></TD>\n", ${$h{AOSACMD2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOSACMD2}}[3], ${$h{AOSACMD2}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSAEST2</FONT></TD>\n", ${$h{AOSAEST2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOSAEST2}}[3], ${$h{AOSAEST2}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSARES2</FONT></TD>\n", ${$h{AOSARES2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AOSARES2}}[3], ${$h{AOSARES2}}[1];
printf SF "</TABLE>\n";
printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>SPE</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ASPEA5CV</FONT></TD>\n", ${$h{ASPEA5CV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ASPEA5CV}}[3], ${$h{ASPEA5CV}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ASPEAX</FONT></TD>\n", ${$h{ASPEAX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ASPEAX}}[3], ${$h{ASPEAX}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ASPEB5CV</FONT></TD>\n", ${$h{ASPEB5CV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ASPEB5CV}}[3], ${$h{ASPEB5CV}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>ASPEBX</FONT></TD>\n", ${$h{ASPEBX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{ASPEBX}}[3], ${$h{ASPEBX}}[1];
printf SF "</TABLE>\n";
printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>SOFTWARE</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOMGRSTA</FONT></TD>\n", ${$h{AOMGRSTA}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOMGRSTA}}[3], ${$h{AOMGRSTA}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSFFTQ</FONT></TD>\n", ${$h{AOPSFFTQ}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSFFTQ}}[3], ${$h{AOPSFFTQ}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSRWUM</FONT></TD>\n", ${$h{AOPSRWUM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSRWUM}}[3], ${$h{AOPSRWUM}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSSCMM</FONT></TD>\n", ${$h{AOPSSCMM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSSCMM}}[3], ${$h{AOPSSCMM}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSACDP</FONT></TD>\n", ${$h{AOPSACDP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSACDP}}[3], ${$h{AOPSACDP}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSFSDP</FONT></TD>\n", ${$h{AOPSFSDP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSFSDP}}[3], ${$h{AOPSFSDP}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSSACD</FONT></TD>\n", ${$h{AOPSSACD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSSACD}}[3], ${$h{AOPSSACD}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOCSSOK</FONT></TD>\n", ${$h{AOCSSOK}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOCSSOK}}[3], ${$h{AOCSSOK}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSACGN</FONT></TD>\n", ${$h{AOPSACGN}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSACGN}}[3], ${$h{AOPSACGN}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSFSSV</FONT></TD>\n", ${$h{AOPSFSSV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSFSSV}}[3], ${$h{AOPSFSSV}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSSACL</FONT></TD>\n", ${$h{AOPSSACL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSSACL}}[3], ${$h{AOPSSACL}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOECLIPS</FONT></TD>\n", ${$h{AOECLIPS}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOECLIPS}}[3], ${$h{AOECLIPS}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSACPR</FONT></TD>\n", ${$h{AOPSACPR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSACPR}}[3], ${$h{AOPSACPR}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSIRDP</FONT></TD>\n", ${$h{AOPSIRDP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSIRDP}}[3], ${$h{AOPSIRDP}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSSADP</FONT></TD>\n", ${$h{AOPSSADP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSSADP}}[3], ${$h{AOPSSADP}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOECLOVL</FONT></TD>\n", ${$h{AOECLOVL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOECLOVL}}[3], ${$h{AOECLOVL}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSAERM</FONT></TD>\n", ${$h{AOPSAERM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSAERM}}[3], ${$h{AOPSAERM}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSIRUM</FONT></TD>\n", ${$h{AOPSIRUM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSIRUM}}[3], ${$h{AOPSIRUM}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSSAOM</FONT></TD>\n", ${$h{AOPSSAOM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSSAOM}}[3], ${$h{AOPSSAOM}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOECLPSE</FONT></TD>\n", ${$h{AOECLPSE}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOECLPSE}}[3], ${$h{AOECLPSE}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSAMUL</FONT></TD>\n", ${$h{AOPSAMUL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSAMUL}}[3], ${$h{AOPSAMUL}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSKINT</FONT></TD>\n", ${$h{AOPSKINT}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSKINT}}[3], ${$h{AOPSKINT}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSSAPM</FONT></TD>\n", ${$h{AOPSSAPM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSSAPM}}[3], ${$h{AOPSSAPM}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOETIMEX</FONT></TD>\n", ${$h{AOETIMEX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOETIMEX}}[3], ${$h{AOETIMEX}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSATER</FONT></TD>\n", ${$h{AOPSATER}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSATER}}[3], ${$h{AOPSATER}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSLAEM</FONT></TD>\n", ${$h{AOPSLAEM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSLAEM}}[3], ${$h{AOPSLAEM}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSSCAR</FONT></TD>\n", ${$h{AOPSSCAR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSSCAR}}[3], ${$h{AOPSSCAR}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOFATTMD</FONT></TD>\n", ${$h{AOFATTMD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOFATTMD}}[3], ${$h{AOFATTMD}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSATUP</FONT></TD>\n", ${$h{AOPSATUP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSATUP}}[3], ${$h{AOPSATUP}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSPTCL</FONT></TD>\n", ${$h{AOPSPTCL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSPTCL}}[3], ${$h{AOPSPTCL}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSSUCL</FONT></TD>\n", ${$h{AOPSSUCL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSSUCL}}[3], ${$h{AOPSSUCL}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOFATTUP</FONT></TD>\n", ${$h{AOFATTUP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOFATTUP}}[3], ${$h{AOFATTUP}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSAXEP</FONT></TD>\n", ${$h{AOPSAXEP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSAXEP}}[3], ${$h{AOPSAXEP}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSRSEL</FONT></TD>\n", ${$h{AOPSRSEL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSRSEL}}[3], ${$h{AOPSRSEL}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSSUEP</FONT></TD>\n", ${$h{AOPSSUEP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSSUEP}}[3], ${$h{AOPSSUEP}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOGYHEXD</FONT></TD>\n", ${$h{AOGYHEXD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOGYHEXD}}[3], ${$h{AOGYHEXD}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSCATM</FONT></TD>\n", ${$h{AOPSCATM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSCATM}}[3], ${$h{AOPSCATM}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSRWCD</FONT></TD>\n", ${$h{AOPSRWCD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSRWCD}}[3], ${$h{AOPSRWCD}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSSUPM</FONT></TD>\n", ${$h{AOPSSUPM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSSUPM}}[3], ${$h{AOPSSUPM}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOINTOFF</FONT></TD>\n", ${$h{AOINTOFF}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOINTOFF}}[3], ${$h{AOINTOFF}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSCSDP</FONT></TD>\n", ${$h{AOPSCSDP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSCSDP}}[3], ${$h{AOPSCSDP}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSRWCL</FONT></TD>\n", ${$h{AOPSRWCL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSRWCL}}[3], ${$h{AOPSRWCL}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSTHCD</FONT></TD>\n", ${$h{AOPSTHCD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSTHCD}}[3], ${$h{AOPSTHCD}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSUNSA1</FONT></TD>\n", ${$h{AOSUNSA1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOSUNSA1}}[3], ${$h{AOSUNSA1}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSCSSV</FONT></TD>\n", ${$h{AOPSCSSV}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSCSSV}}[3], ${$h{AOPSCSSV}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSRWDP</FONT></TD>\n", ${$h{AOPSRWDP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSRWDP}}[3], ${$h{AOPSRWDP}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSTOCL</FONT></TD>\n", ${$h{AOPSTOCL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSTOCL}}[3], ${$h{AOPSTOCL}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSUNSA2</FONT></TD>\n", ${$h{AOSUNSA2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOSUNSA2}}[3], ${$h{AOSUNSA2}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSDVCD</FONT></TD>\n", ${$h{AOPSDVCD}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSDVCD}}[3], ${$h{AOPSDVCD}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSRWMM</FONT></TD>\n", ${$h{AOPSRWMM}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSRWMM}}[3], ${$h{AOPSRWMM}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOPSTREF</FONT></TD>\n", ${$h{AOPSTREF}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOPSTREF}}[3], ${$h{AOPSTREF}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOSUNSA3</FONT></TD>\n", ${$h{AOSUNSA3}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3e</FONT></TD>\n", ${$h{AOSUNSA3}}[3], ${$h{AOSUNSA3}}[1];
printf SF "</TABLE>\n";
printf SF "<BR>\n";
printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>VDE</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOVAVERR</FONT></TD>\n", ${$h{AOVAVERR}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOVAVERR}}[3], ${$h{AOVAVERR}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AVD1CV5V</FONT></TD>\n", ${$h{AVD1CV5V}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AVD1CV5V}}[3], ${$h{AVD1CV5V}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AVDEAX</FONT></TD>\n", ${$h{AVDEAX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AVDEAX}}[3], ${$h{AVDEAX}}[1];
printf SF "<TR><TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AOVDESEL</FONT></TD>\n", ${$h{AOVDESEL}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AOVDESEL}}[3], ${$h{AOVDESEL}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AVD2CV5V</FONT></TD>\n", ${$h{AVD2CV5V}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{AVD2CV5V}}[3], ${$h{AVD2CV5V}}[1];
printf SF "<TD><FONT SIZE=2>&nbsp</FONT>";
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>AVDEBX</FONT></TD>\n", ${$h{AVDEBX}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{AVDEBX}}[3], ${$h{AVDEBX}}[1];
printf SF "</TABLE>\n";
printf SF "<BR>\n";
close SF;

print_links("$outfile");
print SF "</BODY></HTML>\n";
close SF;
# end
}
1;
