sub soh_format {
  $outfile = shift @_;
  %h = @_;
  print_head("$outfile","Propulsion", %h);

open (SF, ">>$outfile");

printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=11><FONT SIZE=4>MUPS</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FDM-1 MUPS LATCH ISO VALVE 1 (CH0) <br>  OPEN CLOS', CAPTION, 'PF1MV1C1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PF1MV1C1</FONT></a></TD>\n", ${$h{PF1MV1C1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{PF1MV1C1}}[3], ${$h{PF1MV1C1}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('MUPS 1 THRUSTER VALVE 01 TEMP DEGF<br><font color=#FFFF00>(47.0) 130 </font><br><font color=#FF0000>(40.0) 130</font>', CAPTION, 'PM1THV1T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PM1THV1T</FONT></a></TD>\n", ${$h{PM1THV1T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PM1THV1T}}[3], ${$h{PM1THV1T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('MUPS 3 THRUSTER VALVE 01 TEMP DEGF<br><font color=#FFFF00>(47.0) 110 </font><br><font color=#FF0000>(40.0) 110</font>', CAPTION, 'PM3THV1T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PM3THV1T</FONT></a></TD>\n", ${$h{PM3THV1T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PM3THV1T}}[3], ${$h{PM3THV1T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('MUPS CATBED PRI HTR ON/OFF (CH0) <br>  OFF ON', CAPTION, 'PMCBHTP1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PMCBHTP1</FONT></a></TD>\n", ${$h{PMCBHTP1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{PMCBHTP1}}[3], ${$h{PMCBHTP1}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FDM-1 MUPS LATCH ISO VALVE 1 (CH1) <br>  OPEN CLOS', CAPTION, 'PF1MV1C2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PF1MV1C2</FONT></a></TD>\n", ${$h{PF1MV1C2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{PF1MV1C2}}[3], ${$h{PF1MV1C2}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('MUPS 1 THRUSTER VALVE 02 TEMP DEGF<br><font color=#FFFF00>(47.0) 130 </font><br><font color=#FF0000>(40.0) 130</font>', CAPTION, 'PM1THV2T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PM1THV2T</FONT></a></TD>\n", ${$h{PM1THV2T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PM1THV2T}}[3], ${$h{PM1THV2T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('MUPS 3 THRUSTER VALVE 02 TEMP DEGF<br><font color=#FFFF00>(47.0) 110 </font><br><font color=#FF0000>(40.0) 110</font>', CAPTION, 'PM3THV2T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PM3THV2T</FONT></a></TD>\n", ${$h{PM3THV2T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PM3THV2T}}[3], ${$h{PM3THV2T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('MUPS CATBED PRI HTR ON/OFF (CH1) <br>  OFF ON', CAPTION, 'PMCBHTP2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PMCBHTP2</FONT></a></TD>\n", ${$h{PMCBHTP2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{PMCBHTP2}}[3], ${$h{PMCBHTP2}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FDM-1 MUPS LATCH ISO VALVE 2 (CH0) <br>  OPEN CLOS', CAPTION, 'PF1MV2C1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PF1MV2C1</FONT></a></TD>\n", ${$h{PF1MV2C1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{PF1MV2C1}}[3], ${$h{PF1MV2C1}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('MUPS 2 THRUSTER VALVE 01 TEMP DEGF<br><font color=#FFFF00>(47.0) 140 </font><br><font color=#FF0000>(40.0) 140</font>', CAPTION, 'PM2THV1T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PM2THV1T</FONT></a></TD>\n", ${$h{PM2THV1T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PM2THV1T}}[3], ${$h{PM2THV1T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('MUPS 4 THRUSTER VALVE 01 TEMP DEGF<br><font color=#FFFF00>(47.0) 110 </font><br><font color=#FF0000>(40.0) 110</font>', CAPTION, 'PM4THV1T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PM4THV1T</FONT></a></TD>\n", ${$h{PM4THV1T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PM4THV1T}}[3], ${$h{PM4THV1T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('MUPS CATBED HTR RDNT ON/OFF (CH0) <br>  OFF ON', CAPTION, 'PMCBHTR1' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PMCBHTR1</FONT></a></TD>\n", ${$h{PMCBHTR1}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{PMCBHTR1}}[3], ${$h{PMCBHTR1}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FDM-1 MUPS LATCH ISO VALVE 2 (CH1) <br>  OPEN CLOS', CAPTION, 'PF1MV2C2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PF1MV2C2</FONT></a></TD>\n", ${$h{PF1MV2C2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{PF1MV2C2}}[3], ${$h{PF1MV2C2}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('MUPS 2 THRUSTER VALVE 02 TEMP DEGF<br><font color=#FFFF00>(47.0) 140 </font><br><font color=#FF0000>(40.0) 140</font>', CAPTION, 'PM2THV2T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PM2THV2T</FONT></a></TD>\n", ${$h{PM2THV2T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PM2THV2T}}[3], ${$h{PM2THV2T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('MUPS 4 THRUSTER VALVE 02 TEMP DEGF<br><font color=#FFFF00>(47.0) 110 </font><br><font color=#FF0000>(40.0) 110</font>', CAPTION, 'PM4THV2T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PM4THV2T</FONT></a></TD>\n", ${$h{PM4THV2T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PM4THV2T}}[3], ${$h{PM4THV2T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('MUPS CATBED HTR RDNT ON/OFF (CH1) <br>  ON OFF', CAPTION, 'PMCBHTR2' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PMCBHTR2</FONT></a></TD>\n", ${$h{PMCBHTR2}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%s</FONT></TD>\n", ${$h{PMCBHTR2}}[3], ${$h{PMCBHTR2}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('MUPS TANK TEMP 1 DEGF<br><font color=#FFFF00>(60) 90 </font><br><font color=#FF0000>(40.0) 90</font>', CAPTION, 'PMTANK1T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PMTANK1T</FONT></a></TD>\n", ${$h{PMTANK1T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PMTANK1T}}[3], ${$h{PMTANK1T}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('MUPS TANK TEMP 2 DEGF<br><font color=#FFFF00>(60) 90 </font><br><font color=#FF0000>(40.0) 90</font>', CAPTION, 'PMTANK2T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PMTANK2T</FONT></a></TD>\n", ${$h{PMTANK2T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PMTANK2T}}[3], ${$h{PMTANK2T}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('MUPS TANK TEMP 3 DEGF<br><font color=#FFFF00>(60) 90 </font><br><font color=#FF0000>(40.0) 90</font>', CAPTION, 'PMTANK3T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PMTANK3T</FONT></a></TD>\n", ${$h{PMTANK3T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PMTANK3T}}[3], ${$h{PMTANK3T}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('MFP TEMP 1 DEGF<br><font color=#FFFF00>(47.0) 80 </font><br><font color=#FF0000>(40.0) 80</font>', CAPTION, 'PMFP01T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PMFP01T</FONT></a></TD>\n", ${$h{PMFP01T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PMFP01T}}[3], ${$h{PMFP01T}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('MUPS TANK PRESSURE PSIA<br><font color=#FFFF00>(160.0) 350.0 </font><br><font color=#FF0000>(150.0) 350.0</font>', CAPTION, 'PMTANKP' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PMTANKP</FONT></a></TD>\n", ${$h{PMTANKP}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PMTANKP}}[3], ${$h{PMTANKP}}[1];
printf SF "</TABLE>\n";

printf SF "<BR>\n";

printf SF "<TABLE BORDER=0>\n";
printf SF "<TR><TD ALIGN=LEFT COLSPAN=5><FONT SIZE=4>SYSTEM TEMPS</FONT></TR>\n";
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PROP LINE TEMP 01 DEGF<br><font color=#FFFF00>(47.0) 80 </font><br><font color=#FF0000>(40.0) 80</font>', CAPTION, 'PLINE01T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PLINE01T</FONT></a></TD>\n", ${$h{PLINE01T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PLINE01T}}[3], ${$h{PLINE01T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PROP LINE TEMP 09 DEGF<br><font color=#FFFF00>(60) 130 </font><br><font color=#FF0000>(40.0) 130</font>', CAPTION, 'PLINE09T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PLINE09T</FONT></a></TD>\n", ${$h{PLINE09T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PLINE09T}}[3], ${$h{PLINE09T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FDM1 TEMP 01 DEGF<br><font color=#FFFF00>(47.0) 80 </font><br><font color=#FF0000>(40.0) 80</font>', CAPTION, 'PFDM101T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PFDM101T</FONT></a></TD>\n", ${$h{PFDM101T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PFDM101T}}[3], ${$h{PFDM101T}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PROP LINE TEMP 02 DEGF<br><font color=#FFFF00>(47.0) 85 </font><br><font color=#FF0000>(40.0) 85</font>', CAPTION, 'PLINE02T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PLINE02T</FONT></a></TD>\n", ${$h{PLINE02T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PLINE02T}}[3], ${$h{PLINE02T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PROP LINE TEMP 10 DEGF<br><font color=#FFFF00>(65) 110.0 </font><br><font color=#FF0000>(40.0) 110.0</font>', CAPTION, 'PLINE10T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PLINE10T</FONT></a></TD>\n", ${$h{PLINE10T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PLINE10T}}[3], ${$h{PLINE10T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FDM1 TEMP 02 DEGF<br><font color=#FFFF00>(47.0) 80 </font><br><font color=#FF0000>(40.0) 80</font>', CAPTION, 'PFDM102T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PFDM102T</FONT></a></TD>\n", ${$h{PFDM102T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PFDM102T}}[3], ${$h{PFDM102T}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PROP LINE TEMP 03 DEGF<br><font color=#FFFF00>(60) 120.0 </font><br><font color=#FF0000>(40.0) 120.0</font>', CAPTION, 'PLINE03T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PLINE03T</FONT></a></TD>\n", ${$h{PLINE03T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PLINE03T}}[3], ${$h{PLINE03T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PROP LINE TEMP 11 DEGF<br><font color=#FFFF00>(55) 100.0 </font><br><font color=#FF0000>(40.0) 100.0</font>', CAPTION, 'PLINE11T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PLINE11T</FONT></a></TD>\n", ${$h{PLINE11T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PLINE11T}}[3], ${$h{PLINE11T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FDM2 TEMP 01 DEGF<br><font color=#FFFF00>(47.0) 80 </font><br><font color=#FF0000>(40.0) 80</font>', CAPTION, 'PFDM201T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PFDM201T</FONT></a></TD>\n", ${$h{PFDM201T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PFDM201T}}[3], ${$h{PFDM201T}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PROP LINE TEMP 04 DEGF<br><font color=#FFFF00>(47.0) 100 </font><br><font color=#FF0000>(40.0) 100</font>', CAPTION, 'PLINE04T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PLINE04T</FONT></a></TD>\n", ${$h{PLINE04T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PLINE04T}}[3], ${$h{PLINE04T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PROP LINE TEMP 12 DEGF<br><font color=#FFFF00>(47.0) 80 </font><br><font color=#FF0000>(40.0) 80</font>', CAPTION, 'PLINE12T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PLINE12T</FONT></a></TD>\n", ${$h{PLINE12T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PLINE12T}}[3], ${$h{PLINE12T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FDM2 TEMP 02 DEGF<br><font color=#FFFF00>(47.0) 80 </font><br><font color=#FF0000>(40.0) 80</font>', CAPTION, 'PFDM202T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PFDM202T</FONT></a></TD>\n", ${$h{PFDM202T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PFDM202T}}[3], ${$h{PFDM202T}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PROP LINE TEMP 05 DEGF<br><font color=#FFFF00>(47.0) 90 </font><br><font color=#FF0000>(40.0) 90</font>', CAPTION, 'PLINE05T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PLINE05T</FONT></a></TD>\n", ${$h{PLINE05T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PLINE05T}}[3], ${$h{PLINE05T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PROP LINE TEMP 13 DEGF<br><font color=#FFFF00>(47.0) 80 </font><br><font color=#FF0000>(40.0) 80</font>', CAPTION, 'PLINE13T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PLINE13T</FONT></a></TD>\n", ${$h{PLINE13T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PLINE13T}}[3], ${$h{PLINE13T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FFP TEMP 1 DEGF<br><font color=#FFFF00>(47.0) 100.0 </font><br><font color=#FF0000>(40.0) 100.0</font>', CAPTION, 'PFFP01T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PFFP01T</FONT></a></TD>\n", ${$h{PFFP01T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PFFP01T}}[3], ${$h{PFFP01T}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PROP LINE TEMP 06 DEGF<br><font color=#FFFF00>(45) 75 </font><br><font color=#FF0000>(40.0) 75</font>', CAPTION, 'PLINE06T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PLINE06T</FONT></a></TD>\n", ${$h{PLINE06T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PLINE06T}}[3], ${$h{PLINE06T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PROP LINE TEMP 14 DEGF<br><font color=#FFFF00>(45) 80 </font><br><font color=#FF0000>(20.0) 80</font>', CAPTION, 'PLINE14T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PLINE14T</FONT></a></TD>\n", ${$h{PLINE14T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PLINE14T}}[3], ${$h{PLINE14T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FUEL TANK TEMP 01 DEGF<br><font color=#FFFF00>(60) 90.0 </font><br><font color=#FF0000>(40.0) 90.0</font>', CAPTION, 'PFTANK1T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PFTANK1T</FONT></a></TD>\n", ${$h{PFTANK1T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PFTANK1T}}[3], ${$h{PFTANK1T}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PROP LINE TEMP 07 DEGF<br><font color=#FFFF00>(47.0) 95 </font><br><font color=#FF0000>(40.0) 95</font>', CAPTION, 'PLINE07T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PLINE07T</FONT></a></TD>\n", ${$h{PLINE07T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PLINE07T}}[3], ${$h{PLINE07T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PROP LINE TEMP 15 DEGF<br><font color=#FFFF00>(45) 80 </font><br><font color=#FF0000>(30.0) 80</font>', CAPTION, 'PLINE15T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PLINE15T</FONT></a></TD>\n", ${$h{PLINE15T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PLINE15T}}[3], ${$h{PLINE15T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('FUEL TANK TEMP 02 DEGF<br><font color=#FFFF00>(60) 90.0 </font><br><font color=#FF0000>(40.0) 90.0</font>', CAPTION, 'PFTANK2T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PFTANK2T</FONT></a></TD>\n", ${$h{PFTANK2T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PFTANK2T}}[3], ${$h{PFTANK2T}}[1];
printf SF "<TR><TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PROP LINE TEMP 08 DEGF<br><font color=#FFFF00>(47.0) 85 </font><br><font color=#FF0000>(40.0) 85</font>', CAPTION, 'PLINE08T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PLINE08T</FONT></a></TD>\n", ${$h{PLINE08T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PLINE08T}}[3], ${$h{PLINE08T}}[1];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2>&nbsp</FONT>\n";
printf SF "<TD ALIGN=LEFT> <a href=\"javascript:void(0);\" style=\"text-decoration: none;\" onmouseover=\"return overlib ('PROP LINE TEMP 16 DEGF<br><font color=#FFFF00>(47.0) 100.0 </font><br><font color=#FF0000>(40.0) 100.0</font>', CAPTION, 'PLINE16T' );\" onmouseout=\"return nd();\"><FONT SIZE=2 COLOR=%s>PLINE16T</FONT></a></TD>\n", ${$h{PLINE16T}}[3];
printf SF "<TD ALIGN=LEFT><FONT SIZE=2 COLOR=%s>%.3f</FONT></TD>\n", ${$h{PLINE16T}}[3], ${$h{PLINE16T}}[1];
printf SF "</TABLE>\n";
printf SF "<BR>\n";
close SF;

print_links("$outfile");
print SF "</BODY></HTML>\n";
close SF;
# end
}
1;
